
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/30/2023 12:49:21 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230830124924 ON [FAS].[DBO].[GLCONTRAHEADER] ([ISCANCEL],[COMPANYCODE],[BRANCHCODE]) INCLUDE ([TXNDATE],[REMARK],[CONTRANO]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_GLCONTRADETAIL] ON [FAS].[DBO].[GLCONTRADETAIL] ([BRANCHCODE],[COMPANYCODE],[CONTRANO],[DOCUMENTNO],[DOCUMENTTYPE],[ISCANCEL]) INCLUDE ([TXNDATE],[REMARK],[LOCALAMOUNT]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
