

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230830124924 ON [FAS].[DBO].[GLCONTRAHEADER]; 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_GLCONTRADETAIL] ON [FAS].[DBO].[GLCONTRADETAIL] ([BRANCHCODE],[COMPANYCODE],[CONTRANO],[DOCUMENTNO],[DOCUMENTTYPE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;
