
USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ASN];
		PRINT N'INDEX IX_AIDBA_1_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ASN] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ASN] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRUCK];
		PRINT N'INDEX IX_AIDBA_2_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRUCK] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRUCK] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRUCK_QUEUE];
		PRINT N'INDEX IX_AIDBA_3_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRUCK_QUEUE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRUCK_QUEUE] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230502 ON [SPRITZERTAIPINGDB].[dbo].[LOCATION];
		PRINT N'INDEX IX_AIDBA_4_20230502 ON [SPRITZERTAIPINGDB].[dbo].[LOCATION] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230502 ON [SPRITZERTAIPINGDB].[dbo].[LOCATION] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230502 ON [SPRITZERTAIPINGDB].[dbo].[SHIPMENT];
		PRINT N'INDEX IX_AIDBA_5_20230502 ON [SPRITZERTAIPINGDB].[dbo].[SHIPMENT] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230502 ON [SPRITZERTAIPINGDB].[dbo].[SHIPMENT] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_6_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_6_20230502 ON [SPRITZERTAIPINGDB].[dbo].[SHIPPED_INVENTORY];
		PRINT N'INDEX IX_AIDBA_6_20230502 ON [SPRITZERTAIPINGDB].[dbo].[SHIPPED_INVENTORY] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_6_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_6_20230502 ON [SPRITZERTAIPINGDB].[dbo].[SHIPPED_INVENTORY] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_7_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_7_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_UNIT];
		PRINT N'INDEX IX_AIDBA_7_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_UNIT] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_7_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_7_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_UNIT] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_8_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_8_20230502 ON [SPRITZERTAIPINGDB].[dbo].[EVENTLOG];
		PRINT N'INDEX IX_AIDBA_8_20230502 ON [SPRITZERTAIPINGDB].[dbo].[EVENTLOG] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_8_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_8_20230502 ON [SPRITZERTAIPINGDB].[dbo].[EVENTLOG] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_9_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_9_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANS];
		PRINT N'INDEX IX_AIDBA_9_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANS] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_9_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_9_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANS] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_10_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_10_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_HEADER];
		PRINT N'INDEX IX_AIDBA_10_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_HEADER] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_10_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_10_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_HEADER] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_11_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_11_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_LOG];
		PRINT N'INDEX IX_AIDBA_11_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_LOG] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_11_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_11_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_LOG] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_12_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_12_20230502 ON [SPRITZERTAIPINGDB].[dbo].[CHECKIN_DETAIL];
		PRINT N'INDEX IX_AIDBA_12_20230502 ON [SPRITZERTAIPINGDB].[dbo].[CHECKIN_DETAIL] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_12_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_12_20230502 ON [SPRITZERTAIPINGDB].[dbo].[CHECKIN_DETAIL] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_13_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_13_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TELEGRAM_LOG];
		PRINT N'INDEX IX_AIDBA_13_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TELEGRAM_LOG] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_13_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_13_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TELEGRAM_LOG] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_14_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_14_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TASK];
		PRINT N'INDEX IX_AIDBA_14_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TASK] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_14_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_14_20230502 ON [SPRITZERTAIPINGDB].[dbo].[TASK] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_15_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_15_20230502 ON [SPRITZERTAIPINGDB].[dbo].[EXPECTED_RECEIPT];
		PRINT N'INDEX IX_AIDBA_15_20230502 ON [SPRITZERTAIPINGDB].[dbo].[EXPECTED_RECEIPT] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_15_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_15_20230502 ON [SPRITZERTAIPINGDB].[dbo].[EXPECTED_RECEIPT] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_16_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_16_20230502 ON [SPRITZERTAIPINGDB].[dbo].[HOST_MESSAGE];
		PRINT N'INDEX IX_AIDBA_16_20230502 ON [SPRITZERTAIPINGDB].[dbo].[HOST_MESSAGE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_16_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_16_20230502 ON [SPRITZERTAIPINGDB].[dbo].[HOST_MESSAGE] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_17_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_17_20230502 ON [SPRITZERTAIPINGDB].[dbo].[AUDIT_TRAIL];
		PRINT N'INDEX IX_AIDBA_17_20230502 ON [SPRITZERTAIPINGDB].[dbo].[AUDIT_TRAIL] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_17_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_17_20230502 ON [SPRITZERTAIPINGDB].[dbo].[AUDIT_TRAIL] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_18_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_18_20230502 ON [SPRITZERTAIPINGDB].[dbo].[WORK_ORDER];
		PRINT N'INDEX IX_AIDBA_18_20230502 ON [SPRITZERTAIPINGDB].[dbo].[WORK_ORDER] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_18_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_18_20230502 ON [SPRITZERTAIPINGDB].[dbo].[WORK_ORDER] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_19_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_19_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ARCHIVED_ORDER_HEADER];
		PRINT N'INDEX IX_AIDBA_19_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ARCHIVED_ORDER_HEADER] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_19_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_19_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ARCHIVED_ORDER_HEADER] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_20_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_20_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ARCHIVED_ASN];
		PRINT N'INDEX IX_AIDBA_20_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ARCHIVED_ASN] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_20_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_20_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ARCHIVED_ASN] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_21_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_21_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_LOG];
		PRINT N'INDEX IX_AIDBA_21_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_LOG] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_21_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_21_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_LOG] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_22_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_22_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_LINE];
		PRINT N'INDEX IX_AIDBA_22_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_LINE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_22_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_22_20230502 ON [SPRITZERTAIPINGDB].[dbo].[ORDER_LINE] CANNOT BE DROPPED.';
END CATCH;
