
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/18/2023 6:00:04 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230518060006 ON [SPRITZERTAIPINGDB].[DBO].[TASK_GROUP] ([TU_TYPE_ID],[PICK_METHOD],[CLASS_TYPE],[STATUS],[WORK_ZONE_KEY],[TASK_GROUP_KEY],[EQUIPMENT_KEY],[CREATE_DATE],[CREATED_BY],[UPDATED_BY]) INCLUDE ([STATUS_DATE],[TRANSACTION_COUNT],[UPDATE_DATE],[ORDER_GROUP_KEY],[WORKSTATION_ID],[WORKSTATION_LOCATION_KEY],[USER_ID],[DESTINATION_UOM_TREE],[DESTINATION_TU_TYPE],[STRICT_SEQUENCE],[TARGET_DATE],[TASK_GROUP_ID],[TASK_GROUP_TYPE],[TASK_GROUP_COLL_KEY],[ORDER_TU_PLAN_KEY],[ERP_GROUP_TYPE_DESCRIPTION],[ERP_GROUP_TYPE_ID],[ERP_TARGET_DATE],[SOURCE_UOM_TREE],[TOTAL_PALLET_REQUEST],[SOURCE_TU_TYPE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230518060018 ON [SPRITZERTAIPINGDB].[DBO].[HOST_MESSAGE] ([HOST_MESSAGE_KEY],[CLASS_TYPE]) ;
 END TRY BEGIN CATCH END CATCH;
