
BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N001006]
	ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N001006]
	ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00791]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00791] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00791] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00791]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00791] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00791] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Fard_IX_01_31032022]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Fard_IX_01_31032022]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00277]
	ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00277] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00277] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_10258]
	ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00277]
	ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00277] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00277] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_10258]
	ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_50697]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS_TEST].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS_TEST].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_50697]
	ON [MIMS].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] CANNOT BE ENABLED.';
END CATCH;
