
BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N001006')
	BEGIN
	ALTER INDEX [IDX_N001006]
	ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] DISABLE;
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N001006')
	BEGIN
	ALTER INDEX [IDX_N001006]
	ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] DISABLE;
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_116_115')
	BEGIN
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] DISABLE;
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_116_115')
	BEGIN
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] DISABLE;
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'PEDIDO_VENDA_ITEM')
	BEGIN
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'PEDIDO_VENDA_ITEM')
	BEGIN
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00791')
	BEGIN
	ALTER INDEX [IDX_N00791]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] DISABLE;
	PRINT 'INDEX [IDX_N00791] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00791] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00791')
	BEGIN
	ALTER INDEX [IDX_N00791]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] DISABLE;
	PRINT 'INDEX [IDX_N00791] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00791] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Fard_IX_01_31032022')
	BEGIN
	ALTER INDEX [Fard_IX_01_31032022]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] DISABLE;
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Fard_IX_01_31032022')
	BEGIN
	ALTER INDEX [Fard_IX_01_31032022]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] DISABLE;
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Fard_IX_01_31032022] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00277')
	BEGIN
	ALTER INDEX [IDX_N00277]
	ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] DISABLE;
	PRINT 'INDEX [IDX_N00277] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00277] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_10258')
	BEGIN
	ALTER INDEX [FARD_IX_10258]
	ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] DISABLE;
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00277')
	BEGIN
	ALTER INDEX [IDX_N00277]
	ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] DISABLE;
	PRINT 'INDEX [IDX_N00277] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00277] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_10258')
	BEGIN
	ALTER INDEX [FARD_IX_10258]
	ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] DISABLE;
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_10258] ON [MIMS_TEST].[dbo].[EXPEDICAO_CARGA_IDENTIFICACAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_50697')
	BEGIN
	ALTER INDEX [FARD_IX_50697]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] DISABLE;
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS_TEST].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS_TEST].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_50697')
	BEGIN
	ALTER INDEX [FARD_IX_50697]
	ON [MIMS].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] DISABLE;
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_50697] ON [MIMS].[dbo].[PRODUCAO_REGI_UNID_ITEM_DETA] CANNOT BE DISABLED.';
END CATCH;
