
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/9/2023 7:27:42 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809192750 ON [MIMS].[DBO].[PEDIDO_VENDA] ([ID_PEDIVEND],[FL_STATPEDIVEND],[ID_MOEDA],[ID_MOEDA_DESPESA],[ID_MOEDA_FRETE],[ID_MOEDA_SEGURO],[FL_SINCINTEPEDIVEND],[FL_SINCINTEFILIPEDIVEND],[ID_FORNECEDOR_DISTRIBUICAO],[IE_PEDIVEND],[NR_LOTEINTEPEDIVEND],[NR_LOTEINTEFILIPEDIVEND]) INCLUDE ([ID_CARGEXPE],[DT_ALTESTATPEDIVEND],[NR_ORDEENTRPEDIVEND],[DT_ORDEENTRPEDIVEND],[NM_LOGIUSUAORDEENTRPEDIVEND],[NR_INVOPEDIVEND],[DT_INVOPEDIVEND],[NM_LOGIUSUAINVOPEDIVEND],[VL_INVOPEDIVEND],[VL_TOTAIMPOINVOPEDIVEND],[VL_ARREIMPOPEDIVEND],[FL_STATPICKPEDIVEND],[DT_LIMIEXPEPEDIVEND],[FILIAL]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND],[ID_ITEMPEDIVEND]) INCLUDE ([QN_PESOPADREXPEITEMPEDIVEND],[QN_PESOREALEXPEITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) INCLUDE ([ID_DETAITEMPEDIVEND],[QN_PESOEXPEDETAITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
