
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/14/2023 8:21:27 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230814082130 ON [SPRITZERTAIPINGDB].[DBO].[TRANSPORT_ORDER] ([STATUS],[CLASS_TYPE],[SUBSYSTEM_ID],[FLOW_STATE]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[PRIORITY],[TRANSPORT_ORDER_KEY],[ACTIVE_ERROR_HANDLING],[ASSIGNMENT_DESTINATION_POS],[ASSIGNMENT_GROUP_ID],[ASSIGNMENT_GROUP_SIZE],[ASSIGNMENT_ORIENTATION],[ASSIGNMENT_SEQUENCE],[ASSIGNMENT_SEQUENCE_SIZE],[ASSIGNMENT_SOURCE_POSITION],[ASSIGNMENT_SUB_SEQUENCE],[DESTINATION_SLOT],[ERROR_HANDLING_START_DATE],[EXPRESS],[FLOW_STACK],[HANDOVER_STATION_ID],[LAST_REPORTED_POSITION],[LOOP_COUNTER],[DESTINATION_LOCATION_KEY],[DESTINATION_NODE_ID],[TRANSPORT_EQUIPMENT_ID],[LAST_PASSED_SEQUENCE_NODE_ID],[OPERATION_ID],[REQUESTED_DESTINATION_NODE_ID],[REQUESTED_TRANSPORT_EQUIP_ID],[SOURCE_LOCATION_KEY],[SOURCE_NODE_ID],[KEY_OF_TO_TO_WAIT_FOR],[TU_KEY],[TU_TYPE_ID],[REQUESTED_ASSIGNMENT_KEY],[TRANSPORT_ASSIGNMENT_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230814082131 ON [SPRITZERTAIPINGDB].[DBO].[EVENTLOG] ([EVENT_KEY],[SEVERITY],[CLASS_TYPE],[ORIGIN_CATEGORY]) INCLUDE ([OCCURRENCE_DATE],[MESSAGE],[OCCURRENCE_COUNT],[TRANSLATED_MESSAGE]) ;
 END TRY BEGIN CATCH END CATCH;
