
BEGIN TRY
	ALTER INDEX [IX_LASTMODDATE_07]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IX_LASTMODDATE_07] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_LASTMODDATE_07] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IX_FL_OPERMOVIREGIPROD_ID_PALEEXPE_FL_SINCMIDDMOVIREGIPROD_04]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IX_FL_OPERMOVIREGIPROD_ID_PALEEXPE_FL_SINCMIDDMOVIREGIPROD_04] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_FL_OPERMOVIREGIPROD_ID_PALEEXPE_FL_SINCMIDDMOVIREGIPROD_04] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IX_ID_PALEEXPE_FL_OPERMOVIREGIPROD_FL_SINCMIDDMOVIREGIPROD_05]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IX_ID_PALEEXPE_FL_OPERMOVIREGIPROD_FL_SINCMIDDMOVIREGIPROD_05] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_ID_PALEEXPE_FL_OPERMOVIREGIPROD_FL_SINCMIDDMOVIREGIPROD_05] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_1344]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_1344] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_1344] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [ix_PRODUCAO_REGISTRO_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_STATREGIPROD_FL_ORIGREGIPROD_includes]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_STATREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_STATREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00807]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00807] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00807] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N10143]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N10143] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10143] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00801]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00801] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00801] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_LANC_REGIPROD_TRAN]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_LANC_REGIPROD_TRAN] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_LANC_REGIPROD_TRAN] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_LANC_ALMO_OPER_TIPO]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_LANC_ALMO_OPER_TIPO] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_LANC_ALMO_OPER_TIPO] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_PEDIVEND_004]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_PEDIVEND_004] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PEDIVEND_004] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_119]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_119] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_119] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00628]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_REGIPROD_SINCMIDD]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_REGIPROD_SINCMIDD] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_REGIPROD_SINCMIDD] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00790]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00790] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00790] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00789]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00789] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00789] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_PRODUCAO_REGISTRO_REGIPROD_BATC]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_PRODUCAO_REGISTRO_REGIPROD_BATC] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PRODUCAO_REGISTRO_REGIPROD_BATC] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [<Name of Missing Index, sysname,>]
	ON [MIMS].[dbo].[EXPEDICAO_PALETE_MOVIMENTACAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [<Name of Missing Index, sysname,>] ON [MIMS].[dbo].[EXPEDICAO_PALETE_MOVIMENTACAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [<Name of Missing Index, sysname,>] ON [MIMS].[dbo].[EXPEDICAO_PALETE_MOVIMENTACAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_REGIPROD]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO_DEST_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_REGIPROD] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_DEST_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_REGIPROD] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_DEST_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_FK_PEBAPROD_PRIMMATEBATCPROD_ID_PRIMMATEBATCPROD]
	ON [MIMS].[dbo].[PRODUCAO_BATCH_PESAGEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_FK_PEBAPROD_PRIMMATEBATCPROD_ID_PRIMMATEBATCPROD] ON [MIMS].[dbo].[PRODUCAO_BATCH_PESAGEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_FK_PEBAPROD_PRIMMATEBATCPROD_ID_PRIMMATEBATCPROD] ON [MIMS].[dbo].[PRODUCAO_BATCH_PESAGEM] CANNOT BE ENABLED.';
END CATCH;
