
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/9/2023 7:21:42 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809192217 ON [MIMS].[DBO].[PRODUCAO_REGISTRO_ESTOQUE_FECH] ([FILIAL],[EMPRESA],[ID_UNIDABAT],[FL_STATFECHESTOREGIPROD],[DT_INICFECHESTOREGIPROD],[DT_FINAFECHESTOREGIPROD]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_EMBADEFI] ON [MIMS].[DBO].[EMBALAGEM_DEFINICAO] ([ID_DEFIEMBA],[ID_MATEALMO],[EMPRESA],[ID_EMBALAGEM],[ID_ALMOXARIFADO]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_FK_ITEM_DESTREGIPROD_ID_DESTREGIPROD] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_DEST_ITEM] ([ID_DESTREGIPROD],[ID_ITEMDESTREGIPROD]) INCLUDE ([ID_REGIPROD],[ID_PROCLINH],[FL_TIPOITEMDESTREGIPROD],[ID_CORTLOTEPROD],[ID_MOTIDESTPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA__DTA_INDEX_MATERIAL_EMBALAGEM_DEFINICAO_12_416720537__K3_K2_6] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_DEFINICAO] ([ID_DEFIMATEEMBA],[ID_PRODDEFIMATEEMBA],[FL_PRODBATCDEFIMATEEMBA]) INCLUDE ([ID_MATERIAL],[NM_PRODDEFIMATEEMBA],[ID_VALIMATEEMBA],[FL_ESPEDEFIMATEEMBA],[FL_ESTADEFIMATEEMBA],[ID_TIPOAVE],[IE_DEFIMATEEMBA],[ID_MARCA],[ID_FAMIPROD],[FL_SEMIACABDEFIMATEEMBA],[FL_CONDDEFIMATEEMBA],[QN_CAPAPADRDEFIMATEEMBA],[QN_CAPAMEDIDEFIMATEEMBA],[QN_PRODEMBAMATEEMBADEFI],[ID_EMBALAGEM],[NM_PRODREDUDEFIMATEEMBA],[ID_VALONUTR],[PC_QUEBDEFIMATEEMBA],[QN_ANIMEMBAMATEEMBADEFI]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809192313 ON [MIMS].[DBO].[PRODUCAO_BATCH_PESAGEM_REPO] ([ID_USUASIST],[ID_REPOPESABATCPROD],[ID_BATCPROD],[FL_DESCREPOPESABATCPROD]) INCLUDE ([QN_PESOREPOPESABATCPROD],[NR_LOTEREPOPESABATCPROD],[ID_REGIPROD],[QN_BRUTREPOPESABATCPROD],[QN_TARAREPOPESABATCPROD],[NR_CODIBARRREPOPESABATCPROD],[ID_ALMOXARIFADO]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_REGIPRODBATC] ON [MIMS].[DBO].[PRODUCAO_REGISTRO] ([ID_BATCPROD],[ID_REGIPROD],[ID_PRODMATEEMBA],[FL_STATREGIPROD],[FL_REGITRANREGIPROD],[FL_ORIGREGIPROD]) INCLUDE ([ID_IDENREGIPROD],[ID_MATERIAL],[ID_ALMOXARIFADO],[DT_REGIPROD],[DT_PADRREGIPROD],[DT_BALAREGIPROD],[ID_BALANCA],[QN_PESOPADRREGIPROD],[QN_PESOLIQUREGIPROD],[QN_TARAEMBAREGIPROD],[DT_ENTRTUNEREGIPROD],[DT_SAIDTUNEREGIPROD],[ID_TUNEPROD],[ID_PALEEXPE],[FL_SITUREGIPROD],[NR_LOTERASTREGIPROD],[FL_SEQUREGIPROD],[DT_VALIREGIPROD],[DT_ELABREGIPROD],[QN_PRODEMBAREGIPROD],[QN_CAIXREGIPROD],[QN_PESOQUEBREGIPROD],[FL_TIPOUNIDREGIPROD],[ID_FORNECEDOR],[GN_TAGREGIPROD],[ID_USUASIST_ENTRTUNEREGIPROD],[ID_USUASIST_SAIDTUNEREGIPROD],[NR_LOTERASTEXTEREGIPROD],[ID_EMBALAGEM],[ID_MATEALMO],[QN_TARACOMPREGIPROD],[ID_USUASIST_REGIPROD],[FL_SIMUREGIPROD],[FL_PRODPROPREGIPROD],[ID_ESTRUNIDABAT],[ID_ENTRAVEVIVA],[QN_PESOORIGREGIPROD],[FL_MODAREGIPROD],[DT_REFEREGIPROD],[ID_IDENORIGDESMREGIPROD],[ID_PACKPROD],[ID_INVEPROD],[NR_SEQUTURNREGIPROD],[FILIAL_IMPRESSA],[EMPRESA_IMPRESSA],[ID_PROCTERMPRODADICMATECONS],[QN_TARAPRIMREGIPROD],[ID_CENTCUST],[FL_SOBRREGIPROD],[ID_ALMOXARIFADO_PRODUCAO],[ID_ITEMDESTREGIPROD_AUTO],[QN_ANIMEMBAREGIPROD],[FL_PROCORIGREGIPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_408] ON [MIMS].[DBO].[CLIENTE_FILIAL] ([ID_CLIENTE]) INCLUDE ([ID_FILICLIE],[FILIAL]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK__INTERFAC__C28E7352542E0D3F] ON [MIMS].[DBO].[INTERFACE_MATERIAL_CONSUMO] ([ID_CONSMATEINTE],[FL_TIPOMATECONSMATEINTE],[IE_FILISIST],[IE_MATERIAL],[NR_LOTEMATE],[IE_ALMOXARIFADO],[ID_PROGPROD],[SG_UNIDMEDI],[NR_CODIBARR]) INCLUDE ([QN_CONSMATEINTE],[FL_OPERCONSMATEINTE],[NM_UNIDMEDI]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_MULTPROGPROD] ON [MIMS].[DBO].[PRODUCAO_PROGRAMACAO_MULTIPLA] ([ID_MULTPROGPROD],[FILIAL],[DT_MULTPROGPROD],[QN_UNIDMULTPROGPROD],[ID_PROGPROD],[FL_SINCMIDDMULTPROGPROD],[FL_BLOQPRODEXCEMULTPROGPROD],[NR_PRIOMULTPROGPROD]) INCLUDE ([ID_PRODMATEEMBA],[NR_SEQUTURNMULTPROGPROD],[EMPRESA],[QN_CAIXMULTPROGPROD],[QN_PESOMULTPROGPROD],[ID_CLIENTE],[ID_PEDIVEND],[GN_TAGMULTPROGPROD],[ID_ETIQUETA],[QN_ALERANTEEXPRMULTPROGPROD],[FL_EXIBPAINCONTMULTPROGPROD],[FL_ALERANTEEXPRMULTPROGPROD],[FX_MULTPROGPROD],[ID_UNIDABAT],[ID_SIMUPROGPROD],[FL_CONSESTOMULTPROGPROD],[QN_ESTOINICMULTPROGPROD],[QN_CAIXORIGMULTPROGPROD],[DT_CONSESTOMULTPROGPROD],[FL_SINCMIDDMAREMULTPROGPROD],[FL_STATMIDDMAREMULTPROGPROD],[ID_ALMODESTMULTPROGPROD],[GN_OBSEMIDDMAREMULTPROGPROD],[ID_USUASIST_CRIAPROG],[ID_USUASIST_VALIMARE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_SYS_C0013374] ON [MIMS].[DBO].[EXPEDICAO_PALETE] ([ID_PALEEXPE],[ID_MATEEMBA]) INCLUDE ([EMPRESA],[FILIAL],[NR_IDENPALEEXPE],[DT_PALEEXPE],[QN_EMBAPALEEXPE],[DT_ABERPALEEXPE],[DT_FECHPALEEXPE],[ID_SSCCPALEEXPE],[QN_DIASVALIMATEPALEEXPE],[QN_PESOLIQUPALEEXPE],[QN_TARAEMBAPALEEXPE],[FX_PALEEXPE],[QN_PESOBASEPALEEXPE],[ID_CLIENTE],[ID_USUASIST_ABERTURA],[ID_USUASIST_FECHAMENTO],[FL_TIPOETIQPALEEXPE],[FL_SITUPALEEXPE],[FL_DISPPALEEXPE],[QN_PESOREALPALEEXPE],[NR_MODEETIQSSCCPALEEXPE],[FL_ETIQCOMPPALEEXPE],[QN_DIASTOLEDTPADRPALEEXPE],[ID_EMBAPALEEXPE],[IE_PALEEXPE],[ID_ALMOTRANSINTEPALEEXPE],[ID_USUASIST_EXCLUSAO],[DT_EXCLPALEEXPE],[GN_LOGEXCLPALEEXPE],[FL_TIPORESTPROD],[FL_SINCMIDDPALEEXPE],[ID_PEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_PRODBATCMATEPRIM_0008] ON [MIMS].[DBO].[PRODUCAO_BATCH_MATERIA_PRIMA] ([ID_BATCPROD],[ID_MATEEMBAFILI],[ID_PRIMMATEBATCPROD],[ID_PRODMATEEMBA],[QN_PESODOSABATCPROD],[QN_PESOREQUBATCPROD],[QN_QTDEMATEPRIMBATCPROD]) INCLUDE ([ID_MATERIAL],[NR_ORDEMATEPRIMBATCPROD],[FX_PRIMMATEBATCPROD],[ID_MATESUBS],[SUBS],[QN_SUBSMATEPRIMBATCPROD],[FL_DOSABATCPROD],[FL_MANUINCLPRIMMATEBATCPROD],[ID_AGRUINGRMATEEMBA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_197] ON [MIMS].[DBO].[PRODUCAO_BATCH_REPOSITORIO] ([EMPRESA],[FILIAL]) INCLUDE ([ID_REPOBATCPROD],[NR_ETIQREPOBATCPROD],[NR_REPOBATCPROD],[ID_MATEEMBA],[DT_PADRREPOBATCPROD],[FL_STATREPOBATCPROD],[QN_TAMAREPOBATCPROD],[ID_CLASMATE],[ID_BATCPROD],[ID_RECEREPOBATCPROD],[ID_AGRUINGRMATEEMBA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PRODUCAO_BATCH_MATE_PRIM_REPO_ID_REPOBATCPROD] ON [MIMS].[DBO].[PRODUCAO_BATCH_MATE_PRIM_REPO] ([ID_REPOBATCPROD],[ID_REPOPRIMMATEBATCPROD]) INCLUDE ([ID_MATERIAL],[ID_MATEEMBAFILI],[ID_PRODMATEEMBA],[QN_PESOREQUREPOBATCPROD],[FL_DOSAREPOBATCPROD],[QN_PESODOSAREPOBATCPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_SYS_C0012203] ON [MIMS].[DBO].[CAMINHAO_PROGRAMACAO] ([ID_PROGCAMI],[FILIAL],[EMPRESA]) INCLUDE ([FL_STATPROGCAMI],[FX_PROGCAMI]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA__DTA_INDEX_MATERIAL_EMBALAGEM_LOCAL_12_688721506__K4_2] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_LOCAL] ([ID_MATEEMBAFILI],[EMPRESA],[ID_MATEEMBALOCA]) INCLUDE ([FILIAL],[QN_TARACOMPMATEEMBALOCA],[QN_PRODEMBAATUAMATEEMBALOCA],[QN_ANIMEMBAATUAMATEEMBALOCA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA__DTA_INDEX_MATERIAL_EMBALAGEM_FILIAL_12_464720708__K4_K3_2] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([ID_DEFIMATEEMBA],[ID_MATEEMBAFILI],[FL_ATIVMATEEMBAFILI]) INCLUDE ([FILIAL],[FL_CONTTUNEMATEEMBAFILI],[ID_PROCLINH],[NM_PRODFILIMATEEMBA],[ID_CENTCUST],[QN_PRODEMBAMATEEMBAFILI],[ID_ESTRMATEEMBAFILI],[QN_ANIMEMBAMATEEMBAFILI],[ID_MODEETIQIMPRMATEEMBAFILI],[PC_TOLEMINIMATEEMBAFILI],[PC_TOLEMAXIMATEEMBAFILI]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_INDEPALEEXPE_PALEREGIPROD] ON [MIMS].[DBO].[EXPEDICAO_PALETE_IDENTIFICACAO] ([ID_PALEEXPE],[ID_IDENPALEEXPE]) INCLUDE ([ID_REGIPROD],[QN_PESOLIQUIDENPALEEXPE],[QN_TARAEMBAIDENPALEEXPE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_60] ON [MIMS].[DBO].[ENTRADA_AVE_VIVA] ([FL_SINCMIDDDESCENTRAVEVIVA],[IE_LOTEENTRAVEVIVA],[ID_ENTRAVEVIVA]) INCLUDE ([ID_VEICTRAN],[ID_REGIDATAPADR],[ID_ESTAPENDESTRUNIDABAT]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_ORDEPESA_ENTRAVEVIVA] ON [MIMS].[DBO].[PESAGEM_ORDEM] ([ID_ENTRAVEVIVA],[ID_ORDEPESA]) INCLUDE ([NR_ORDETRANORDEPESA],[FL_STATORDETRAN],[DT_PLANAPANORDETRAN],[ID_CARGTIPO],[DT_LIBEMTECHANDHELDORDEPESA],[ID_USUASIST_LIBEMTEC],[FL_SINCMTECORDEPESA],[GN_REFEORDEPESA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_178] ON [MIMS].[DBO].[SCT_DIREITOS_US] ([ID_MODULO],[ID_USUARIO],[ID_RECJANE]) INCLUDE ([ID_DIREITOS_US],[ID_JANELA],[ID_RECURSO],[LASTMODDATE],[ROWID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_PRODREGITOTA_CALC] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_TOTAL] ([DT_PADRTOTAREGIPROD],[GN_TAGTOTAREGIPROD_],[ID_ESTRUNIDABAT],[ID_ETIQUETA_],[ID_PRODMATEEMBA],[NR_SEQUTURN],[ID_TOTAREGIPROD]) INCLUDE ([QN_TOTAREGIPROD],[QN_PESOTOTAREGIPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_SYS_C0015373] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_TRANSFER] ([ID_TRANREGIPROD],[FILIAL],[FL_TIPOTRANREGIPROD],[EMPRESA]) INCLUDE ([DT_ABERTRANREGIPROD],[DT_FECHTRANREGIPROD],[FL_STATTRANREGIPROD],[ID_USUASIST_ABERTURA],[ID_USUASIST_FECHAMENTO],[FX_TRANREGIPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_MATERIAL_EMBALAGEM_COMPOSICAO_ID_MATEEMBA_ID_ESTRCOMPMATEEMBA] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_COMPOSICAO] ([ID_ESTRCOMPMATEEMBA],[ID_MATEEMBA],[ID_COMPMATEEMBA]) INCLUDE ([ID_MATERIAL],[QN_COMPMATEEMBA],[FL_COMPENTRTARAPRIMMATEEMBA],[FL_COMPRATEUNIDMATEEMBA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
