

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230809192217 ON [MIMS].[DBO].[PRODUCAO_REGISTRO_ESTOQUE_FECH]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_EMBADEFI] ON [MIMS].[DBO].[EMBALAGEM_DEFINICAO] ([ID_DEFIEMBA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE  INDEX [IDX_FK_ITEM_DESTREGIPROD_ID_DESTREGIPROD] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_DEST_ITEM] ([ID_DESTREGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [_DTA_INDEX_MATERIAL_EMBALAGEM_DEFINICAO_12_416720537__K3_K2_6] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_DEFINICAO] ([ID_DEFIMATEEMBA],[ID_PRODDEFIMATEEMBA]) INCLUDE ([ID_MATERIAL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230809192313 ON [MIMS].[DBO].[PRODUCAO_BATCH_PESAGEM_REPO]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_REGIPRODBATC] ON [MIMS].[DBO].[PRODUCAO_REGISTRO] ([ID_BATCPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_408] ON [MIMS].[DBO].[CLIENTE_FILIAL] ([ID_CLIENTE]) INCLUDE ([ID_FILICLIE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK__INTERFAC__C28E7352542E0D3F] ON [MIMS].[DBO].[INTERFACE_MATERIAL_CONSUMO] ([ID_CONSMATEINTE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_MULTPROGPROD] ON [MIMS].[DBO].[PRODUCAO_PROGRAMACAO_MULTIPLA] ([ID_MULTPROGPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [SYS_C0013374] ON [MIMS].[DBO].[EXPEDICAO_PALETE] ([ID_PALEEXPE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE  INDEX [IDX_PRODBATCMATEPRIM_0008] ON [MIMS].[DBO].[PRODUCAO_BATCH_MATERIA_PRIMA] ([ID_BATCPROD],[ID_MATEEMBAFILI],[ID_PRIMMATEBATCPROD],[ID_PRODMATEEMBA],[QN_PESODOSABATCPROD],[QN_PESOREQUBATCPROD],[QN_QTDEMATEPRIMBATCPROD]) INCLUDE ([ID_MATERIAL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_197] ON [MIMS].[DBO].[PRODUCAO_BATCH_REPOSITORIO] ([EMPRESA],[FILIAL]) INCLUDE ([ID_REPOBATCPROD],[NR_ETIQREPOBATCPROD],[NR_REPOBATCPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PRODUCAO_BATCH_MATE_PRIM_REPO_ID_REPOBATCPROD] ON [MIMS].[DBO].[PRODUCAO_BATCH_MATE_PRIM_REPO] ([ID_REPOBATCPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [SYS_C0012203] ON [MIMS].[DBO].[CAMINHAO_PROGRAMACAO] ([ID_PROGCAMI]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [_DTA_INDEX_MATERIAL_EMBALAGEM_LOCAL_12_688721506__K4_2] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_LOCAL] ([ID_MATEEMBAFILI]) INCLUDE ([FILIAL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [_DTA_INDEX_MATERIAL_EMBALAGEM_FILIAL_12_464720708__K4_K3_2] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([ID_DEFIMATEEMBA],[ID_MATEEMBAFILI]) INCLUDE ([FILIAL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_INDEPALEEXPE_PALEREGIPROD] ON [MIMS].[DBO].[EXPEDICAO_PALETE_IDENTIFICACAO] ([ID_PALEEXPE]) INCLUDE ([ID_REGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_60] ON [MIMS].[DBO].[ENTRADA_AVE_VIVA] ([FL_SINCMIDDDESCENTRAVEVIVA],[IE_LOTEENTRAVEVIVA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_ORDEPESA_ENTRAVEVIVA] ON [MIMS].[DBO].[PESAGEM_ORDEM] ([ID_ENTRAVEVIVA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_178] ON [MIMS].[DBO].[SCT_DIREITOS_US] ([ID_MODULO],[ID_USUARIO]) INCLUDE ([ID_DIREITOS_US],[ID_JANELA],[ID_RECURSO],[LASTMODDATE],[ROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE  INDEX [IDX_PRODREGITOTA_CALC] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_TOTAL] ([DT_PADRTOTAREGIPROD],[GN_TAGTOTAREGIPROD_],[ID_ESTRUNIDABAT],[ID_ETIQUETA_],[ID_PRODMATEEMBA],[NR_SEQUTURN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [SYS_C0015373] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_TRANSFER] ([ID_TRANREGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_MATERIAL_EMBALAGEM_COMPOSICAO_ID_MATEEMBA_ID_ESTRCOMPMATEEMBA] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_COMPOSICAO] ([ID_ESTRCOMPMATEEMBA],[ID_MATEEMBA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;