
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/28/2023 12:40:28 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230828124031 ON [SPRITZERTAIPINGDB].[DBO].[PICK_RESERVATION] ([STATUS],[CLASS_TYPE],[CREATE_DATE],[MATERIAL_STATUS_ID],[ALLOCATION_ZONE_KEY]) INCLUDE ([CREATED_BY],[QUANTITY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[ORDER_LINE_KEY],[BEST_BEFORE_DATE],[EXPIRY_DATE],[LOAD_UNIT_ID],[LOT_CODE],[MANUFACTURING_DATE],[ATTRIBUTE_SET],[PRODUCT_UOM_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230828124046 ON [SPRITZERTAIPINGDB].[DBO].[ASN_LINE] ([CLASS_TYPE],[ASN_LINE_KEY]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[WEIGHT],[X_POSITION],[Y_POSITION],[Z_POSITION],[PRODUCT_UOM_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
