
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/7/2023 12:39:49 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230807123952 ON [SPRITZERTAIPINGDB].[DBO].[OWNER] ([CLASS_TYPE],[CREATE_DATE]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[DESCRIPTION],[OWNER_KEY],[OWNER_ID]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230807124021 ON [SPRITZERTAIPINGDB].[DBO].[AUDIT_TRAIL_PARAM_PROP] ([CLASS_TYPE],[AUDIT_PARAM_PROP_KEY]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[PROP_LABEL],[PROP_TYPE],[PROP_VALUE]) ;
 END TRY BEGIN CATCH END CATCH;
