
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/21/2023 10:14:13 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230821101440 ON [SPRITZERTAIPINGDB].[DBO].[EVENTLOG] ([EVENT_KEY],[SEVERITY],[CLASS_TYPE],[ORIGIN_CATEGORY]) INCLUDE ([OCCURRENCE_DATE],[MESSAGE],[OCCURRENCE_COUNT],[TRANSLATED_MESSAGE]) ;
 END TRY BEGIN CATCH END CATCH;
