
EXEC sp_configure 'show advanced options','1';
RECONFIGURE WITH OVERRIDE;
EXEC sp_configure 'xp_cmdshell','1';
RECONFIGURE WITH OVERRIDE;
EXEC xp_cmdshell 'md "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA"';
EXEC xp_cmdshell 'md "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA"';

CREATE TABLE #results (result nvarchar(max))


BEGIN TRY
	USE master
	IF EXISTS (SELECT * FROM sys.databases WHERE name = 'SPRITZERTAIPINGDB' AND state = 0)
	BEGIN

		IF (SELECT physical_name FROM sys.master_files WHERE database_id = DB_ID(N'SPRITZERTAIPINGDB') AND FILE_ID = 1) = 'D:\MYTPCPSRV01\SSDE_DATA\SPRITZERTAIPINGDB.mdf'
		BEGIN

			ALTER DATABASE [SPRITZERTAIPINGDB] SET OFFLINE WITH ROLLBACK IMMEDIATE;

			IF OBJECT_ID(N'tempdb..#results') IS NOT NULL
			BEGIN
				TRUNCATE TABLE #results
			END
			INSERT INTO #results
			EXEC master..xp_cmdshell 'copy "D:\MYTPCPSRV01\SSDE_DATA\SPRITZERTAIPINGDB.mdf" "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDB.mdf" /Z /Y';
			IF EXISTS(SELECT * FROM #results WHERE result LIKE '%1 file(s) copied.%')
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDB] MODIFY FILE (NAME='SPRITZERTAIPINGDB' , FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDB.mdf');
				ALTER DATABASE [SPRITZERTAIPINGDB] SET ONLINE;
				EXEC master..xp_cmdshell 'del "D:\MYTPCPSRV01\SSDE_DATA\SPRITZERTAIPINGDB.mdf" "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDB.mdf"';
			END
			ELSE
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDB] SET ONLINE;
			END
			TRUNCATE TABLE #results
		END
	END
END TRY
BEGIN CATCH
	IF DB_ID(N'SPRITZERTAIPINGDB') IS NOT NULL
	BEGIN
		ALTER DATABASE [SPRITZERTAIPINGDB] SET ONLINE;
	END
END CATCH

BEGIN TRY
	USE master
	IF EXISTS (SELECT * FROM sys.databases WHERE name = 'SPRITZERTAIPINGDWH' AND state = 0)
	BEGIN

		IF (SELECT physical_name FROM sys.master_files WHERE database_id = DB_ID(N'SPRITZERTAIPINGDWH') AND FILE_ID = 1) = 'D:\MYTPCPSRV01\SSDE_DATA\SPRITZERTAIPINGDWH.mdf'
		BEGIN

			ALTER DATABASE [SPRITZERTAIPINGDWH] SET OFFLINE WITH ROLLBACK IMMEDIATE;

			IF OBJECT_ID(N'tempdb..#results') IS NOT NULL
			BEGIN
				TRUNCATE TABLE #results
			END
			INSERT INTO #results
			EXEC master..xp_cmdshell 'copy "D:\MYTPCPSRV01\SSDE_DATA\SPRITZERTAIPINGDWH.mdf" "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH.mdf" /Z /Y';
			IF EXISTS(SELECT * FROM #results WHERE result LIKE '%1 file(s) copied.%')
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDWH] MODIFY FILE (NAME='SPRITZERTAIPINGDWH' , FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH.mdf');
				ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
				EXEC master..xp_cmdshell 'del "D:\MYTPCPSRV01\SSDE_DATA\SPRITZERTAIPINGDWH.mdf" "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH.mdf"';
			END
			ELSE
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
			END
			TRUNCATE TABLE #results
		END
	END
END TRY
BEGIN CATCH
	IF DB_ID(N'SPRITZERTAIPINGDWH') IS NOT NULL
	BEGIN
		ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
	END
END CATCH

EXEC sp_configure 'xp_cmdshell','0';
RECONFIGURE WITH OVERRIDE;
EXEC sp_configure 'show advanced options','0';
RECONFIGURE WITH OVERRIDE;
