
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/16/2023 9:03:33 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230816090336 ON [SPRITZERTAIPINGDB].[DBO].[PRODUCT] ([CLASS_TYPE],[STATUS],[OWNER_KEY],[CREATE_DATE],[DESCRIPTION],[PRODUCT_ID]) INCLUDE ([CREATED_BY],[STATUS_DATE],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[PRODUCT_KEY],[DEFAULT_UOM_RATIO],[UOM_ID],[LOCAL]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230816090418 ON [SPRITZERTAIPINGDB].[DBO].[WORK_ZONE] ([WORK_ZONE_KEY],[ORGANIZATION_NODE_KEY],[CLASS_TYPE],[STATUS]) ;
 END TRY BEGIN CATCH END CATCH;
