USE [master];
BEGIN TRY
	ALTER LOGIN [marelcons] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [stwmrsys] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [slcons] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [dpa] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [mareladmin] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [marelpdsnt] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [DPPMARELDB\Administrator] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [link_11] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [aaronlim] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [alicemis] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH

BEGIN TRY
	ALTER LOGIN [Ubaidullah] WITH DEFAULT_DATABASE=[master];
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH
