
BEGIN TRY
--CURRENT VALUE: SIMPLE
ALTER DATABASE [IDB_MTECH_MAREL_SL] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[IDB_MTECH_MAREL_SL] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [IDB_MTECH_MAREL_SL] SET TARGET_RECOVERY_TIME = 61 SECONDS;
PRINT '[IDB_MTECH_MAREL_SL] TARGET_RECOVERY_TIME is set 61.';
END TRY 
BEGIN CATCH
	PRINT 'Database [IDB_MTECH_MAREL_SL] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [PDSNT] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[PDSNT] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [PDSNT] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[PDSNT] PARAMETERIZATION is FORCED.';
END TRY 
BEGIN CATCH
	PRINT 'Database [PDSNT] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [innova] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[innova] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [innova] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[innova] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: ON
USE [innova];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[innova] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [innova];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[innova] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [innova] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: SIMPLE
ALTER DATABASE [innovaObsolete] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[innovaObsolete] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: ON
USE [innovaObsolete];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[innovaObsolete] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [innovaObsolete];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[innovaObsolete] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [innovaObsolete] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;