
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/7/2023 12:42:01 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230807124204 ON [SPRITZERTAIPINGDB].[DBO].[ORDER_TU_PLAN] ([CLASS_TYPE],[STATUS],[CREATE_DATE]) INCLUDE ([CREATED_BY],[STATUS_DATE],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[HEIGHT],[WEIGHT],[ORDER_TU_PLAN_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230807124222 ON [SPRITZERTAIPINGDB].[DBO].[STORAGE_ZONE_PRIORITY] ([CLASS_TYPE],[STORAGE_CLUSTER_KEY],[STORAGE_ZONE_PRIORITY_KEY]) INCLUDE ([STORAGE_ZONE_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
