

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230822103405 ON [MIMS].[DBO].[LINHA_PROCESSAMENTO]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_REPOREGIPROD] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_REPOSITORIO] ([ID_REPOREGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [SYS_C0014607] ON [MIMS].[DBO].[PEDIDO_VENDA] ([ID_PEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_648] ON [MIMS].[DBO].[EXPEDICAO_CARGA_IDENTIFICACAO] ([ID_CARGEXPE]) INCLUDE ([ID_REGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_CARGEXPE_AGRUCARGEXPE] ON [MIMS].[DBO].[EXPEDICAO_CARGA] ([ID_CARGEXPE_AGRU]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_1] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([FL_ATIVMATEEMBAFILI]) INCLUDE ([EMPRESA],[FILIAL],[FL_CONTTUNEMATEEMBAFILI],[FL_DESTPROCPRODMATEEMBAFILI],[FL_EXIGTARAPRODMATEEMBAFILI],[FL_IDENPRODMATEEMBAFILI],[FL_MODAIDENMATEEMBAFILI],[FL_OBRIPALEPESAGRUMATEEMBAFILI],[FL_PESAESTAMATEEMBAFILI],[FL_PRODMATEEMBAFILI],[FL_SEPAPRODMATEEMBAFILI],[FL_SIMUPRODMATEEMBAFILI],[FL_TRATLIMIPESOMATEEMBAFILI],[ID_DEFIMATEEMBA],[ID_ESTRMATEEMBAFILI],[ID_MATEEMBAFILI],[ID_MODEETIQIMPRMATEEMBAFILI],[ID_MODELOTERASTFILISIST],[ID_PROCLINH],[ID_PROCLINH_DESTPROC],[NR_REGIMINIAGRIMATEEMBAFILI],[PC_TOLEMAXIMATEEMBAFILI],[PC_TOLEMINIMATEEMBAFILI],[QN_ANIMEMBAMATEEMBAFILI],[QN_FORMPALEMATEEMBAFILI],[QN_PECAPRODMATEEMBAFILI],[QN_PRODEMBAMATEEMBAFILI]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_FK_ADICMATEBATCPROD_MATEPRIM_ID_MATEEMBA_MATEPRIM] ON [MIMS].[DBO].[PRODUCAO_BATCH_MATERIAL_ADICIO] ([ID_MATEEMBA_MATEPRIM]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_FK_INTEPRODBATCSAP_PRODBATC_NR_BATCPROD] ON [MIMS].[DBO].[INTERFACE_MATERIAL_CONSUMO] ([NR_BATCPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_MOVIREGIPROD_OPER] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_MOVIMENTACAO] ([FL_OPERMOVIREGIPROD],[ID_REGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230822103432 ON [MIMS].[DBO].[EXPEDICAO_CARGA_LOG]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [NR_IDENPALEEXPE] ON [MIMS].[DBO].[EXPEDICAO_PALETE] ([NR_IDENPALEEXPE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_1527] ON [MIMS].[DBO].[ENTRADA_AVE_VIVA] ([FL_STATENTRAVEVIVA],[ID_REGIDATAPADR],[ID_VEICTRAN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_178] ON [MIMS].[DBO].[SCT_DIREITOS_US] ([ID_MODULO],[ID_USUARIO]) INCLUDE ([ID_DIREITOS_US],[ID_JANELA],[ID_RECURSO],[LASTMODDATE],[ROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE  INDEX [_DTA_INDEX_MATERIAL_EMBALAGEM_LOCAL_12_688721506__K4_2] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_LOCAL] ([ID_MATEEMBAFILI]) INCLUDE ([FILIAL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_MATERIAL_EMBALAGEM_COMPOSICAO_ID_MATEEMBA_ID_ESTRCOMPMATEEMBA] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_COMPOSICAO] ([ID_ESTRCOMPMATEEMBA],[ID_MATEEMBA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND]) INCLUDE ([LASTMODDATE],[QN_EMBAEXPEITEMPEDIVEND],[QN_UNIDINDIEXPEITEMPEDIVEND],[ROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PRODUCAO_REGISTRO_TR_ITEM_ID_IDENREGIPROD] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_TR_ITEM] ([ID_IDENREGIPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_EMBADEFI] ON [MIMS].[DBO].[EMBALAGEM_DEFINICAO] ([ID_DEFIEMBA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_45747] ON [MIMS].[DBO].[DATA_PADRAO_REGISTRO] ([DT_REGIDATAPADR]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;