
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/22/2023 10:33:44 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230822103405 ON [MIMS].[DBO].[LINHA_PROCESSAMENTO] ([NM_PROCLINH],[ID_ALMOXARIFADO],[ID_PROCLINH],[FL_TIPOPROCLINH],[FL_PERMPROCLINHINTEPROCLINH]) INCLUDE ([IE_PROCLINH]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_REPOREGIPROD] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_REPOSITORIO] ([ID_REPOREGIPROD],[ID_REGIPROD],[FL_STATREGIPROD],[ID_PRODMATEEMBA],[FL_REGITRANREGIPROD],[FL_ORIGREGIPROD]) INCLUDE ([ID_IDENREGIPROD],[ID_MATERIAL],[ID_EMBALAGEM],[ID_ALMOXARIFADO],[ID_MATEALMO],[DT_REGIPROD],[ID_BALANCA],[QN_PESOPADRREGIPROD],[QN_PESOLIQUREGIPROD],[QN_TARAEMBAREGIPROD],[DT_ENTRTUNEREGIPROD],[DT_SAIDTUNEREGIPROD],[ID_TUNEPROD],[ID_PALEEXPE],[QN_TARACOMPREGIPROD],[ID_USUASIST_REGIPROD],[FL_SIMUREGIPROD],[FL_PRODPROPREGIPROD],[ID_ESTRUNIDABAT],[ID_ENTRAVEVIVA],[QN_PESOORIGREGIPROD],[NR_LOTERASTREGIPROD],[FL_MODAREGIPROD],[DT_REFEREGIPROD],[FL_SEQUREGIPROD],[DT_VALIREGIPROD],[ID_BATCPROD],[ID_IDENORIGDESMREGIPROD],[DT_ELABREGIPROD],[QN_PRODEMBAREGIPROD],[QN_CAIXREGIPROD],[ID_INVEPROD],[NR_SEQUTURNREGIPROD],[QN_PESOQUEBREGIPROD],[FILIAL_IMPRESSA],[EMPRESA_IMPRESSA],[ID_PROCTERMPRODADICMATECONS],[QN_TARAPRIMREGIPROD],[FL_TIPOUNIDREGIPROD],[ID_CENTCUST],[FL_SOBRREGIPROD],[ID_ALMOXARIFADO_PRODUCAO],[ID_ITEMDESTREGIPROD_AUTO],[ID_FORNECEDOR],[QN_ANIMEMBAREGIPROD],[GN_TAGREGIPROD],[ID_USUASIST_ENTRTUNEREGIPROD],[ID_USUASIST_SAIDTUNEREGIPROD],[NR_LOTERASTEXTEREGIPROD],[FL_PROCORIGREGIPROD],[DT_PADRREGIPROD],[DT_BALAREGIPROD],[FL_SITUREGIPROD],[ID_PACKPROD],[DT_EXCLREGIPROD],[ID_TRANREGIPROD],[ID_PEDIVEND],[FL_DISPREGIPROD],[ID_ETIQUETA],[ID_MULTPROGPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_SYS_C0014607] ON [MIMS].[DBO].[PEDIDO_VENDA] ([ID_PEDIVEND],[IE_PEDIVEND],[QN_UNIDINDIEXPEPEDIVEND]) INCLUDE ([EMPRESA],[FILIAL],[ID_CLIENTE],[DT_PEDIVEND],[DT_ENTRPEDIVEND],[DT_DIGIPEDIVEND],[ID_TIPOPEDIVEND],[ID_CARGEXPE],[FL_STATPEDIVEND],[FL_TRANJDEPEDIVEND],[IE_FILISIST_IMPRROMAINVO],[QN_EMBAPEDIVEND],[QN_PESOPEDIVEND],[QN_TARAPEDIVEND],[QN_PESOBRUTPEDIVEND],[VL_INVOPEDIVEND],[VL_TOTAIMPOINVOPEDIVEND],[QN_UNIDINDIPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_648] ON [MIMS].[DBO].[EXPEDICAO_CARGA_IDENTIFICACAO] ([ID_CARGEXPE],[ID_IDENCARGEXPE]) INCLUDE ([ID_REGIPROD],[FL_TIPOUNIDIDENCARGEXPE],[EMPRESA],[FILIAL],[QN_PESOIDENCARGEXPE],[QN_TARAIDENCARGEXPE],[DT_CARRIDENCARGEXPE],[ID_PEDIVEND],[FL_MODAREGIIDENCARGEXPE],[FL_IMPRETIQIDENCARGEXPE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_CARGEXPE_AGRUCARGEXPE] ON [MIMS].[DBO].[EXPEDICAO_CARGA] ([ID_CARGEXPE_AGRU]) INCLUDE ([FL_MODACARGEXPE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_1] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([FL_ATIVMATEEMBAFILI]) INCLUDE ([EMPRESA],[FILIAL],[FL_CONTTUNEMATEEMBAFILI],[FL_DESTPROCPRODMATEEMBAFILI],[FL_EXIGTARAPRODMATEEMBAFILI],[FL_IDENPRODMATEEMBAFILI],[FL_MODAIDENMATEEMBAFILI],[FL_OBRIPALEPESAGRUMATEEMBAFILI],[FL_PESAESTAMATEEMBAFILI],[FL_PRODMATEEMBAFILI],[FL_SEPAPRODMATEEMBAFILI],[FL_SIMUPRODMATEEMBAFILI],[FL_TRATLIMIPESOMATEEMBAFILI],[ID_DEFIMATEEMBA],[ID_ESTRMATEEMBAFILI],[ID_MATEEMBAFILI],[ID_MODEETIQIMPRMATEEMBAFILI],[ID_MODELOTERASTFILISIST],[ID_PROCLINH],[ID_PROCLINH_DESTPROC],[NR_REGIMINIAGRIMATEEMBAFILI],[PC_TOLEMAXIMATEEMBAFILI],[PC_TOLEMINIMATEEMBAFILI],[QN_ANIMEMBAMATEEMBAFILI],[QN_FORMPALEMATEEMBAFILI],[QN_PECAPRODMATEEMBAFILI],[QN_PRODEMBAMATEEMBAFILI],[FL_QTDEINDIMATEEMBAFILI],[FL_TIPOEXPEMATEEMBAFILI],[QN_ETIQEXPEMATEEMBAFILI],[FL_REPEMATEEMBAFILI],[PC_TOLEPESOPESAGRUMATEEMBAFILI]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_FK_ADICMATEBATCPROD_MATEPRIM_ID_MATEEMBA_MATEPRIM] ON [MIMS].[DBO].[PRODUCAO_BATCH_MATERIAL_ADICIO] ([ID_MATEEMBA_MATEPRIM],[ID_ADICMATEBATCPROD]) INCLUDE ([ID_MATERIAL],[QN_PADRADICMATEBATCPROD],[QN_CONSADICMATEBATCPROD],[NR_LOTEADICMATEBATCPROD],[QN_SEPAADICMATEBATCPROD],[ID_PROGPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_FK_INTEPRODBATCSAP_PRODBATC_NR_BATCPROD] ON [MIMS].[DBO].[INTERFACE_MATERIAL_CONSUMO] ([NR_BATCPROD],[ID_CONSMATEINTE]) INCLUDE ([IE_MATERIAL],[QN_CONSMATEINTE],[FL_OPERCONSMATEINTE],[ID_PRODTERMMATEEMBA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_MOVIREGIPROD_OPER] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_MOVIMENTACAO] ([FL_OPERMOVIREGIPROD],[ID_REGIPROD],[ID_MOVIREGIPROD]) INCLUDE ([ID_USUASIST]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230822103432 ON [MIMS].[DBO].[EXPEDICAO_CARGA_LOG] ([ID_LOGCARGEXPE],[DT_ABERREALLOGCARGEXPE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_NR_IDENPALEEXPE] ON [MIMS].[DBO].[EXPEDICAO_PALETE] ([NR_IDENPALEEXPE],[ID_PALEEXPE]) INCLUDE ([QN_EMBAPALEEXPE],[DT_PADRPALEEXPE],[FL_STATPALEEXPE],[ID_MATEEMBA],[FL_AUTOPALEEXPE],[ID_PEDIVEND],[QN_UNIDINDIPALEEXPE],[ID_ALMOTRANSINTEPALEEXPE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_1527] ON [MIMS].[DBO].[ENTRADA_AVE_VIVA] ([FL_STATENTRAVEVIVA],[ID_REGIDATAPADR],[ID_VEICTRAN],[ID_ENTRAVEVIVA]) INCLUDE ([NR_MARTENTRAVEVIVA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_178] ON [MIMS].[DBO].[SCT_DIREITOS_US] ([ID_MODULO],[ID_USUARIO],[ID_RECJANE]) INCLUDE ([ID_DIREITOS_US],[ID_JANELA],[ID_RECURSO],[LASTMODDATE],[ROWID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA__DTA_INDEX_MATERIAL_EMBALAGEM_LOCAL_12_688721506__K4_2] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_LOCAL] ([ID_MATEEMBAFILI],[ID_MATEEMBALOCA]) INCLUDE ([FILIAL],[QN_PRODEMBAATUAMATEEMBALOCA],[QN_TARACOMPMATEEMBALOCA],[QN_ANIMEMBAATUAMATEEMBALOCA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_MATERIAL_EMBALAGEM_COMPOSICAO_ID_MATEEMBA_ID_ESTRCOMPMATEEMBA] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_COMPOSICAO] ([ID_ESTRCOMPMATEEMBA],[ID_MATEEMBA],[ID_COMPMATEEMBA]) INCLUDE ([ID_MATERIAL],[QN_COMPMATEEMBA],[FL_COMPENTRTARAPRIMMATEEMBA],[FL_COMPRATEUNIDMATEEMBA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND],[ID_ITEMPEDIVEND],[FL_TIPOEXPEITEMPEDIVEND]) INCLUDE ([LASTMODDATE],[QN_EMBAEXPEITEMPEDIVEND],[QN_UNIDINDIEXPEITEMPEDIVEND],[ROWID],[QN_PESOMINIITEMPEDIVEND],[QN_PESOMAXIITEMPEDIVEND],[FL_RESTVALIITEMPEDIVEND],[DT_LIMIVALIMINIITEMPEDIVEND],[DT_LIMIVALIMAXIITEMPEDIVEND],[QN_EMBAEMPEITEMPEDIVEND],[QN_PESOPADREXPEITEMPEDIVEND],[QN_TARAREALEXPEITEMPEDIVEND],[QN_PESOREALEXPEITEMPEDIVEND],[ID_MATEALMO],[QN_EXPEITEMPEDIVEND],[QN_UNIDINDIITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PRODUCAO_REGISTRO_TR_ITEM_ID_IDENREGIPROD] ON [MIMS].[DBO].[PRODUCAO_REGISTRO_TR_ITEM] ([ID_IDENREGIPROD],[ID_ITEMTRANREGIPROD]) INCLUDE ([ID_TRANREGIPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_EMBADEFI] ON [MIMS].[DBO].[EMBALAGEM_DEFINICAO] ([ID_DEFIEMBA],[ID_MATEALMO],[ID_EMBALAGEM],[ID_ALMOXARIFADO]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_45747] ON [MIMS].[DBO].[DATA_PADRAO_REGISTRO] ([DT_REGIDATAPADR],[ID_REGIDATAPADR]) INCLUDE ([EMPRESA],[FILIAL]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
