



BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230518061630 ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPERMISSIONSMEMBERGROUPS]; 
END TRY 
BEGIN CATCH 
END CATCH;




BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROTEINCOUNTERS_COUNTERMODE_COUNTERTYPE_PROTEINCOSTCENTERSIRN_PROTEINVENDORSIRN_PROTEINDIVISIONSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINCOUNTERS] ([COUNTERMODE],[COUNTERTYPE],[PROTEINCOSTCENTERSIRN],[PROTEINDIVISIONSIRN],[PROTEINVENDORSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROTEINPRODUCTCATEGORIES] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTCATEGORIES] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;