
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/18/2023 6:16:27 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230518061630 ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPERMISSIONSMEMBERGROUPS] ([IRN],[PROTEINPERMISSIONSUSERSIRN]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROTEINCOUNTERS_COUNTERMODE_COUNTERTYPE_PROTEINCOSTCENTERSIRN_PROTEINVENDORSIRN_PROTEINDIVISIONSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINCOUNTERS] ([COUNTERMODE],[COUNTERTYPE],[PROTEINCOSTCENTERSIRN],[PROTEINDIVISIONSIRN],[PROTEINVENDORSIRN],[LASTMODDATE]) INCLUDE ([CREATIONDATE],[REPLICATIONDATETIME],[REPLICASOURCEID],[CURRENTCOUNTERNO],[EXTERNALID],[CREATIONUSERID],[USERID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROTEINPRODUCTCATEGORIES] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTCATEGORIES] ([IRN]) INCLUDE ([PROTEINPRODUCTS],[PROTEINPRODUCTSUOM]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
