
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/22/2023 10:47:06 AM UTC
*/
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_F4211_PK] ON [JDE_PRODUCTION].[PRODDTA].[F4211] ([SDDCTO],[SDDOCO],[SDKCOO],[SDLNID],[SDLNTY],[SDLTTR]) INCLUDE ([SDMCU],[SDAN8],[SDSHAN],[SDDRQJ],[SDTRDJ],[SDIVD],[SDITM],[SDLITM],[SDDELN],[SDCARS],[SDUOM1],[SDPQOR],[SDUOM2],[SDSQOR],[SDITWT],[SDWTUM],[SDAITM],[SDUOM],[SDUORG],[SDSOQS],[SDAEXP],[SDCRCD],[SDUPMJ],[SDCO],[SDADDJ]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_F0005_2] ON [JDE_PRODUCTION].[PRODCTL].[F0005] ([DRDL02],[DRKY],[DRRT],[DRSY]) INCLUDE ([DRDL01]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_F4102_PK] ON [JDE_PRODUCTION].[PRODDTA].[F4102] ([IBITM],[IBMCU],[IBSTKT]) INCLUDE ([IBLITM],[IBAITM],[IBSRP1],[IBSRP2],[IBSRP3],[IBPRGR]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_F4101_2] ON [JDE_PRODUCTION].[PRODDTA].[F4101] ([IMLITM],[IMITM]) INCLUDE ([IMUOM1],[IMDSC1]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_F9861W_5] ON [JDE920].[OL920].[F9861W] ([SIOID],[SIPATHCD],[SIWOSTATUS],[SIWOUSER],[SIWOBNM]) INCLUDE ([SIUSER],[SIDM],[SIJDEVERS],[SIMSAR],[SISTCE],[SIMRGMOD],[SIMRGOPT],[SIMODCMT],[SIPID],[SIMKEY],[SIWOUTIME],[SIWOFU1],[SIWOFU2],[SIWOFU3],[SIWOFU4],[SIWOFU5],[SIWOFU6],[SIWOFU7],[SIWOFU8],[SIWOFU9],[SIWOFU10],[SIOMWACTFLG]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_F9563110_PK] ON [JDE920].[SY920].[F9563110] ([RJRPDOUGUD],[RJRPDFUSN1],[RJRPDFUSN2]) INCLUDE ([RJRPDUOGUD],[RJRPDJBNBR],[RJRPDNM],[RJEXEHOST],[RJJOBNBR],[RJRPDSRCTP],[RJRPDSRC],[RJRPDSRCV],[RJRPDSRCFM],[RJRPDSRCSF],[RJRPDSRCFU],[RJRPDSBTUT],[RJRPDORGHT],[RJRPDFUSS1],[RJRPDFUSS2],[RJRPDFUSS3],[RJRPDFUSS8],[RJRPDFUSS9],[RJRPDFUSC1],[RJRPDFUSC2],[RJRPDFUSC3],[RJRPDFUSM1],[RJRPDFUSM2],[RJRPDFUSU1],[RJRPDFUSU2],[RJRPDFUSU3],[RJMKEY],[RJUSER],[RJUTIME]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
