


BEGIN TRY 
    CREATE UNIQUE INDEX [F4211_PK] ON [JDE_PRODUCTION].[PRODDTA].[F4211] ([SDDCTO],[SDDOCO],[SDKCOO],[SDLNID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;




BEGIN TRY 
    CREATE UNIQUE INDEX [F0005_2] ON [JDE_PRODUCTION].[PRODCTL].[F0005] ([DRDL02],[DRKY],[DRRT],[DRSY]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [F4102_PK] ON [JDE_PRODUCTION].[PRODDTA].[F4102] ([IBITM],[IBMCU]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;





BEGIN TRY 
    CREATE UNIQUE INDEX [F4101_2] ON [JDE_PRODUCTION].[PRODDTA].[F4101] ([IMLITM]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;





BEGIN TRY 
    CREATE  INDEX [F9861W_5] ON [JDE920].[OL920].[F9861W] ([SIOID],[SIPATHCD],[SIWOSTATUS],[SIWOUSER]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F9563110_PK] ON [JDE920].[SY920].[F9563110] ([RJRPDOUGUD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;