
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/17/2023 9:13:06 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230817091325 ON [CHUANSINCACTUS].[DBO].[TRANSACTIONCODES] ([ID],[ISDEFAULT],[TABLEID]) INCLUDE ([FORMAT],[SUFFIXFILLCHAR],[NEXTNUMBER],[DATETYPE],[RESETMONTHLY],[USEPROJECTCODE],[USECOUNTERCODE],[OPTIMISTICLOCKFIELD]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_DEBTORS] ON [CHUANSINCACTUS].[DBO].[DEBTORS] ([ID],[ROWINDEX]) INCLUDE ([GLACCOUNT],[RECEIPT]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230817091328 ON [CHUANSINCACTUS].[DBO].[STOCKSALESPRICEHISTORY] ([OID],[STOCK]) INCLUDE ([OPTIMISTICLOCKFIELD],[PRICETYPE],[DOCDATE],[PRICE],[DISCOUNT]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_JOURNALS] ON [CHUANSINCACTUS].[DBO].[JOURNALS] ([ROWINDEX],[ISCANCELLED],[JOURNALDATE],[ISUNPAIDPURCHASE]) INCLUDE ([JOURNALCODE],[CURRENCYID],[CURRENCYRATE],[DESCRIPTION],[NOTES]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_JOURNALDETAILS] ON [CHUANSINCACTUS].[DBO].[JOURNALDETAILS] ([ROWINDEX],[JOURNALID],[GLACCOUNTID]) INCLUDE ([NETDEBITLOCAL],[NETCREDITLOCAL],[PROJECTID],[COSTCENTREID],[REFERENCENO],[DESCRIPTION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_GLACCOUNTS] ON [CHUANSINCACTUS].[DBO].[GLACCOUNTS] ([ID],[ROWINDEX],[GLACCOUNTCODE]) INCLUDE ([DESCRIPTION],[ACCOUNT],[SPECIALACCOUNT],[DRCR],[CURRENCY],[NOTES],[BANKACCOUNTNO],[GSTMSICCODE],[SAC],[TARIFFCODE],[DESCRIPTION2],[PARENT],[ISCREDITCARD],[ISACTIVE],[ISREVALUATION],[ISSUBACCOUNT],[OPTIMISTICLOCKFIELD],[HASCHILDINCOA],[INCLUDEINCASHFLOWFORECASTADVISOR],[SSTTARIFFCODE],[ATCCODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PURCHASERETURNDETAILS] ON [CHUANSINCACTUS].[DBO].[PURCHASERETURNDETAILS] ([ID],[LOCALONECENTSDIFF]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IPAYFORID_ARMATCHED] ON [CHUANSINCACTUS].[DBO].[ARMATCHED] ([PAYFORID]) INCLUDE ([CREDITLIMIT]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_STOCKS] ON [CHUANSINCACTUS].[DBO].[STOCKS] ([ROWINDEX],[STOCKCONTROL],[ITEMTYPECODE],[ISACTIVE]) INCLUDE ([ID],[STOCKCODE],[STOCKNAME],[CATEGORYID],[CLASSID],[GROUPID],[BARCODE],[OBJECTTYPE],[DESCRIPTION],[LISTPRICE],[MINPRICE],[SALESDISCOUNT],[PURCHASEDISCOUNT],[WEIGHT],[WEIGHTUOM],[VOLUMN],[VOLUMNUOM],[DEFAULTLOCATIONID],[CURRENTBALANCE],[ISBUNDLED],[CREATEDATE],[DEFAULTINPUTTAXCODEID],[DEFAULTOUTPUTTAXCODEID],[USESERIALNO],[SERIALNOPREFIX],[SERIALNOSUFFIX],[OPTIMISTICLOCKFIELD],[REMARK1],[REMARK2],[REMARK3],[REMARK4],[REMARK5],[HSN],[USEBATCHNO],[USEDEFAULTUNSALABLEPERIOD],[UNSALABLEPERIOD],[COMMISSIONGROUPID],[ALLOWNEGATIVESTOCK],[TARIFFCODEID],[DISCOUNTAPPLYTOQTY],[FLOORPRICE],[DISPLAYINMODULES],[POINTMGTQTY],[POINTMGTPOINTSPERQTY],[BASEUOM2],[BASEUOM2RATE],[BASEUOM3],[BASEUOM3RATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PAYMENTS] ON [CHUANSINCACTUS].[DBO].[PAYMENTS] ([ID],[ROWINDEX]) INCLUDE ([POS],[GLACCOUNT],[DESCRIPTION],[PROJECT],[DEPARTMENT],[REFERENCENO],[AMOUNT],[WTAXAMOUNT],[COSTCENTRE],[AMOUNTLOCAL],[NOTE],[ITEMTYPECODE],[TAXCODE],[ISTAXINCLUSIVE],[TAXRATE],[TAXCLASS],[TAXCLASSVALUE],[TAXAMOUNT],[TAXAMOUNTLOCAL],[NETAMOUNT],[NETAMOUNTLOCAL],[SUBAMOUNT],[SUBAMOUNTLOCAL],[TAXEXCLUSIVEAMOUNT],[TAXEXCLUSIVEAMOUNTLOCAL],[TAXCLASSVALUEREF],[OPTIMISTICLOCKFIELD],[WTAXCODE],[WTAXRATE],[WTAXAMOUNTLOCAL],[PAYMENTRECEIPTINFO],[GLBIRCLSINFO],[K1GOODSREMOVED],[TARIFFCODE],[FROMRELIEFIMPORTATION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
