
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [CHUANSINCACTUS] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[CHUANSINCACTUS] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [CHUANSINCACTUS] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[CHUANSINCACTUS] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [CHUANSINCACTUS] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[CHUANSINCACTUS] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [CHUANSINCACTUS] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;