
BEGIN TRY
ALTER DATABASE [CHUANSINCACTUS] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[CHUANSINCACTUS] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [CHUANSINCACTUS] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[CHUANSINCACTUS] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [CHUANSINCACTUS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[CHUANSINCACTUS] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [CHUANSINCACTUS] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;