
DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC FREESESSIONCACHE;
DBCC FREESYSTEMCACHE ( 'ALL');
USE [tempdb];
DBCC SHRINKFILE (N'tempdev', EMPTYFILE);
ALTER DATABASE [tempdb] REMOVE FILE [tempdev];

			ALTER DATABASE tempdb MODIFY FILE (NAME=N'templog', SIZE=1048576KB , FILEGROWTH=1048576KB)
			