
USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230809 ON [MIMS].[dbo].[ENTRADA_AVE_VIVA];
		PRINT N'INDEX IX_AIDBA_1_20230809 ON [MIMS].[dbo].[ENTRADA_AVE_VIVA] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230809 ON [MIMS].[dbo].[ENTRADA_AVE_VIVA] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH-EDATA];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230809 ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans];
		PRINT N'INDEX IX_AIDBA_2_20230809 ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230809 ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230809 ON [MIMS].[dbo].[CLIENTE_FILIAL];
		PRINT N'INDEX IX_AIDBA_3_20230809 ON [MIMS].[dbo].[CLIENTE_FILIAL] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230809 ON [MIMS].[dbo].[CLIENTE_FILIAL] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230809 ON [MIMS].[dbo].[PEDIDO_VENDA];
		PRINT N'INDEX IX_AIDBA_4_20230809 ON [MIMS].[dbo].[PEDIDO_VENDA] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230809 ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230809 ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE];
		PRINT N'INDEX IX_AIDBA_5_20230809 ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230809 ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE DROPPED.';
END CATCH;

USE [INTERM];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_6_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_6_20230809 ON [INTERM].[dbo].[INTERFACE_PEDIDO_VENDA];
		PRINT N'INDEX IX_AIDBA_6_20230809 ON [INTERM].[dbo].[INTERFACE_PEDIDO_VENDA] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_6_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_6_20230809 ON [INTERM].[dbo].[INTERFACE_PEDIDO_VENDA] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_7_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_7_20230809 ON [MIMS].[dbo].[MATERIAL_ALMOXARIFADO];
		PRINT N'INDEX IX_AIDBA_7_20230809 ON [MIMS].[dbo].[MATERIAL_ALMOXARIFADO] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_7_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_7_20230809 ON [MIMS].[dbo].[MATERIAL_ALMOXARIFADO] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_8_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_8_20230809 ON [MIMS].[dbo].[SISTEMA_LOG_ITEM];
		PRINT N'INDEX IX_AIDBA_8_20230809 ON [MIMS].[dbo].[SISTEMA_LOG_ITEM] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_8_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_8_20230809 ON [MIMS].[dbo].[SISTEMA_LOG_ITEM] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_9_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_9_20230809 ON [MIMS].[dbo].[CRIACAO_LOTE_INTEGRACAO_GALPAO];
		PRINT N'INDEX IX_AIDBA_9_20230809 ON [MIMS].[dbo].[CRIACAO_LOTE_INTEGRACAO_GALPAO] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_9_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_9_20230809 ON [MIMS].[dbo].[CRIACAO_LOTE_INTEGRACAO_GALPAO] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_10_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_10_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_US];
		PRINT N'INDEX IX_AIDBA_10_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_US] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_10_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_10_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_US] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_11_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_11_20230809 ON [MIMS].[dbo].[CRIACAO_LOTE_INTEGRACAO];
		PRINT N'INDEX IX_AIDBA_11_20230809 ON [MIMS].[dbo].[CRIACAO_LOTE_INTEGRACAO] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_11_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_11_20230809 ON [MIMS].[dbo].[CRIACAO_LOTE_INTEGRACAO] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_12_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_12_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_GR];
		PRINT N'INDEX IX_AIDBA_12_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_GR] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_12_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_12_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_GR] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_13_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_13_20230809 ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM];
		PRINT N'INDEX IX_AIDBA_13_20230809 ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_13_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_13_20230809 ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] CANNOT BE DROPPED.';
END CATCH;

USE [MIMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_14_20230809')
	BEGIN
		DROP INDEX IX_AIDBA_14_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_GR_JANE];
		PRINT N'INDEX IX_AIDBA_14_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_GR_JANE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_14_20230809 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_14_20230809 ON [MIMS].[dbo].[SCT_DIREITOS_GR_JANE] CANNOT BE DROPPED.';
END CATCH;
