ALTER INDEX [IX_SISTEMA_REPLICACAO_MERGE_LOG_ROWID] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_MERGE_LOG] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [Hitachi_45384_45383] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [Hitachi_45389_45388] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [Hitachi_45846_45845] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [IDX_N00623] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [IDX_N00635] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [IX_PEDIDO_VENDA_FILIAL] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						ALTER INDEX [IX_PEDIDO_VENDA_ID_PEDIVEND_DESM] ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (DATA_COMPRESSION=PAGE);
						