
BEGIN TRY
	ALTER INDEX [Hitachi_62_61]
	ON [MIMS].[dbo].[PEDIDO_DEVO_VEND_ITEM_DETA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_62_61] ON [MIMS].[dbo].[PEDIDO_DEVO_VEND_ITEM_DETA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_62_61] ON [MIMS].[dbo].[PEDIDO_DEVO_VEND_ITEM_DETA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_45412_45411]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_45412_45411] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_45412_45411] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00628]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00623]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00623] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00623] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_LASTMODDATE_TABEEXCLREPLSIST]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_LASTMODDATE_TABEEXCLREPLSIST] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_LASTMODDATE_TABEEXCLREPLSIST] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IX_Hitachi_183_182_PmtsCondemnTrans]
	ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IX_Hitachi_183_182_PmtsCondemnTrans] ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_Hitachi_183_182_PmtsCondemnTrans] ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [nc2MSmerge_sessions]
	ON [distribution].[dbo].[MSmerge_sessions] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [nc2MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [nc2MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [nc4MSmerge_sessions]
	ON [distribution].[dbo].[MSmerge_sessions] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [nc4MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [nc4MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N1046]
	ON [MIMS].[dbo].[EXPEDICAO_CARGA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N1046] ON [MIMS].[dbo].[EXPEDICAO_CARGA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N1046] ON [MIMS].[dbo].[EXPEDICAO_CARGA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [nc1MSmerge_articlehistory]
	ON [distribution].[dbo].[MSmerge_articlehistory] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [nc1MSmerge_articlehistory] ON [distribution].[dbo].[MSmerge_articlehistory] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [nc1MSmerge_articlehistory] ON [distribution].[dbo].[MSmerge_articlehistory] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_ORDEPESA_INTE]
	ON [MIMS].[dbo].[PESAGEM_ORDEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_ORDEPESA_INTE] ON [MIMS].[dbo].[PESAGEM_ORDEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_ORDEPESA_INTE] ON [MIMS].[dbo].[PESAGEM_ORDEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_PROD_BALA]
	ON [MIMS].[dbo].[PRODUCAO_BALANCA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_PROD_BALA] ON [MIMS].[dbo].[PRODUCAO_BALANCA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PROD_BALA] ON [MIMS].[dbo].[PRODUCAO_BALANCA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00914]
	ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00914] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00914] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [UNQ_SCT_DIREITOS_US_JANE_ROWID]
	ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [UNQ_SCT_DIREITOS_US_JANE_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_SCT_DIREITOS_US_JANE_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [UNQ_DIREITOS_US_ROWID]
	ON [MIMS].[dbo].[SCT_DIREITOS_US] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [UNQ_DIREITOS_US_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_DIREITOS_US_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00913]
	ON [MIMS].[dbo].[SCT_DIREITOS_US] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00913] ON [MIMS].[dbo].[SCT_DIREITOS_US] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00913] ON [MIMS].[dbo].[SCT_DIREITOS_US] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL]
	ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL] ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL] ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [UNQ_PRODBALAPROD_ROWID]
	ON [MIMS].[dbo].[PRODUCAO_BALANCA_PRODUTO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [UNQ_PRODBALAPROD_ROWID] ON [MIMS].[dbo].[PRODUCAO_BALANCA_PRODUTO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_PRODBALAPROD_ROWID] ON [MIMS].[dbo].[PRODUCAO_BALANCA_PRODUTO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [UNQ_ENDEPESS_ROWID]
	ON [MIMS].[dbo].[PESSOA_ENDERECO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [UNQ_ENDEPESS_ROWID] ON [MIMS].[dbo].[PESSOA_ENDERECO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_ENDEPESS_ROWID] ON [MIMS].[dbo].[PESSOA_ENDERECO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IX_MATERIAL_EMBALAGEM_FILIAL_FILIAL]
	ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_FILIAL] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IX_MATERIAL_EMBALAGEM_FILIAL_FILIAL] ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_FILIAL] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_MATERIAL_EMBALAGEM_FILIAL_FILIAL] ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_FILIAL] CANNOT BE ENABLED.';
END CATCH;
