
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 7/13/2023 7:29:44 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230713072947 ON [SPRITZERTAIPINGDB].[DBO].[EVENTLOG] ([CLASS_TYPE],[EVENT_KEY],[SEVERITY],[ORIGIN_CATEGORY]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[OCCURRENCE_DATE],[MESSAGE],[OCCURRENCE_COUNT],[TRANSLATED_MESSAGE]) ;
 END TRY BEGIN CATCH END CATCH;
