
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/30/2023 12:57:58 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230830125800 ON [SPRITZERTAIPINGDB].[DBO].[POWER_CONSUMPTION] ([CREATE_DATE],[CLASS_TYPE]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[CRANE_01],[CRANE_02],[CRANE_03],[CRANE_04],[CRANE_05],[CRANE_06],[CRANE_07],[CRANE_08]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230830125831 ON [SPRITZERTAIPINGDB].[DBO].[ASN_LINE] ([CLASS_TYPE],[ASN_LINE_KEY],[TU_ID]) ;
 END TRY BEGIN CATCH END CATCH;
