



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSUSERFILE_SYSINDEX] ON [E101TRAIN].[ICE].[SYSUSERFILE] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_1030] ON [SWISSLOG].[DBO].[FSW_TBLSWISSREQUEST] ([TYPENAME]) INCLUDE ([COMPANY],[EXCEPTIONERR],[KEYVALUE],[REQUESTDATE],[REQUESTID],[RESCODE],[RESDATE],[RESDESC],[RESTRANSCODE],[SERVICETYPE],[SUBTYPE],[TYPEOFACTION],[XMLREQUEST],[XMLRESPONSE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSUSERFILE_SYSINDEX] ON [E101TEST].[ICE].[SYSUSERFILE] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PART_SYSINDEX] ON [E101TEST].[ERP].[PART] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_POHEADER_SYSINDEX] ON [E101TEST].[ERP].[POHEADER] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSAGENTSCHED_SYSINDEX] ON [E101TEST].[ICE].[SYSAGENTSCHED] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;