

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230519002641 ON [E101TRAIN].[ICE].[SYSRPTLST]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSUSERFILE_SYSINDEX] ON [E101TRAIN].[ICE].[SYSUSERFILE] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSUSERFILE_SYSINDEX] ON [E101TEST].[ICE].[SYSUSERFILE] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PART_SYSINDEX] ON [E101TEST].[ERP].[PART] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230519002719 ON [E101TEST].[ERP].[SHIPHEAD]; 
END TRY 
BEGIN CATCH 
END CATCH;