
USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230506 ON [SPRITZERTAIPINGDB].[dbo].[LOCATION];
		PRINT N'INDEX IX_AIDBA_1_20230506 ON [SPRITZERTAIPINGDB].[dbo].[LOCATION] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230506 ON [SPRITZERTAIPINGDB].[dbo].[LOCATION] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230506 ON [SPRITZERTAIPINGDB].[dbo].[AUDIT_TRAIL_PARAM_PROP];
		PRINT N'INDEX IX_AIDBA_2_20230506 ON [SPRITZERTAIPINGDB].[dbo].[AUDIT_TRAIL_PARAM_PROP] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230506 ON [SPRITZERTAIPINGDB].[dbo].[AUDIT_TRAIL_PARAM_PROP] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230506 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_LOG];
		PRINT N'INDEX IX_AIDBA_3_20230506 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_LOG] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230506 ON [SPRITZERTAIPINGDB].[dbo].[TRANSPORT_LOG] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230506 ON [SPRITZERTAIPINGDB].[dbo].[TRANS];
		PRINT N'INDEX IX_AIDBA_4_20230506 ON [SPRITZERTAIPINGDB].[dbo].[TRANS] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230506 ON [SPRITZERTAIPINGDB].[dbo].[TRANS] CANNOT BE DROPPED.';
END CATCH;

USE [SPRITZERTAIPINGDB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230506 ON [SPRITZERTAIPINGDB].[dbo].[HOST_MESSAGE];
		PRINT N'INDEX IX_AIDBA_5_20230506 ON [SPRITZERTAIPINGDB].[dbo].[HOST_MESSAGE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230506 ON [SPRITZERTAIPINGDB].[dbo].[HOST_MESSAGE] CANNOT BE DROPPED.';
END CATCH;
