
BEGIN TRY
ALTER DATABASE [SPRITZERTAIPINGDB] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[SPRITZERTAIPINGDB] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [SPRITZERTAIPINGDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDB] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [SPRITZERTAIPINGDWH] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[SPRITZERTAIPINGDWH] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [SPRITZERTAIPINGDWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDWH] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;