
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/26/2023 5:59:35 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230826175939 ON [MIMS].[DBO].[SCT_DIREITOS_US_JANE] ([FILIAL],[LASTMODDATE]) INCLUDE ([ROWID],[EMPRESA],[ID_USUARIO]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_EXCEGRUPPROD] ON [MIMS].[DBO].[PRODUCAO_GRUPO_EXCECAO] ([ID_EXCEGRUPPROD],[ID_DEFIMATEEMBA]) INCLUDE ([ID_TIPOAVE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PEDIDO_VENDA_ITEM_DETALHE_ID_ITEMPEDIVEND] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND],[ID_DETAITEMPEDIVEND]) INCLUDE ([IE_DETAITEMPEDIVEND],[NR_LINHDETAITEMPEDIVEND],[QN_PESOEXPEDETAITEMPEDIVEND],[FL_UNIDOPERDETAITEMPEDIVEND],[FL_UNIDPRECDETAITEMPEDIVEND],[QN_EMBAEXPEDETAITEMPEDIVEND],[QN_UNIDEXPEDETAITEMPEDIVEND],[VL_IMPOEXPEDETAITEMPEDIVEND],[QN_EMBADETAITEMPEDIVEND],[QN_UNIDDETAITEMPEDIVEND],[QN_PESODETAITEMPEDIVEND],[VL_UNITDETAITEMPEDIVEND],[FL_UNIDERPDETAITEMPEDIVEND],[QN_PECAEXPEDETAITEMPEDIVEND],[QN_PESOREALDETAITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND],[ID_ITEMPEDIVEND]) INCLUDE ([QN_PESOPADREXPEITEMPEDIVEND],[QN_PESOREALEXPEITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_1_20220131] ON [MIMS].[DBO].[PEDIDO_DEVO_VEND_ITEM_DETA] ([ID_ITEMPEDIDEVOVEND],[ID_DETAITEMPEDIDEVOVEND]) INCLUDE ([IE_DETAITEMPEDIDEVOVEND],[FL_UNIDOPERDETAITEMPEDIDEVOVEN],[FL_UNIDIMPRDETAITEMPEDIDEVOVEN],[QN_EMBARECEDETAITEMPEDIDEVOVEN],[QN_UNIDRECEDETAITEMPEDIDEVOVEN],[QN_PESORECEDETAITEMPEDIDEVOVEN],[LASTMODDATE],[SYNCFLAG],[NR_LINHDETAITEMPEDIDEVOVEND],[QN_EMBADETAITEMPEDIDEVOVEND],[QN_UNIDDETAITEMPEDIDEVOVEND],[QN_PESODETAITEMPEDIDEVOVEND]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_HITACHI_45509_45508] ON [MIMS].[DBO].[PRODUCAO_DESCARTE] ([ID_ENTRAVEVIVA],[ID_DESCPROD]) INCLUDE ([ID_MOTIDESCPROD],[QN_UNIDDESCPROD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_HITACHI_210_209] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([FILIAL],[ID_MATEEMBALOCA]) INCLUDE ([ID_DEFIMATEEMBA],[ID_MATEEMBAFILI],[ID_UNIDMEDI_PECAMATEEMBAFILI],[ID_UNIDMEDI_UNIDMATEEMBAFILI],[QN_PECAPRODMATEEMBAFILI],[QN_PRODEMBAMATEEMBAFILI],[QN_PRODEMBAATUAMATEEMBALOCA]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
