
USE [master];
EXEC sp_configure 'show advanced options','1';
RECONFIGURE WITH OVERRIDE;
EXEC sp_configure 'xp_cmdshell','1';
RECONFIGURE WITH OVERRIDE;
EXEC xp_cmdshell 'md D:\AIDBA_AUDIT';
/*EXEC sp_configure 'xp_cmdshell','0';*/
RECONFIGURE WITH OVERRIDE;
EXEC sp_configure 'show advanced options','0';
RECONFIGURE WITH OVERRIDE;

USE [master];

IF NOT EXISTS (SELECT 1 FROM sys.server_file_audits WHERE [name] = 'AIDBA_AUDIT')
BEGIN
CREATE SERVER AUDIT [AIDBA_AUDIT]
TO FILE 
(	FILEPATH = N'D:\AIDBA_AUDIT'
	,MAXSIZE = 1 GB
	,MAX_ROLLOVER_FILES = 1
	,RESERVE_DISK_SPACE = ON
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)
END 

ALTER SERVER AUDIT [AIDBA_AUDIT] WITH ( STATE = ON);


-------FusionDW-------	
USE [FusionDW];
IF EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE [name] = 'AIDBA_AUDIT')
BEGIN
	ALTER DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] WITH (STATE = OFF);
	DROP DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT];
END

CREATE DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] FOR SERVER AUDIT [AIDBA_AUDIT]
ADD (SELECT,INSERT,UPDATE,DELETE,EXECUTE ON SCHEMA::[dbo] BY [public])
WITH (STATE = ON);


-------FusionOperational-------	
USE [FusionOperational];
IF EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE [name] = 'AIDBA_AUDIT')
BEGIN
	ALTER DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] WITH (STATE = OFF);
	DROP DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT];
END

CREATE DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] FOR SERVER AUDIT [AIDBA_AUDIT]
ADD (SELECT,INSERT,UPDATE,DELETE,EXECUTE ON SCHEMA::[dbo] BY [public])
WITH (STATE = ON);


-------ReportServer-------	
USE [ReportServer];
IF EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE [name] = 'AIDBA_AUDIT')
BEGIN
	ALTER DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] WITH (STATE = OFF);
	DROP DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT];
END

CREATE DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] FOR SERVER AUDIT [AIDBA_AUDIT]
ADD (SELECT,INSERT,UPDATE,DELETE,EXECUTE ON SCHEMA::[dbo] BY [public])
WITH (STATE = ON);


-------ReportServerTempDB-------	
USE [ReportServerTempDB];
IF EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE [name] = 'AIDBA_AUDIT')
BEGIN
	ALTER DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] WITH (STATE = OFF);
	DROP DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT];
END

CREATE DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] FOR SERVER AUDIT [AIDBA_AUDIT]
ADD (SELECT,INSERT,UPDATE,DELETE,EXECUTE ON SCHEMA::[dbo] BY [public])
WITH (STATE = ON);


-------ShotscopeNXSecurity-------	
USE [ShotscopeNXSecurity];
IF EXISTS (SELECT 1 FROM sys.database_audit_specifications WHERE [name] = 'AIDBA_AUDIT')
BEGIN
	ALTER DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] WITH (STATE = OFF);
	DROP DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT];
END

CREATE DATABASE AUDIT SPECIFICATION [AIDBA_AUDIT] FOR SERVER AUDIT [AIDBA_AUDIT]
ADD (SELECT,INSERT,UPDATE,DELETE,EXECUTE ON SCHEMA::[dbo] BY [public])
WITH (STATE = ON);

