
BEGIN TRY
ALTER DATABASE [ReportServerTempDB] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[ReportServerTempDB] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [ReportServerTempDB] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[ReportServerTempDB] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [ReportServerTempDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[ReportServerTempDB] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ReportServerTempDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [JDE_PRODUCTION] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[JDE_PRODUCTION] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [JDE_PRODUCTION] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[JDE_PRODUCTION] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [JDE_PRODUCTION] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [ReportServer] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[ReportServer] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [ReportServer] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[ReportServer] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [ReportServer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[ReportServer] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ReportServer] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [SCHEDULER] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[SCHEDULER] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [SCHEDULER] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[SCHEDULER] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [SCHEDULER] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[SCHEDULER] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SCHEDULER] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [JDE_ARCHIVE] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[JDE_ARCHIVE] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [JDE_ARCHIVE] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[JDE_ARCHIVE] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [JDE_ARCHIVE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[JDE_ARCHIVE] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [JDE_ARCHIVE] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [JDE920] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[JDE920] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [JDE920] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[JDE920] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [JDE920] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[JDE920] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [JDE920] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [JDE_PD920] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[JDE_PD920] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [JDE_PD920] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[JDE_PD920] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [JDE_PD920] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[JDE_PD920] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [JDE_PD920] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;