
ALTER DATABASE [tempdb] ADD FILE (NAME=N'tempdev02', FILENAME='F:\JDEdwards\MSSQL\Tmpdata\tempdev02.ndf' ,SIZE=8192MB TO FILEGROUP [PRIMARY]
			
ALTER DATABASE [tempdb] ADD FILE (NAME=N'tempdev03', FILENAME='F:\JDEdwards\MSSQL\Tmpdata\tempdev03.ndf' ,SIZE=8192MB TO FILEGROUP [PRIMARY]
			
ALTER DATABASE [tempdb] ADD FILE (NAME=N'tempdev04', FILENAME='F:\JDEdwards\MSSQL\Tmpdata\tempdev04.ndf' ,SIZE=8192MB TO FILEGROUP [PRIMARY]
			
ALTER DATABASE [tempdb] ADD FILE (NAME=N'tempdev08', FILENAME='F:\JDEdwards\MSSQL\Tmpdata\tempdev08.ndf' ,SIZE=8192MB TO FILEGROUP [PRIMARY]
			