
BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_116_115')
	BEGIN
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] DISABLE;
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'PEDIDO_VENDA_ITEM')
	BEGIN
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_116_115')
	BEGIN
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] DISABLE;
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_119_118')
	BEGIN
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'PEDIDO_VENDA_ITEM')
	BEGIN
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N10102')
	BEGIN
	ALTER INDEX [IDX_N10102]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_N10102] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10102] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N10102')
	BEGIN
	ALTER INDEX [IDX_N10102]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_N10102] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10102] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N001006')
	BEGIN
	ALTER INDEX [IDX_N001006]
	ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] DISABLE;
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N001006')
	BEGIN
	ALTER INDEX [IDX_N001006]
	ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] DISABLE;
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes')
	BEGIN
	ALTER INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] DISABLE;
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes')
	BEGIN
	ALTER INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] DISABLE;
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_1776')
	BEGIN
	ALTER INDEX [FARD_IX_1776]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [FARD_IX_1776] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_1776] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_131_130')
	BEGIN
	ALTER INDEX [Hitachi_IX_131_130]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [Hitachi_IX_131_130] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_131_130] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_123_122')
	BEGIN
	ALTER INDEX [Hitachi_IX_123_122]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [Hitachi_IX_123_122] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_123_122] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_121_120')
	BEGIN
	ALTER INDEX [Hitachi_IX_121_120]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [Hitachi_IX_121_120] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_121_120] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_IX_1566_1565')
	BEGIN
	ALTER INDEX [Hitachi_IX_1566_1565]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [Hitachi_IX_1566_1565] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_1566_1565] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_2839')
	BEGIN
	ALTER INDEX [FARD_IX_2839]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [FARD_IX_2839] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_2839] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;
