
BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_116_115]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_116_115] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_119_118]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_119_118] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N10102]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N10102] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10102] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N10102]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N10102] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10102] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N001006]
	ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N001006]
	ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes]
	ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes]
	ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [ix_PRODUCAO_REGISTRO_ID_PRODMATEEMBA_FL_PRODPROPREGIPROD_FL_TIPOUNIDREGIPROD_FL_ORIGREGIPROD_includes] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_1776]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_1776] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_1776] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_131_130]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_131_130] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_131_130] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_123_122]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_123_122] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_123_122] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_121_120]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_121_120] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_121_120] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_IX_1566_1565]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_IX_1566_1565] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_IX_1566_1565] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [FARD_IX_2839]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [FARD_IX_2839] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_2839] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;
