
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/22/2023 10:38:55 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230822103859 ON [MIMS].[DBO].[PEDIDO_VENDA] ([FILIAL],[ID_PEDIVEND],[NR_LOTEINTEPEDIVEND],[NR_LOTEINTEFILIPEDIVEND]) INCLUDE ([IE_PEDIVEND]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) INCLUDE ([ID_DETAITEMPEDIVEND],[IE_DETAITEMPEDIVEND],[NR_LINHDETAITEMPEDIVEND],[QN_EMBAEXPEDETAITEMPEDIVEND],[QN_UNIDEXPEDETAITEMPEDIVEND],[QN_PESOEXPEDETAITEMPEDIVEND],[FL_UNIDOPERDETAITEMPEDIVEND],[FL_UNIDPRECDETAITEMPEDIVEND],[VL_IMPOEXPEDETAITEMPEDIVEND],[QN_EMBADETAITEMPEDIVEND],[QN_UNIDDETAITEMPEDIVEND],[QN_PESODETAITEMPEDIVEND],[VL_UNITDETAITEMPEDIVEND],[FL_UNIDERPDETAITEMPEDIVEND],[QN_PECAEXPEDETAITEMPEDIVEND],[QN_PESOREALDETAITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
