



BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230822103859 ON [MIMS].[DBO].[PEDIDO_VENDA]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) INCLUDE ([ID_DETAITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;
