
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 6/19/2023 8:02:35 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230619200237 ON [SPRITZERTAIPINGDB].[DBO].[AUDIT_TRAIL_PARAM] ([UPDATED_BY],[CLASS_TYPE],[CREATE_DATE],[CREATED_BY],[AUDIT_PARAM_VALUE],[AUDIT_PARAM_TYPE],[AUDIT_PARAM_LABEL]) INCLUDE ([TRANSACTION_COUNT],[UPDATE_DATE]) ;
 END TRY BEGIN CATCH END CATCH;
