
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [SPRITZERTAIPINGDB] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[SPRITZERTAIPINGDB] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [SPRITZERTAIPINGDB] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDB] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [SPRITZERTAIPINGDB] SET TARGET_RECOVERY_TIME = 62 SECONDS;
PRINT '[SPRITZERTAIPINGDB] TARGET_RECOVERY_TIME is set 62.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [SPRITZERTAIPINGDWH] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[SPRITZERTAIPINGDWH] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [SPRITZERTAIPINGDWH] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDWH] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;