
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/30/2023 12:59:46 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230830125949 ON [SPRITZERTAIPINGDB].[DBO].[TRANS] ([CLASS_TYPE],[CREATE_DATE],[TRANSPORT_ORDER_KEY],[TO_PRODUCT_ID],[TO_TU_ID],[FROM_PRODUCT_ID],[FROM_TU_ID]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[OPERATION_ID]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230830130015 ON [SPRITZERTAIPINGDB].[DBO].[WORK_ZONE] ([CLASS_TYPE],[WORK_ZONE_KEY],[ORGANIZATION_NODE_KEY],[STATUS]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[WORK_ZONE_ID]) ;
 END TRY BEGIN CATCH END CATCH;
