
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/23/2023 11:35:10 PM UTC
*/
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROTEINPOLINEITEMS] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPOLINEITEMS] ([IRN]) INCLUDE ([PROTEINPRODUCTS],[VENDORSKUNO],[VENDORSKUNAME],[PROTEINPRODUCTSUOM]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230823233516 ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINFARMS] ([IRN],[PROTEINCOSTCENTERSIRN],[FARMTYPE]) INCLUDE ([CREATIONDATE],[LASTMODDATE],[REPLICASOURCEID],[PROTEINVENDORSIRN],[REPLICATIONDATETIME],[COMMENTS],[EXTERNALID],[CREATIONUSERID],[USERID],[FARMNAME],[FARMNO],[PROTEINGROWOUTCODESIRN]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PROTEINPERMISSIONSMEMBERGROUPS_1] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPERMISSIONSMEMBERGROUPS] ([PROTEINPERMISSIONSUSERSIRN]) INCLUDE ([PROTEINPERMISSIONSGROUPSIRN]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PMTSPROCRECVTRANS] ON [MTECH_V7_PRODUCTION].[MTECH].[PMTSPROCRECVTRANS] ([IRN]) INCLUDE ([OMORDERSSHIPMENTLINEITEMS],[PROTEINCOSTCENTERS]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_OMORDERSLINEITEMS] ON [MTECH_V7_PRODUCTION].[MTECH].[OMORDERSLINEITEMS] ([IRN],[PROTEINPRODUCTSSALESIRN]) INCLUDE ([U_OMBILLNO]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROTEINTAXRATES_3] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINTAXRATES] ([EFFECTIVEDATE],[PRODUCTTYPE],[PROTEINCOUNTRIESIRN_DESTINATION],[PROTEINCOUNTRIESIRN_SOURCE],[PROTEINSTATESIRN_DESTINATION],[PROTEINSTATESIRN_SOURCE],[PROTEINTAXCODESIRN]) INCLUDE ([TAXRATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PMTSPROCRECVTRANS_PROTEINFACILITYPLANTSIRN_VOIDFLAG_XDATE] ON [MTECH_V7_PRODUCTION].[MTECH].[PMTSPROCRECVTRANS] ([PROTEINFACILITYPLANTSIRN],[VOIDFLAG],[XDATE]) INCLUDE ([IRN],[PROTEINENTITIESIRN],[CREATIONDATE],[LASTMODDATE],[REPLICATIONDATETIME],[REPLICASOURCEID],[OMORDERSSHIPMENTIRN],[QUANTITYSHIPPED],[OMORDERSINVENTORYUSAGEIRN],[COMPLETEDFLAG],[EXTERNALID],[BACKORDERFLAG],[INVOICEDFLAG],[UNITPRICE],[CREATIONUSERID],[USERID],[SOURCECODE],[CURRENCYEFFECTIVEDATE],[CURRENCYEXCHANGERATES],[LINEINDEX],[OMORDERSINVENTORYRECVIRN],[OMORDERSSHIPMENTLINEITEMSIRN],[U_SECONDUOMSHIPMENTS],[U_SECONDQTYSHIPMENT],[U_DOCWEIGHTSHIPMENT],[PROTEINPRODUCTSUOMIRN_REF],[EXTRAFREEQUANTITY],[OMORDERSINVOICELINEITEMSIRN_TRIANGULATION],[PROTEINPOINVOICESLINEITEMSIRN_TRIANGULATION],[PULLEDFORWARDFLAG]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_6_20220401] ON [MTECH_V7_PRODUCTION].[MTECH].[OMORDERS] ([APPROVEDFLAG],[ORDERDATE],[POSTSTATUS],[PROFORMAINVOICENO],[PROTEINCOSTCENTERSIRN],[PROTEINPOIRN],[SHIPDATE]) INCLUDE ([DELIVERYDATE],[IRN],[OMCUSTOMERBUSINESSDELIVERYLOCATIONSIRN],[OMCUSTOMERSIRN_BILLTO],[OMCUSTOMERSIRN_SHIPTO],[ORDERNO],[_PO],[PROTEINEMPLOYEESIRN_SALES],[CREATIONDATE],[REPLICASOURCEID],[REPLICATIONDATETIME],[LASTMODDATE],[DELIVERYTIME],[LETTERCREDITEXPIRATIONDATE],[CANCELLATIONFLAG],[FREIGHTVERIFIEDFLAG],[OMINTCOMMERCIALTERMSIRN],[INVOICEPRINTPERCENTFREEFLAG],[INVOICEPRINTUNITPRICESFLAG],[INVOICEREMARKS],[INVOICEREMARKSPROFORMA],[ORDERLOCKEDFLAG],[OMPAYMENTMETHODSIRN],[RESALEFLAG],[ORDERSTATUS],[NOTES],[DELIVERYINSTRUCTIONS],[EVENTDATE],[VOIDFLAG],[COUNTRYEXPORTCODE],[POSTDATE],[PROTEINSHIPMETHODSIRN],[PROTEINFREIGHTTERMSIRN],[PROTEINPAYMENTTERMSIRN],[CURRENCYEFFECTIVEDATE],[CURRENCYEXCHANGERATES],[OMCUSTOMERCONTACTDETAILSIRN_B],[OMCUSTOMERCONTACTDETAILSIRN_S],[EXTERNALID],[PREPAYMENTRECEIVEDFLAG],[OMORDERSIRN],[PRE],[POSTTRANSACTIONID],[PONO],[SOURCECODE],[CREATIONUSERID],[USERID],[EARLIESTDELIVERYDATE],[LATESTDELIVERYDATE],[APPROVEDUSERID],[APPROVEDDATE],[PROCESSSEQUENCE],[HANDLINGINSTRUCTIONS],[PROTEINCURRENCIESIRN],[U_CURRENTEXCHANGERATE],[U_CREDITCHECKONHOLD],[U_SALESCC],[U_PRINT_MSG],[U_MOD_O],[PROTEINEMPLOYEESIRN_TECHSERVICE],[PROTEINCARRIERIRN],[TRADETYPE],[SHIPWEEK],[ORDERTYPE],[FORECASTORDERNO],[PRINTCOUNTER],[LASTPRINTDATE],[PRINTUSERID],[TRIANGULATIONFLAG],[CREATEPURCHASEORDERFLAG],[ADJUSTMENTFLAG],[INTERCOMPANYFLAG],[U_ENTRANCENO]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PROTEINAPPROVALTRANS_TRANSACTIONIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINAPPROVALTRANS] ([TRANSACTIONIRN],[STATUS]) INCLUDE ([XDATE],[PROTEINAPPROVALDEFINITIONSUSERSIRN],[CREATIONDATE],[LASTMODDATE],[REPLICATIONDATETIME],[REPLICASOURCEID],[EXTERNALID],[CREATIONUSERID],[USERID],[XTABLENAME]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_MTSYSUSERSETTINGS] ON [MTECH_V7_PRODUCTION].[MTECH].[MTSYSUSERSETTINGS] ([USERLOGON],[XKEY],[IRN]) INCLUDE ([CREATIONDATE],[LASTMODDATE],[REPLICATIONDATETIME],[TYPE],[XVALUE],[REPLICASOURCEID],[EXTERNALID],[CREATIONUSERID],[USERID],[LASTACCESSEDDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROTEINCOSTCENTERS_1] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINCOSTCENTERS] ([COSTCENTERNO],[IRN]) INCLUDE ([COSTCENTERNAME],[U_CC_ADDNO]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROTEINPRODUCTSSALES] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTSSALES] ([IRN],[PROTEINPRODUCTSIRN],[ACTIVEFLAG],[SALESSKUNO]) INCLUDE ([U_SECONDUOM_SKU]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PROTEINPRODUCTSVENDORSADDONS] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTSVENDORSADDONS] ([PROTEINPRODUCTSADDONSIRN]) INCLUDE ([CREATIONDATE],[LASTMODDATE],[REPLICATIONDATETIME],[REPLICASOURCEID],[RATE],[EXTERNALID],[CREATIONUSERID],[USERID],[PROTEINCURRENCIESIRN],[PAYEETYPE],[OMCUSTOMERSIRN],[PROTEINVENDORSIRN],[PROTEINCOSTCENTERSIRN]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PROTEINAPPROVALDEFINITIONSUSERS_PROTEINAPPROVALDEFINITIONSLEVELSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINAPPROVALDEFINITIONSUSERS] ([PROTEINAPPROVALDEFINITIONSLEVELSIRN]) INCLUDE ([CREATIONDATE],[LASTMODDATE],[REPLICATIONDATETIME],[REPLICASOURCEID],[EXTERNALID],[CREATIONUSERID],[USERID],[PROTEINPERMISSIONSUSERSIRN],[USERTYPE],[ACTIVEFLAG],[STARTINGDATE],[ENDINGDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_OMCUSTOMERS_2] ON [MTECH_V7_PRODUCTION].[MTECH].[OMCUSTOMERS] ([CUSTOMERNO],[IRN]) INCLUDE ([U_INVOICESENDTO]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROTEINGROWERAPPUSERS_PROTEINPERMISSIONSUSERSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINGROWERAPPUSERS] ([PROTEINPERMISSIONSUSERSIRN]) INCLUDE ([CREATIONDATE],[LASTMODDATE],[REPLICATIONDATETIME],[REPLICASOURCEID],[EXTERNALID],[CREATIONUSERID],[USERID],[PROTEINWAREHOUSESIRN],[MTSYSSCREENPROFILESIRN],[PROTEINTECHADVISORSIRN],[PROTEINVETERINARIANSIRN],[PRODUCTUSAGEMODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROTEINPRODUCTWHPURCHASEDETAIL] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTWHPURCHASEDETAIL] ([IRN]) INCLUDE ([CREATIONDATE],[LASTMODDATE],[REFNO],[XTIME],[COMMENTS],[POSTSTATUS],[EVENTDATE],[VOIDFLAG],[PROTEINFARMS],[PROTEINVENDORS],[POSTTRANSACTIONID],[CREATIONUSERID],[USERID],[REVERSEDFLAG]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_PROTEINPRODUCTWHPURCHASEDETAIL_4] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTWHPURCHASEDETAIL] ([PROTEINPRODUCTWHPURCHASESIRN]) INCLUDE ([LOTNO],[QUANTITY],[XVALUE],[UNITSRECEIVED],[PROTEINPOLINEITEMSIRN],[PROTEINPRODUCTSVENDORSIRN],[PROTEINPRODWHPURCHDTLIRN_SRC]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_OMCUSTOMERMASTER_7] ON [MTECH_V7_PRODUCTION].[MTECH].[OMCUSTOMERS] ([PROTEINEMPLOYEESIRN]) INCLUDE ([OMCUSTOMERSIRN_SHIPTO]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
