


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROTEINPOLINEITEMS] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPOLINEITEMS] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230823233516 ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINFARMS]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINPERMISSIONSMEMBERGROUPS_1] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPERMISSIONSMEMBERGROUPS] ([PROTEINPERMISSIONSUSERSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PMTSPROCRECVTRANS] ON [MTECH_V7_PRODUCTION].[MTECH].[PMTSPROCRECVTRANS] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_OMORDERSLINEITEMS] ON [MTECH_V7_PRODUCTION].[MTECH].[OMORDERSLINEITEMS] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROTEINTAXRATES_3] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINTAXRATES] ([EFFECTIVEDATE],[PRODUCTTYPE],[PROTEINCOUNTRIESIRN_DESTINATION],[PROTEINCOUNTRIESIRN_SOURCE],[PROTEINSTATESIRN_DESTINATION],[PROTEINSTATESIRN_SOURCE],[PROTEINTAXCODESIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PMTSPROCRECVTRANS_PROTEINFACILITYPLANTSIRN_VOIDFLAG_XDATE] ON [MTECH_V7_PRODUCTION].[MTECH].[PMTSPROCRECVTRANS] ([PROTEINFACILITYPLANTSIRN],[VOIDFLAG],[XDATE]) INCLUDE ([IRN],[PROTEINENTITIESIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX [IX_AIDBA_6_20220401] ON [MTECH_V7_PRODUCTION].[MTECH].[OMORDERS]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINAPPROVALTRANS_TRANSACTIONIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINAPPROVALTRANS] ([TRANSACTIONIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_MTSYSUSERSETTINGS] ON [MTECH_V7_PRODUCTION].[MTECH].[MTSYSUSERSETTINGS] ([USERLOGON],[XKEY]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROTEINCOSTCENTERS_1] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINCOSTCENTERS] ([COSTCENTERNO]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROTEINPRODUCTSSALES] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTSSALES] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINPRODUCTSVENDORSADDONS] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTSVENDORSADDONS] ([PROTEINPRODUCTSADDONSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINAPPROVALDEFINITIONSUSERS_PROTEINAPPROVALDEFINITIONSLEVELSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINAPPROVALDEFINITIONSUSERS] ([PROTEINAPPROVALDEFINITIONSLEVELSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_OMCUSTOMERS_2] ON [MTECH_V7_PRODUCTION].[MTECH].[OMCUSTOMERS] ([CUSTOMERNO]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROTEINGROWERAPPUSERS_PROTEINPERMISSIONSUSERSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINGROWERAPPUSERS] ([PROTEINPERMISSIONSUSERSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROTEINPRODUCTWHPURCHASEDETAIL] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTWHPURCHASEDETAIL] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINPRODUCTWHPURCHASEDETAIL_4] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTWHPURCHASEDETAIL] ([PROTEINPRODUCTWHPURCHASESIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_OMCUSTOMERMASTER_7] ON [MTECH_V7_PRODUCTION].[MTECH].[OMCUSTOMERS] ([PROTEINEMPLOYEESIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;