

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230613193034 ON [E101LIVE].[ICE].[SESSIONSTATE]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_ORDERHED_OPENORDER] ON [E101LIVE].[ERP].[ORDERHED] ([COMPANY],[OPENORDER],[ORDERNUM]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_UD110_UD_FS_SHIPBYDATE_C_FS_STATUS_C_FS_TYPE_C_FS_LOADINGBAY_C_FS_PICKINGSTATUS_C_FS_G_CHECKIN_C] ON [E101LIVE].[ICE].[UD110_UD] ([FS_G_CHECKIN_C],[FS_LOADINGBAY_C],[FS_PICKINGSTATUS_C],[FS_SHIPBYDATE_C],[FS_STATUS_C],[FS_TYPE_C]) INCLUDE ([FOREIGNSYSROWID],[FS_DPPRIORITY_C],[FS_G_CHECKINSTATUS_C],[FS_TIMESLOT_C],[FS_TRUCKNO_C]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230613193049 ON [E101LIVE].[ERP].[WHSEBIN]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTQTYDEFERRED_SYSINDEX] ON [E101LIVE].[ERP].[PARTQTYDEFERRED] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SHIPDTL_SYSINDEX] ON [E101LIVE].[ERP].[SHIPDTL] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSUSERFILE_SYSINDEX] ON [E101LIVE].[ICE].[SYSUSERFILE] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTBIN_SYSINDEX] ON [E101LIVE].[ERP].[PARTBIN] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTBINDEFERRED_SYSINDEX] ON [E101LIVE].[ERP].[PARTBINDEFERRED] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PARTTRAN] ON [E101LIVE].[ERP].[PARTTRAN] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_CHGLOG_SYSINDEX] ON [E101LIVE].[ICE].[CHGLOG] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTWHSE_SYSINDEX] ON [E101LIVE].[ERP].[PARTWHSE] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTQTY_SYSINDEX] ON [E101LIVE].[ERP].[PARTQTY] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_01_11062022] ON [SWISSLOGLIVE].[DBO].[FSW_TBLSWISSREQUEST] ([REQUESTID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_NOTIFICATIONS] ON [REPORTSERVER].[DBO].[NOTIFICATIONS] ([NOTIFICATIONID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_CATALOG] ON [REPORTSERVER].[DBO].[CATALOG] ([ITEMID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_BITFLAG_SYSINDEX] ON [E101LIVE].[ICE].[BITFLAG] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_INTQUEOUT_SYSINDEX] ON [E101LIVE].[ICE].[INTQUEOUT] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTLOT_SYSINDEX] ON [E101LIVE].[ERP].[PARTLOT] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PARTLOTDEFERRED_DEFERREDSEQ] ON [E101LIVE].[ERP].[PARTLOTDEFERRED] ([DEFERREDSEQ]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SYSACTIVITYLOG_SYSINDEX] ON [E101LIVE].[ICE].[SYSACTIVITYLOG] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_INTPARAMVALUES_SYSINDEX] ON [E101LIVE].[ICE].[INTPARAMVALUES] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;