
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 6/19/2023 7:38:42 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230619193847 ON [FAS].[DBO].[GLTEMPLATEDETAIL] ([DEBIT],[CREDIT],[COMPANYCODE],[BRANCHCODE],[CREDITORCODE],[DEBTORCODE],[TEMPLATECODE]) INCLUDE ([CURRENCYCODE],[EXRATE],[BASEAMOUNT],[REMARK],[DEPARTMENTCODE],[ANALYSISCODE],[ITEMNO],[GLCODE],[DEBITCREDIT],[LOCALAMOUNT],[SUBANALYSISCODE],[CREATEBY],[CREATEDATE],[EDITBY],[EDITDATE],[TAXCODE],[MSIC],[REF1],[REF2]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_2_20220926] ON [FAS].[DBO].[GLTRANSACTION] ([BRANCHCODE],[COMPANYCODE],[GLCODE],[TXNDATE],[ISCANCEL]) INCLUDE ([ANALYSISCODE],[CREDIT],[CREDITORCODE],[DEBIT],[DEBITCREDIT],[DEBTORCODE],[DEPARTMENTCODE],[DOCUMENTNO],[DOCUMENTTYPE],[ITEMNO],[MODULETYPE],[REMARK],[VOUCHERTYPE],[CURRENCYCODE],[EXRATE],[BASEAMOUNT],[LOCALAMOUNT],[REFNO],[CANCELBY],[CANCELDATE],[CREATEBY],[CREATEDATE],[EDITBY],[EDITDATE]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
