

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230809194604 ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINPRODUCTWHUSAGE]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PMTSTRANSFERDESTINATIONS_4] ON [MTECH_V7_PRODUCTION].[MTECH].[PMTSTRANSFERDESTINATIONS] ([PROTEINENTITIESIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PMTSTRANSFERDESTDETAILS] ON [MTECH_V7_PRODUCTION].[MTECH].[PMTSTRANSFERDESTDETAILS] ([PMTSTRANSFERDESTINATIONSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROTEINGROWERAPPUSERS_PROTEINPERMISSIONSUSERSIRN] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINGROWERAPPUSERS] ([PROTEINPERMISSIONSUSERSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_MTSYSUSERSETTINGS] ON [MTECH_V7_PRODUCTION].[MTECH].[MTSYSUSERSETTINGS] ([USERLOGON],[XKEY]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230809194612 ON [MTECH_V7_PRODUCTION].[MTECH].[BIMFIELDTRANS]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_MTSYSENVIRONMENTS] ON [MTECH_V7_PRODUCTION].[MTECH].[MTSYSENVIRONMENTS] ([DATABASENAME],[SERVERNAME]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_REPORTLAYOUTML] ON [MTECH_V7_PRODUCTION].[MTECH].[REPORTLAYOUTML] ([REPORTLAYOUTSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROTEINFARMS] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINFARMS] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINENTITIES_DTA_4] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINENTITIES] ([ENTITYNO],[IRN],[PENNO],[PROTEINFARMSIRN],[PROTEINHOUSESIRN],[STATUS]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_BIMENTITIES] ON [MTECH_V7_PRODUCTION].[MTECH].[BIMENTITIES] ([PROTEINENTITIESIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PROTEINENTITIES_2] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINENTITIES] ([ENTITYNO],[PENNO],[PROTEINFARMSIRN],[PROTEINHOUSESIRN],[STATUS]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_FMIMFEEDTRANSORDERS] ON [MTECH_V7_PRODUCTION].[MTECH].[FMIMFEEDTRANSORDERS] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_FMIMFEEDTRANS_10] ON [MTECH_V7_PRODUCTION].[MTECH].[FMIMFEEDTRANS] ([FMIMFEEDTRANSORDERSIRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROTEINWEIGHTSCALES] ON [MTECH_V7_PRODUCTION].[MTECH].[PROTEINWEIGHTSCALES] ([IRN]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_BRIMFIELDTRANS_ENTITYHISTORYFLAG_PROTEINENTITIESIRN_XDATE] ON [MTECH_V7_PRODUCTION].[MTECH].[BRIMFIELDTRANS] ([ENTITYHISTORYFLAG],[PROTEINENTITIESIRN],[XDATE]) INCLUDE ([FEEDCONSUMED],[IRN],[MORTALITY]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;