
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 7/25/2023 4:23:23 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230725042326 ON [SPRITZERTAIPINGDB].[DBO].[ORDER_TU_PLAN] ([STATUS],[CLASS_TYPE],[CREATE_DATE]) INCLUDE ([CREATED_BY],[STATUS_DATE],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[WEIGHT]) ;
 END TRY BEGIN CATCH END CATCH;
