
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/16/2023 9:00:57 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230816090059 ON [SPRITZERTAIPINGDB].[DBO].[MANUAL_TRANSPORT_LINK] ([CLASS_TYPE],[CREATE_DATE]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[PRIORITY],[FROM_LOCATION_KEY],[TO_LOCATION_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230816090114 ON [SPRITZERTAIPINGDB].[DBO].[AUDIT_TRAIL_PARAM_PROP] ([CLASS_TYPE],[CREATE_DATE],[AUDIT_PARAM_PROP_KEY]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[PROP_LABEL],[PROP_TYPE],[PROP_VALUE]) ;
 END TRY BEGIN CATCH END CATCH;
