
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 6/20/2023 2:09:04 AM UTC
*/
BEGIN TRY     CREATE  INDEX [IX_AIDBA_5_20220926] ON [CMS].[DBO].[INVGOODSSOLDHEADER] ([PROPERTYID],[RECORDSTATUS],[TXNDATE]) INCLUDE ([DEPARTMENTID],[DOCUMENTID],[REFERENCEID],[REMARKS]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_2_20220926] ON [FAS].[DBO].[GLTRANSACTION] ([BRANCHCODE],[COMPANYCODE],[GLCODE],[TXNDATE],[ISCANCEL]) INCLUDE ([ANALYSISCODE],[CREDIT],[CREDITORCODE],[DEBIT],[DEBITCREDIT],[DEBTORCODE],[DEPARTMENTCODE],[DOCUMENTNO],[DOCUMENTTYPE],[ITEMNO],[MODULETYPE],[REMARK],[VOUCHERTYPE],[CURRENCYCODE],[EXRATE],[BASEAMOUNT],[LOCALAMOUNT],[REFNO],[CANCELBY],[CANCELDATE],[CREATEBY],[CREATEDATE],[EDITBY],[EDITDATE]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_APINVOICEDETAIL] ON [FAS].[DBO].[APINVOICEDETAIL] ([BRANCHCODE],[COMPANYCODE],[ITEMNO],[VOUCHERNO],[TAX1AMOUNT]) INCLUDE ([LOCALAMOUNT],[TAX2AMOUNT],[TAX3AMOUNT],[TAX4AMOUNT],[GLCODE],[DEPARTMENTCODE],[TAXCODE],[REMARK]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
