
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/23/2023 11:26:31 AM UTC
*/
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_NOTIFICATIONS] ON [REPORTSERVER].[DBO].[NOTIFICATIONS] ([NOTIFICATIONID],[PROCESSSTART],[PROCESSAFTER]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_CATALOG] ON [REPORTSERVER].[DBO].[CATALOG] ([ITEMID],[PATH]) INCLUDE ([TYPE],[POLICYID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_EVENT] ON [REPORTSERVER].[DBO].[EVENT] ([EVENTID],[PROCESSSTART]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) INCLUDE ([ID_DETAITEMPEDIVEND],[IE_DETAITEMPEDIVEND],[NR_LINHDETAITEMPEDIVEND],[QN_EMBAEXPEDETAITEMPEDIVEND],[QN_UNIDEXPEDETAITEMPEDIVEND],[QN_PESOEXPEDETAITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND],[ID_ITEMPEDIVEND]) INCLUDE ([QN_PESOPADREXPEITEMPEDIVEND],[QN_PESOREALEXPEITEMPEDIVEND]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
