

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230727044920 ON [CHUANSINCACTUS].[DBO].[PURCHASEORDERS]; 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_XPWEAKREFERENCE] ON [CHUANSINCACTUS].[DBO].[XPWEAKREFERENCE] ([ROWINDEX]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_SPECIALACCOUNTS] ON [CHUANSINCACTUS].[DBO].[SPECIALACCOUNTS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230727044924 ON [CHUANSINCACTUS].[DBO].[PAYMENTS]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_STOCKLOCATIONS] ON [CHUANSINCACTUS].[DBO].[STOCKLOCATIONS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IGOODSRECEIVEDNOTEID_GOODSRECEIVEDNOTEDETAILS] ON [CHUANSINCACTUS].[DBO].[GOODSRECEIVEDNOTEDETAILS] ([GOODSRECEIVEDNOTEID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IGOODSRECEIVEDNOTEDETAIL_PURCHASETRANSFERLINK] ON [CHUANSINCACTUS].[DBO].[PURCHASETRANSFERLINK] ([GOODSRECEIVEDNOTEDETAIL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDOCUMENTID_STOCKTRANSACTIONS] ON [CHUANSINCACTUS].[DBO].[STOCKTRANSACTIONS] ([DOCUMENTID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [ISTOCKID_UOMS] ON [CHUANSINCACTUS].[DBO].[UOMS] ([STOCKID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDOCUMENTID_DOCUMENTINFO] ON [CHUANSINCACTUS].[DBO].[DOCUMENTINFO] ([DOCUMENTID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_RECEIPTS] ON [CHUANSINCACTUS].[DBO].[RECEIPTS] ([ROWINDEX]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_ARCN] ON [CHUANSINCACTUS].[DBO].[ARCN] ([ROWINDEX]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;