
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/9/2023 1:02:22 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809130225 ON [SPRITZERTAIPINGDB].[DBO].[CHANNEL] ([CLASS_TYPE],[SUBSYSTEM_ID]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[CHANNEL_KEY],[CHANNEL_VALUE],[NON_PERSISTENT_MESSAGES],[SEND_QUEUE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809130227 ON [SPRITZERTAIPINGDB].[DBO].[EVENTLOG] ([EVENT_KEY],[SEVERITY],[CLASS_TYPE],[ORIGIN_CATEGORY]) INCLUDE ([OCCURRENCE_DATE],[MESSAGE],[OCCURRENCE_COUNT],[TRANSLATED_MESSAGE]) ;
 END TRY BEGIN CATCH END CATCH;
