
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/22/2023 12:37:39 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230522123742 ON [CLUBON].[DBO].[MRMPAYMENTDELETEMASTER] ([ID],[TRANSACTIONDATE],[SALESID]) INCLUDE ([REMARK],[USERID],[TRANSACTIONCLASS],[YEAR],[DESCRIPTION],[ACCOUNTID],[PAYMENTCODE],[CURRENCYAMOUNT],[AMOUNT],[CREDITCARDTYPE],[BANKNAME],[OTHERSTYPE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PRSITEMMASTER] ON [CLUBON].[DBO].[RETITEMMASTER] ([ITEMCODE],[TRANSACTIONCLASS],[TRANSACTIONDATE],[RECORDSTATUS]) INCLUDE ([REMARKS],[USERID],[AMOUNT],[AUTHORISEDBY],[REGCHITID],[CANCELLEDDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
