
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 6/9/2023 7:18:39 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230609071843 ON [SPRITZERTAIPINGDB].[DBO].[TARGET_BUFFER_RESERVATION] ([CLASS_TYPE],[CREATE_DATE],[STATUS],[TRANSPORT_ORDER_KEY],[TARGET_BUFFER_ID]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230609071849 ON [SPRITZERTAIPINGDB].[DBO].[CONFIGURATION_VALUE] ([CLASS_TYPE],[CONFIG_VALUE_KEY],[DATA_KEY]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY]) ;
 END TRY BEGIN CATCH END CATCH;
