

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230609071843 ON [SPRITZERTAIPINGDB].[DBO].[TARGET_BUFFER_RESERVATION]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230609071849 ON [SPRITZERTAIPINGDB].[DBO].[CONFIGURATION_VALUE]; 
END TRY 
BEGIN CATCH 
END CATCH;






