

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230726103831 ON [OCS].[DBO].[A_A_LOADINGAPPOINTMENTTIMETRANSACTION_LOG]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SLIST_UNIQUE] ON [COLOS].[DBO].[SLIST] ([INTVALUE],[STRLISTNAME]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230726103834 ON [VEEAMONE].[REPORTER].[OBJECTPROPERTY]; 
END TRY 
BEGIN CATCH 
END CATCH;