
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 7/26/2023 10:38:29 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230726103831 ON [OCS].[DBO].[A_A_LOADINGAPPOINTMENTTIMETRANSACTION_LOG] ([ROWID],[LOG_TABLEROW]) INCLUDE ([LOG_REVERSALTYPE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_SLIST_UNIQUE] ON [COLOS].[DBO].[SLIST] ([INTVALUE],[STRLISTNAME]) INCLUDE ([STRDESCRIPTION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230726103834 ON [VEEAMONE].[REPORTER].[OBJECTPROPERTY] ([ID],[MODIFICATIONID],[ISDELETED]) INCLUDE ([PROPKEY],[OBJECTID],[PROPERTYID],[INTVALUE]) ;
 END TRY BEGIN CATCH END CATCH;
