
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 7/13/2023 7:30:42 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230713073045 ON [SPRITZERTAIPINGDB].[DBO].[POWER_CONSUMPTION] ([CLASS_TYPE],[CREATE_DATE]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[CRANE_01],[CRANE_02],[CRANE_03],[CRANE_04],[CRANE_05],[CRANE_06],[CRANE_07],[CRANE_08]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230713073053 ON [SPRITZERTAIPINGDB].[DBO].[TELEGRAM_LOG] ([CLASS_TYPE],[UPDATED_BY],[CREATE_DATE],[CHANNEL_VALUE],[TELEGRAM_TYPE],[SUBSYSTEM_NAME],[TELEGRAM_LOG_KEY],[PROCESSING_RESULT]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[DESCRIPTION],[TELEGRAM_JSON],[DIRECTION],[EXCEPTION_TEXT]) ;
 END TRY BEGIN CATCH END CATCH;
