
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/23/2023 11:10:34 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230823111038 ON [SPRITZERTAIPINGDB].[DBO].[WORKSTATION] ([STATUS],[CLASS_TYPE],[SESSION_ID]) INCLUDE ([CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[PRIORITY],[WORKSTATION_ID],[BLIND_RECEIVING],[HOSTNAME],[LAST_ACTIVITY],[LB_WORKSTATION_TYPE_ID],[LOGIN_REQUIRED_FOR_OPERATION],[PRINTER_NAME],[SCAN_ORDER_TU],[SEQUENCE],[STATUS_DATE],[WORKSTATION_TYPE],[CURRENT_OPERATION_DEF_ID],[DEFAULT_OPERATION_DEF_ID],[NEGATIVE_PICKING_THRESHOLD],[SCAN_PUTAWAY_TU]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230823111044 ON [SPRITZERTAIPINGDB].[DBO].[EVENTLOG] ([EVENT_KEY],[SEVERITY],[CLASS_TYPE],[ORIGIN_CATEGORY]) INCLUDE ([OCCURRENCE_DATE],[MESSAGE],[OCCURRENCE_COUNT],[TRANSLATED_MESSAGE]) ;
 END TRY BEGIN CATCH END CATCH;
