
BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_IdxWhseActTransUOM')
	BEGIN
	ALTER INDEX [IX_PartTran_IdxWhseActTransUOM]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_IdxWhseActTransUOM] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_IdxWhseActTransUOM] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'PK_PartQtyDeferred')
	BEGIN
	ALTER INDEX [PK_PartQtyDeferred]
	ON [E101Live].[Erp].[PartQtyDeferred] DISABLE;
	PRINT 'INDEX [PK_PartQtyDeferred] ON [E101Live].[Erp].[PartQtyDeferred] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [PK_PartQtyDeferred] ON [E101Live].[Erp].[PartQtyDeferred] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartBin_CompanySysRevID')
	BEGIN
	ALTER INDEX [IX_PartBin_CompanySysRevID]
	ON [E101Live].[Erp].[PartBin] DISABLE;
	PRINT 'INDEX [IX_PartBin_CompanySysRevID] ON [E101Live].[Erp].[PartBin] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartBin_CompanySysRevID] ON [E101Live].[Erp].[PartBin] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_idxRevert')
	BEGIN
	ALTER INDEX [IX_PartTran_idxRevert]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_idxRevert] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_idxRevert] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_CallNum')
	BEGIN
	ALTER INDEX [IX_PartTran_CallNum]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_CallNum] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_CallNum] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_PlantTranIdx')
	BEGIN
	ALTER INDEX [IX_PartTran_PlantTranIdx]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_PlantTranIdx] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_PlantTranIdx] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_DemandReconcileNum')
	BEGIN
	ALTER INDEX [IX_PartTran_DemandReconcileNum]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_DemandReconcileNum] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_DemandReconcileNum] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_idxABT')
	BEGIN
	ALTER INDEX [IX_PartTran_idxABT]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_idxABT] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_idxABT] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_RefCodeIdx')
	BEGIN
	ALTER INDEX [IX_PartTran_RefCodeIdx]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_RefCodeIdx] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_RefCodeIdx] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartTran_RefTypeIdx')
	BEGIN
	ALTER INDEX [IX_PartTran_RefTypeIdx]
	ON [E101Live].[Erp].[PartTran] DISABLE;
	PRINT 'INDEX [IX_PartTran_RefTypeIdx] ON [E101Live].[Erp].[PartTran] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartTran_RefTypeIdx] ON [E101Live].[Erp].[PartTran] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Live].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Live].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Live].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_StartedOn')
	BEGIN
	ALTER INDEX [IX_SysTask_StartedOn]
	ON [E101Live].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Live].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Live].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_PartBin_PartWhsDimLotBin')
	BEGIN
	ALTER INDEX [IX_PartBin_PartWhsDimLotBin]
	ON [E101Live].[Erp].[PartBin] DISABLE;
	PRINT 'INDEX [IX_PartBin_PartWhsDimLotBin] ON [E101Live].[Erp].[PartBin] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_PartBin_PartWhsDimLotBin] ON [E101Live].[Erp].[PartBin] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_ABTWork_SysIndex')
	BEGIN
	ALTER INDEX [IX_ABTWork_SysIndex]
	ON [E101Live].[Erp].[ABTWork] DISABLE;
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Live].[Erp].[ABTWork] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Live].[Erp].[ABTWork] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_ShipDtl_ChangeIdx')
	BEGIN
	ALTER INDEX [IX_ShipDtl_ChangeIdx]
	ON [E101Live].[Erp].[ShipDtl] DISABLE;
	PRINT 'INDEX [IX_ShipDtl_ChangeIdx] ON [E101Live].[Erp].[ShipDtl] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_ShipDtl_ChangeIdx] ON [E101Live].[Erp].[ShipDtl] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_13938')
	BEGIN
	ALTER INDEX [FARD_IX_13938]
	ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] DISABLE;
	PRINT 'INDEX [FARD_IX_13938] ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_13938] ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_5313')
	BEGIN
	ALTER INDEX [FARD_IX_5313]
	ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] DISABLE;
	PRINT 'INDEX [FARD_IX_5313] ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_5313] ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_104007')
	BEGIN
	ALTER INDEX [FARD_IX_104007]
	ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] DISABLE;
	PRINT 'INDEX [FARD_IX_104007] ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_104007] ON [SwisslogLive].[dbo].[FSW_tblSwissRequest] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_903145')
	BEGIN
	ALTER INDEX [FARD_IX_903145]
	ON [SwisslogLive].[dbo].[FSW_tblEpicorRequest] DISABLE;
	PRINT 'INDEX [FARD_IX_903145] ON [SwisslogLive].[dbo].[FSW_tblEpicorRequest] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_903145] ON [SwisslogLive].[dbo].[FSW_tblEpicorRequest] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_903179')
	BEGIN
	ALTER INDEX [FARD_IX_903179]
	ON [SwisslogLive].[dbo].[FSW_tblEpicorRequest] DISABLE;
	PRINT 'INDEX [FARD_IX_903179] ON [SwisslogLive].[dbo].[FSW_tblEpicorRequest] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_903179] ON [SwisslogLive].[dbo].[FSW_tblEpicorRequest] CANNOT BE DISABLED.';
END CATCH;
