

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230823111740 ON [COLOS].[DBO].[SPALLETLINE_SDEVICE]; 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    DROP INDEX [IX_AIDBA_15_20220908] ON [COLOS].[DBO].[PPALLET]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SLIST_UNIQUE] ON [COLOS].[DBO].[SLIST] ([INTVALUE],[STRLISTNAME]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;
