
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/23/2023 11:17:38 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230823111740 ON [COLOS].[DBO].[SPALLETLINE_SDEVICE] ([ID],[SPALLETLINEID]) INCLUDE ([SDEVICEID]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_15_20220908] ON [COLOS].[DBO].[PPALLET] ([BLNCREATEDMANUALLY],[STATUS],[STRPALLETLINENUMBER],[BPRODORDERID]) INCLUDE ([STRICONNAME],[BARTICLEID],[SPALLETLINEID],[PJOBID],[CREATEDON],[CREATEDBY],[MODIFIEDON],[MODIFIEDBY],[STRSSCC],[INTENUM_PALLETLOAD],[INTENUM_IDENTIFICATIONTYPE],[INTLINENUMBER],[STRRECEIVEDDATA],[INTRECEIVEDQUANTITY],[DTEBBE],[DTEQUEUEDTIME],[BLNIGNORE],[BLNOPERATORINPUT],[BLNRECEIVEDLOW],[BLNRECEIVEDINCOMPLETE],[BLNTOBACKUP],[BLNEXPORTED],[INTQUANTITYCASES],[STRLOTCODE],[STRGTIN_PALLET],[STRARTICLENUMBER],[STRARTICLEVARIANT],[STRARTICLEDESCRIPTION01],[STRARTICLEDESCRIPTION02],[STRLAYOUT_PALLET],[BLNPERFORMANCEREGISTERED],[STRORDERNUMBER],[STRMESSAGE],[INTSEQUENCENUMBER],[STRDATEFORMAT],[BLNDATEFIXED],[STRDEFAULTBACKUPPRINTER],[MMWEEKOFMM],[PONUMBER],[CUSTEXPIRYDATE],[STRARTICLEDESCRIPTION03],[STRCOUNTRY],[STRSKUNAME],[SCANNEDLOTCODE],[SCANNEDDATAMATCHED],[PRODLINE],[STRUOM],[BESTBEFOREDATE],[PARTSHORTDESC],[HEALTHCERT]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_SLIST_UNIQUE] ON [COLOS].[DBO].[SLIST] ([INTVALUE],[STRLISTNAME]) INCLUDE ([STRDESCRIPTION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
