
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 6/13/2023 7:48:38 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230613194841 ON [SPRITZERTAIPINGDB].[DBO].[AUDIT_TRAIL_PARAM] ([UPDATED_BY],[CLASS_TYPE],[CREATE_DATE],[CREATED_BY],[AUDIT_PARAM_VALUE],[AUDIT_PARAM_TYPE],[AUDIT_PARAM_LABEL]) INCLUDE ([TRANSACTION_COUNT],[UPDATE_DATE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230613194846 ON [SPRITZERTAIPINGDB].[DBO].[ORDER_LINE] ([CLASS_TYPE],[ORDER_LINE_KEY]) INCLUDE ([PRODUCT_KEY],[ALLOCATION_TOLERANCE_WINDOW],[BEST_BEFORE_DATE],[CHECK_IN_DATE],[CREATE_DATE],[CREATED_BY],[EXCLUDED_FROM_ALLOCATION],[EXPIRATION_WINDOW],[EXPIRY_DATE],[INVENTORY_SORTING],[LAST_ALLOCATION_DATE],[LOAD_UNIT_ID],[LOT_CODE],[MANUFACTURING_DATE],[ORDERED_TU_ID],[QUANTITY_ALLOCATED],[QUANTITY_CANCELED],[QUANTITY_ORDERED],[QUANTITY_PICKED],[QUANTITY_RESERVED],[QUANTITY_SHIPPED],[QUANTITY_TO_ALLOCATE],[RELEVANT_DATE_FOR_ALLOCATION],[STATUS],[STATUS_DATE],[TRANSACTION_COUNT],[UOM_TREE],[UPDATE_DATE],[UPDATED_BY],[ATTRIBUTE_SET],[CONSOLIDATION_LOCATION_KEY],[MATERIAL_STATUS_ID]) ;
 END TRY BEGIN CATCH END CATCH;
