
EXEC sp_configure 'show advanced options','1';
RECONFIGURE WITH OVERRIDE;
EXEC sp_configure 'xp_cmdshell','1';
RECONFIGURE WITH OVERRIDE;
EXEC xp_cmdshell 'md "G:\MYTPSYNQSRV01\SSDE_DATA"';
EXEC xp_cmdshell 'md "E:\MYTPSYNQSRV01\SSDE_LOG"';

CREATE TABLE #results (result nvarchar(max))


BEGIN TRY
	USE master
	IF EXISTS (SELECT * FROM sys.databases WHERE name = 'SPRITZERTAIPINGDWH' AND state = 0)
	BEGIN

		IF (SELECT physical_name FROM sys.master_files WHERE database_id = DB_ID(N'SPRITZERTAIPINGDWH') AND FILE_ID = 1) = 'C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH.mdf'
		BEGIN

			ALTER DATABASE [SPRITZERTAIPINGDWH] SET OFFLINE WITH ROLLBACK IMMEDIATE;

			IF OBJECT_ID(N'tempdb..#results') IS NOT NULL
			BEGIN
				TRUNCATE TABLE #results
			END
			INSERT INTO #results
			EXEC master..xp_cmdshell 'copy "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH.mdf" "G:\MYTPSYNQSRV01\SSDE_DATA\SPRITZERTAIPINGDWH.mdf" /Z /Y';
			IF EXISTS(SELECT * FROM #results WHERE result LIKE '%1 file(s) copied.%')
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDWH] MODIFY FILE (NAME='SPRITZERTAIPINGDWH' , FILENAME='G:\MYTPSYNQSRV01\SSDE_DATA\SPRITZERTAIPINGDWH.mdf');
				ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
				EXEC master..xp_cmdshell 'del "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH.mdf"';
			END
			ELSE
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
			END
			TRUNCATE TABLE #results
		END
	END
END TRY
BEGIN CATCH
	IF DB_ID(N'SPRITZERTAIPINGDWH') IS NOT NULL
	BEGIN
		ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
	END
END CATCH

BEGIN TRY
	USE master
	IF EXISTS (SELECT * FROM sys.databases WHERE name = 'SPRITZERTAIPINGDWH' AND state = 0)
	BEGIN

		IF (SELECT physical_name FROM sys.master_files WHERE database_id = DB_ID(N'SPRITZERTAIPINGDWH') AND FILE_ID = 2) = 'C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH_log.ldf'
		BEGIN

			ALTER DATABASE [SPRITZERTAIPINGDWH] SET OFFLINE WITH ROLLBACK IMMEDIATE;

			IF OBJECT_ID(N'tempdb..#results') IS NOT NULL
			BEGIN
				TRUNCATE TABLE #results
			END
			INSERT INTO #results
			EXEC master..xp_cmdshell 'copy "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH_log.ldf" "E:\MYTPSYNQSRV01\SSDE_LOG\SPRITZERTAIPINGDWH_log.ldf" /Z /Y ';
			IF EXISTS(SELECT * FROM #results WHERE result LIKE '%1 file(s) copied.%')
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDWH] MODIFY FILE (NAME='SPRITZERTAIPINGDWH_log' , FILENAME='E:\MYTPSYNQSRV01\SSDE_LOG\SPRITZERTAIPINGDWH_log.ldf');
				ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
				EXEC master..xp_cmdshell 'del "C:\Program Files\Microsoft SQL Server\MSSQL12.WM6\MSSQL\DATA\SPRITZERTAIPINGDWH_log.ldf"';
			END
			ELSE
			BEGIN
				ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
			END
			TRUNCATE TABLE #results
		END
	END
END TRY
BEGIN CATCH
	IF DB_ID(N'SPRITZERTAIPINGDWH') IS NOT NULL
	BEGIN
		ALTER DATABASE [SPRITZERTAIPINGDWH] SET ONLINE;
	END
END CATCH

EXEC sp_configure 'xp_cmdshell','0';
RECONFIGURE WITH OVERRIDE;
EXEC sp_configure 'show advanced options','0';
RECONFIGURE WITH OVERRIDE;
