
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/10/2023 7:48:56 AM UTC
*/
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PURCHASERETURNDETAILS] ON [CHUANSINCACTUS].[DBO].[PURCHASERETURNDETAILS] ([ID],[UOMID],[QTY],[LOCALONECENTSDIFF]) INCLUDE ([PROJECT],[NETAMOUNT],[NETAMOUNTLOCAL],[WTAXAMOUNT],[WTAXAMOUNTLOCAL]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_GLACCOUNTS] ON [CHUANSINCACTUS].[DBO].[GLACCOUNTS] ([ID],[ROWINDEX],[SPECIALACCOUNTID]) INCLUDE ([GLACCOUNTCODE],[CURRENCY],[DESCRIPTION],[NOTES],[BANKACCOUNTNO],[GSTMSICCODE],[SAC],[TARIFFCODE],[DESCRIPTION2],[PARENT],[DRCR],[ISCREDITCARD],[ISACTIVE],[ISREVALUATION],[ISSUBACCOUNT],[OPTIMISTICLOCKFIELD],[HASCHILDINCOA],[INCLUDEINCASHFLOWFORECASTADVISOR],[SSTTARIFFCODE],[ATCCODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_APMATCHED] ON [CHUANSINCACTUS].[DBO].[APMATCHED] ([ID],[COMPANYCODE]) INCLUDE ([COMPANYNAME],[CATEGORY],[AREA],[PURCHASER],[COMPANYNAME2],[CONTROLACCOUNT],[GLACCOUNT],[ADDRESS1],[ADDRESS2],[ADDRESS3],[ADDRESS4],[CONTACTPERSON],[PHONENO1],[PHONENO2],[FAXNO1],[FAXNO2],[EMAIL],[BUSINESSNATURE],[CURRENCY],[TERM]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230810074933 ON [CHUANSINCACTUS].[DBO].[ARMATCHED] ([ISPOSTDATEDCHEQUE],[ID],[FOREXPOSTINGDATE],[ARTRANID]) INCLUDE ([GLACCOUNTID],[OPTIMISTICLOCKFIELD],[PAYFORID],[AMOUNT],[PAYFORAMOUNTLOCAL],[PAYFORCODE],[ARTYPE],[ARCODE],[PAYFORTYPE],[ARAMOUNTLOCAL],[ISCANCELLED],[ARREMARK],[PAYFORREMARK],[PAYFORPROJECTTOTALAMOUNT],[PAYFORACCOUNTAMOUNT]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_RECEIPTS] ON [CHUANSINCACTUS].[DBO].[RECEIPTS] ([ROWINDEX],[ISCANCELLED],[DEBTORID],[OBJECTTYPE],[TAXDATE],[ISPOSTDATEDCHEQUE],[RECEIPTDATE],[ISBOUNCEDCHEQUE],[BOUNCEDCHEQUEDATE]) INCLUDE ([NETTOTALAMOUNTLOCAL],[ROUNDINGADJUSTMENTLOCAL],[WTAXTOTALAMOUNT],[WTAXTOTALAMOUNTLOCAL],[WVATTOTALAMOUNT],[WVATTOTALAMOUNTLOCAL],[REFERENCENO],[SALESPERSONID],[PROJECTID],[DESCRIPTION],[CURRENCYID],[CURRENCYRATE],[COSTCENTREID],[NOTES],[ISDETAILFORGLPOSTING],[TOTALAMOUNTLOCAL],[BALANCE],[DEPARTMENTID],[TAXTOTALAMOUNT],[TAXTOTALAMOUNTLOCAL],[SUBTOTALAMOUNT],[SUBTOTALAMOUNTLOCAL],[ISTAXINCLUSIVE],[TAXEXCLUSIVETOTALAMOUNT],[TAXEXCLUSIVETOTALAMOUNTLOCAL],[ROUNDINGADJUSTMENTACCOUNT],[ISROUNDING],[OPTIMISTICLOCKFIELD],[REVERSERATE],[ISESALES],[ISDETAILPOSTING],[RECEIPTCODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_ARCN] ON [CHUANSINCACTUS].[DBO].[ARCN] ([ROWINDEX],[ISCANCELLED],[CNDATE],[FROMDOCID]) INCLUDE ([DESCRIPTION],[REFERENCENO],[PROJECTID],[COSTCENTREID],[DEBTORID],[NETTOTALAMOUNTLOCAL],[ROUNDINGADJUSTMENT],[ROUNDINGADJUSTMENTLOCAL],[WTAXTOTALAMOUNT],[WTAXTOTALAMOUNTLOCAL],[CNCODE],[SALESPERSONID],[CURRENCYID],[CURRENCYRATE],[NOTES]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_TERMS] ON [CHUANSINCACTUS].[DBO].[TERMS] ([ID]) INCLUDE ([CREDITLIMIT]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_INVOICES] ON [CHUANSINCACTUS].[DBO].[INVOICES] ([ID],[LOCALONECENTSDIFF],[ROWINDEX]) INCLUDE ([INVOICE],[POS],[GLACCOUNT],[DESCRIPTION],[REFERENCENO],[PROJECT],[DEPARTMENT],[COSTCENTRE],[AMOUNT],[AMOUNTLOCAL],[NOTE],[ITEMTYPECODE],[TAXCODE],[ISTAXINCLUSIVE],[TAXRATE],[TAXCLASS],[TAXCLASSVALUE],[TAXAMOUNT],[TAXAMOUNTLOCAL],[NETAMOUNT],[NETAMOUNTLOCAL],[SUBAMOUNT],[SUBAMOUNTLOCAL],[TAXEXCLUSIVEAMOUNT],[TAXEXCLUSIVEAMOUNTLOCAL],[TAXCLASSVALUEREF],[OPTIMISTICLOCKFIELD],[WTAXCODE],[WTAXRATE],[WTAXAMOUNT],[WTAXAMOUNTLOCAL],[SGSTAMOUNT],[CGSTAMOUNT],[IGSTAMOUNT],[SGSTAMOUNTLOCAL],[CGSTAMOUNTLOCAL],[IGSTAMOUNTLOCAL],[TARIFFCODE],[SERVICEAMOUNT],[SERVICEAMOUNTLOCAL],[WVATCODE],[WVATRATE],[WVATAMOUNT],[WVATAMOUNTLOCAL],[ATCCODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_SPECIALACCOUNTS] ON [CHUANSINCACTUS].[DBO].[SPECIALACCOUNTS] ([ID],[ROWINDEX]) INCLUDE ([ACCOUNT],[SPECIALACCOUNTCODE],[DESCRIPTION],[ACCOUNTCODE],[OPTIMISTICLOCKFIELD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDOCUMENTID_DOCUMENTINFO] ON [CHUANSINCACTUS].[DBO].[DOCUMENTINFO] ([DOCUMENTID]) INCLUDE ([DOCTYPE],[FIRSTCREATEDDATE],[FIRSTCREATEDUSERID],[LASTMODIFIEDDATE],[LASTMODIFIEDUSERID],[PRINTCOUNT],[OPTIMISTICLOCKFIELD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
