

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230802113409 ON [CLUBON].[DBO].[INVITEM]; 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    DROP INDEX [IX_AIDBA_2_20220926] ON [FAS].[DBO].[GLTRANSACTION]; 
END TRY 
BEGIN CATCH 
END CATCH;

