
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/23/2023 11:25:02 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230823112505 ON [SPRITZERTAIPINGDB].[DBO].[TRUCK] ([CLASS_TYPE],[STATUS],[CREATE_DATE],[CONTAINER_NUMBER],[SHIPMENT_ID],[TASK_TYPE]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[CHECK_IN_DATE],[PRIORITY],[LOADING_TYPE],[VEHICLE_KEY],[APPOINTMENT_SLOT],[CHECK_OUT_DATE],[DOCK_NO],[DRIVER_ID],[DRIVER_NAME],[PHONE_NUMBER],[PURPOSE],[TRUCK_INSPECTION],[TRUCK_INSPECTION_COMMENT],[TRUCK_INSPECTION_FAILURE],[TRUCK_INSPECTION_RESULT],[TRUCK_LENGTH_45FT],[VEHICLE_NO],[TRUCK_INSPECTED_BY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230823112520 ON [SPRITZERTAIPINGDB].[DBO].[LOCATION] ([CLASS_TYPE],[WORK_ZONE_KEY],[STATUS],[SIS_ADDRESS],[ROLE],[TRANSPORT_NODE_ID],[LOCATION_ID],[LOCATION_KEY]) INCLUDE ([AVAILABLE_CAPACITY],[CHECK_DIGIT],[CREATE_DATE],[CREATED_BY],[HOST_LOCATION_ID],[LAST_CYCLE_COUNT_DATE],[LAST_ZERO_CROSS_CHECK_DATE],[LU_CONSOLIDATION_STRING],[LU_CONSOLIDATION_STRING_PREF],[NODE_DESTINATION_TYPE],[OCCUPATION_SEQUENCE],[OCCUPIED_CAPACITY],[RESERVED_CAPACITY],[ROLE_SEQUENCE],[SIDE_OF_AISLE],[STATUS_DATE],[STORAGE_PATH],[SYSTEM],[TRANSACTION_COUNT],[TU_CONSOLIDATION_STRING],[UPDATE_DATE],[UPDATED_BY],[WEIGHT],[WORK_PATH],[X_POSITION],[Y_POSITION],[Z_POSITION],[ALLOCATION_ZONE_KEY],[LOCATION_PROFILE_ID],[PARENT_LOCATION_KEY],[STORAGE_ZONE_KEY],[LANDSCAPE],[ORIENTATION],[WORKSTATION_ID],[WORKSTATION_LOCATION_DISPLAY],[OUTFEED_LOCATION_KEY],[STAGING_LOCATION],[MODULE],[RACK],[EQUIPMENT_KEY]) ;
 END TRY BEGIN CATCH END CATCH;
