
BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_62_61')
	BEGIN
	ALTER INDEX [Hitachi_62_61]
	ON [MIMS].[dbo].[PEDIDO_DEVO_VEND_ITEM_DETA] DISABLE;
	PRINT 'INDEX [Hitachi_62_61] ON [MIMS].[dbo].[PEDIDO_DEVO_VEND_ITEM_DETA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_62_61] ON [MIMS].[dbo].[PEDIDO_DEVO_VEND_ITEM_DETA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_45412_45411')
	BEGIN
	ALTER INDEX [Hitachi_45412_45411]
	ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [Hitachi_45412_45411] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_45412_45411] ON [MIMS].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00628')
	BEGIN
	ALTER INDEX [IDX_N00628]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00628] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00623')
	BEGIN
	ALTER INDEX [IDX_N00623]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_N00623] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00623] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_LASTMODDATE_TABEEXCLREPLSIST')
	BEGIN
	ALTER INDEX [IDX_LASTMODDATE_TABEEXCLREPLSIST]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [IDX_LASTMODDATE_TABEEXCLREPLSIST] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_LASTMODDATE_TABEEXCLREPLSIST] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_Hitachi_183_182_PmtsCondemnTrans')
	BEGIN
	ALTER INDEX [IX_Hitachi_183_182_PmtsCondemnTrans]
	ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] DISABLE;
	PRINT 'INDEX [IX_Hitachi_183_182_PmtsCondemnTrans] ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_Hitachi_183_182_PmtsCondemnTrans] ON [MTECH-EDATA].[mtech].[PmtsCondemnTrans] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'nc2MSmerge_sessions')
	BEGIN
	ALTER INDEX [nc2MSmerge_sessions]
	ON [distribution].[dbo].[MSmerge_sessions] DISABLE;
	PRINT 'INDEX [nc2MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [nc2MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'nc4MSmerge_sessions')
	BEGIN
	ALTER INDEX [nc4MSmerge_sessions]
	ON [distribution].[dbo].[MSmerge_sessions] DISABLE;
	PRINT 'INDEX [nc4MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [nc4MSmerge_sessions] ON [distribution].[dbo].[MSmerge_sessions] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N1046')
	BEGIN
	ALTER INDEX [IDX_N1046]
	ON [MIMS].[dbo].[EXPEDICAO_CARGA] DISABLE;
	PRINT 'INDEX [IDX_N1046] ON [MIMS].[dbo].[EXPEDICAO_CARGA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N1046] ON [MIMS].[dbo].[EXPEDICAO_CARGA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'nc1MSmerge_articlehistory')
	BEGIN
	ALTER INDEX [nc1MSmerge_articlehistory]
	ON [distribution].[dbo].[MSmerge_articlehistory] DISABLE;
	PRINT 'INDEX [nc1MSmerge_articlehistory] ON [distribution].[dbo].[MSmerge_articlehistory] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [nc1MSmerge_articlehistory] ON [distribution].[dbo].[MSmerge_articlehistory] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_ORDEPESA_INTE')
	BEGIN
	ALTER INDEX [IDX_ORDEPESA_INTE]
	ON [MIMS].[dbo].[PESAGEM_ORDEM] DISABLE;
	PRINT 'INDEX [IDX_ORDEPESA_INTE] ON [MIMS].[dbo].[PESAGEM_ORDEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_ORDEPESA_INTE] ON [MIMS].[dbo].[PESAGEM_ORDEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_PROD_BALA')
	BEGIN
	ALTER INDEX [IDX_PROD_BALA]
	ON [MIMS].[dbo].[PRODUCAO_BALANCA] DISABLE;
	PRINT 'INDEX [IDX_PROD_BALA] ON [MIMS].[dbo].[PRODUCAO_BALANCA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PROD_BALA] ON [MIMS].[dbo].[PRODUCAO_BALANCA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00914')
	BEGIN
	ALTER INDEX [IDX_N00914]
	ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] DISABLE;
	PRINT 'INDEX [IDX_N00914] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00914] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'UNQ_SCT_DIREITOS_US_JANE_ROWID')
	BEGIN
	ALTER INDEX [UNQ_SCT_DIREITOS_US_JANE_ROWID]
	ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] DISABLE;
	PRINT 'INDEX [UNQ_SCT_DIREITOS_US_JANE_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_SCT_DIREITOS_US_JANE_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US_JANE] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'UNQ_DIREITOS_US_ROWID')
	BEGIN
	ALTER INDEX [UNQ_DIREITOS_US_ROWID]
	ON [MIMS].[dbo].[SCT_DIREITOS_US] DISABLE;
	PRINT 'INDEX [UNQ_DIREITOS_US_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_DIREITOS_US_ROWID] ON [MIMS].[dbo].[SCT_DIREITOS_US] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00913')
	BEGIN
	ALTER INDEX [IDX_N00913]
	ON [MIMS].[dbo].[SCT_DIREITOS_US] DISABLE;
	PRINT 'INDEX [IDX_N00913] ON [MIMS].[dbo].[SCT_DIREITOS_US] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00913] ON [MIMS].[dbo].[SCT_DIREITOS_US] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL')
	BEGIN
	ALTER INDEX [IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL]
	ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] DISABLE;
	PRINT 'INDEX [IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL] ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_MATERIAL_EMBALAGEM_MATE_PRIM_FILIAL] ON [MIMS].[dbo].[MATERIAL_EMBALAGEM_MATE_PRIM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'UNQ_PRODBALAPROD_ROWID')
	BEGIN
	ALTER INDEX [UNQ_PRODBALAPROD_ROWID]
	ON [MIMS].[dbo].[PRODUCAO_BALANCA_PRODUTO] DISABLE;
	PRINT 'INDEX [UNQ_PRODBALAPROD_ROWID] ON [MIMS].[dbo].[PRODUCAO_BALANCA_PRODUTO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_PRODBALAPROD_ROWID] ON [MIMS].[dbo].[PRODUCAO_BALANCA_PRODUTO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'UNQ_ENDEPESS_ROWID')
	BEGIN
	ALTER INDEX [UNQ_ENDEPESS_ROWID]
	ON [MIMS].[dbo].[PESSOA_ENDERECO] DISABLE;
	PRINT 'INDEX [UNQ_ENDEPESS_ROWID] ON [MIMS].[dbo].[PESSOA_ENDERECO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [UNQ_ENDEPESS_ROWID] ON [MIMS].[dbo].[PESSOA_ENDERECO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_CREDCLIE_CLIENTE')
	BEGIN
	ALTER INDEX [IDX_CREDCLIE_CLIENTE]
	ON [MIMS].[dbo].[CLIENTE_CREDITO] DISABLE;
	PRINT 'INDEX [IDX_CREDCLIE_CLIENTE] ON [MIMS].[dbo].[CLIENTE_CREDITO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_CREDCLIE_CLIENTE] ON [MIMS].[dbo].[CLIENTE_CREDITO] CANNOT BE DISABLED.';
END CATCH;
