

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230822105019 ON [MIMS].[DBO].[CRIACAO_LOTE_INTEGRACAO_GALPAO]; 
END TRY 
BEGIN CATCH 
END CATCH;




BEGIN TRY 
    CREATE UNIQUE INDEX [IDX_FILICLIE] ON [MIMS].[DBO].[CLIENTE_FILIAL] ([FILIAL],[ID_CLIENTE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;




BEGIN TRY 
    CREATE  INDEX [IX_INTERFACE_PEDIDO_VENDA_ITEM_IE_ITEMPEDIVEND] ON [INTERM].[DBO].[INTERFACE_PEDIDO_VENDA_ITEM] ([IE_ITEMPEDIVEND]) INCLUDE ([IE_FILISIST],[IE_MATEEMBA],[NR_LINHITEMPEDIVEND],[QN_EXPEUMERPITEMPEDIVEND],[QN_EXPEUMTRANITEMPEDIVEND],[QN_PESOEXPEITEMPEDIVEND],[SG_UNIDMEDIERPITEMPEDIVEND],[SG_UNIDMEDITRANITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PEDIDO_VENDA_ITEM_DETALHE_ID_ITEMPEDIVEND] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_EXCEGRUPPROD] ON [MIMS].[DBO].[PRODUCAO_GRUPO_EXCECAO] ([ID_EXCEGRUPPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [HITACHI_45509_45508] ON [MIMS].[DBO].[PRODUCAO_DESCARTE] ([ID_ENTRAVEVIVA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_MATEEMBA_06] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([ID_DEFIMATEEMBA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX [IX_AIDBA_1_20220131] ON [MIMS].[DBO].[PEDIDO_DEVO_VEND_ITEM_DETA]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_ITEMPEDIDEVOVEND_004] ON [MIMS].[DBO].[PEDIDO_DEVOLUCAO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIDEVOVEND],[QN_EMBAITEMPEDIDEVOVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;