
BEGIN TRY
	DROP INDEX [IX_AIDBA_1_20221009]
	ON [FAS].[dbo].[GlJournalHeader];
	PRINT 'INDEX [IX_AIDBA_1_20221009] ON [FAS].[dbo].[GlJournalHeader] IS DROPED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_AIDBA_1_20221009] ON [FAS].[dbo].[GlJournalHeader] CANNOT BE DROPED.';
END CATCH;

BEGIN TRY
	DROP INDEX [IX_AIDBA_1_20221226]
	ON [FAS].[dbo].[GlJournalHeader];
	PRINT 'INDEX [IX_AIDBA_1_20221226] ON [FAS].[dbo].[GlJournalHeader] IS DROPED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_AIDBA_1_20221226] ON [FAS].[dbo].[GlJournalHeader] CANNOT BE DROPED.';
END CATCH;

BEGIN TRY
	DROP INDEX [IX_AIDBA_1_20230103]
	ON [ClubOn].[dbo].[mrmSalesMaster];
	PRINT 'INDEX [IX_AIDBA_1_20230103] ON [ClubOn].[dbo].[mrmSalesMaster] IS DROPED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_AIDBA_1_20230103] ON [ClubOn].[dbo].[mrmSalesMaster] CANNOT BE DROPED.';
END CATCH;

BEGIN TRY
	DROP INDEX [IX_AIDBA_3_20230309]
	ON [ClubOn].[dbo].[RetTransactionMaster];
	PRINT 'INDEX [IX_AIDBA_3_20230309] ON [ClubOn].[dbo].[RetTransactionMaster] IS DROPED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_AIDBA_3_20230309] ON [ClubOn].[dbo].[RetTransactionMaster] CANNOT BE DROPED.';
END CATCH;
