
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/23/2023 1:18:41 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230523011843 ON [SPRITZERTAIPINGDB].[DBO].[AUDIT_TRAIL_PARAM] ([CLASS_TYPE],[UPDATED_BY],[CREATED_BY],[CREATE_DATE],[AUDIT_PARAM_VALUE],[AUDIT_PARAM_TYPE],[AUDIT_PARAM_LABEL]) INCLUDE ([TRANSACTION_COUNT],[UPDATE_DATE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230523011855 ON [SPRITZERTAIPINGDB].[DBO].[HOST_MESSAGE] ([HOST_MESSAGE_KEY],[CLASS_TYPE]) ;
 END TRY BEGIN CATCH END CATCH;
