




BEGIN TRY 
    CREATE UNIQUE INDEX [IX_SLIST_UNIQUE] ON [COLOS].[DBO].[SLIST] ([INTVALUE],[STRLISTNAME]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX [IX_AIDBA_23_20220830] ON [OCS].[DBO].[A_WILORRYUNLOADINGTRANSACTION]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX [IX_AIDBA_4_20220830] ON [OCS].[DBO].[AB_A_LOADINGAPPOINTMENTTIMETRANSACTION_CSSA]; 
END TRY 
BEGIN CATCH 
END CATCH;
