
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/18/2023 6:08:03 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230518060806 ON [PDSNT].[DBO].[AQS_TRAJECT_DEFINITION] ([ASP_DEVICE_ID]) INCLUDE ([MODIFIED],[AQS_QUALITY_MATRIX_ID]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROC_ORDERL] ON [INNOVA].[DBO].[PROC_ORDERL] ([ID],[MATERIAL],[PRUNIT]) INCLUDE ([EXTCODE],[MAXAMOUNT],[CURAMOUNT],[AMOUNTUM],[CURNOMINAL],[EXPIRE1],[EXPIRE2],[EXPIRE3],[VALUE],[CURRENCY],[PRICE],[DPRICE],[ORDER],[PRDAY]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROC_LOTS_CODE] ON [INNOVA].[DBO].[PROC_LOTS] ([CODE],[DIMENSION1]) INCLUDE ([PROCESSOR],[NAME],[SHNAME],[EXT],[PATTERN],[DIMENSION2],[DIMENSION3],[DIMENSION4],[DESCRIPTION1],[DESCRIPTION2],[DESCRIPTION3],[DESCRIPTION4],[DESCRIPTION5],[DESCRIPTION6],[DESCRIPTION7],[DESCRIPTION8],[XMLDATA],[OBJECTTEMPLATE],[ITGRSITE],[ITGRSTATUS],[CREATED],[CREATEDBY],[MODIFIED],[MODIFIEDBY],[ACTIVE],[LOTSTATUS],[VALIDFROM],[VALIDTO],[BRCOUNTRY],[RICOUNTRY],[RICOUNTRY2],[RICOUNTRY3],[RICOUNTRY4],[RICOUNTRY5],[SLHOUSE],[SLSEQUENCE],[PROCESSOR2],[CUSTOMER],[BOM],[REFTIME],[EXPECTEDCOUNT],[CURRENTCOUNT],[QAMARK1],[QAMARK2],[QAMARK3],[QAMARK4],[STARTPOS],[ENDPOS],[STARTRMAREA],[ENDRMAREA],[GROUP],[SUBGROUP],[KILLMETHOD],[BEGTIME],[ENDTIME],[SOURCEPACK],[SOURCEPALLET],[LOTTYPE],[SUPPLIER]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_DEVICES] ON [PDSNT].[DBO].[DEVICES] ([ID],[MODULE_ID],[QUA]) INCLUDE ([FLOCK],[INPUT_ARTC],[OUTPUT_ARTC],[NUMBER],[WEIGHT]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROC_ORDERSERVICEPROCESSES_ORDERPROCESS_ORDERPROCESSTYPE] ON [INNOVA].[DBO].[PROC_ORDERSERVICEPROCESSES] ([ORDERPROCESS],[ORDERPROCESSTYPE],[ID]) INCLUDE ([PROCESSASSEMBLY],[XMLDATA],[ACTIVE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_PROC_UNITMATERIALC_UNITID_UNITTYPE] ON [INNOVA].[DBO].[PROC_UNITMATERIALC] ([UNITID],[UNITTYPE]) INCLUDE ([MATERIALC]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROC_HISTOGRAMS] ON [INNOVA].[DBO].[PROC_HISTOGRAMS] ([ID],[EXTNUM],[PRPERIOD],[DEVICE],[CHECKSTATUS],[SHIFT],[PO],[PLOT],[RMAREA],[BATCH],[RANGEFROM],[RANGETO]) INCLUDE ([PRDAY],[WEIGHT],[WEIGHTSQR],[UNITS],[WEIGHTUNIT],[REGTIME],[MODTIME],[UNITTYPE],[RSTAT],[CHANGE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PROC_ITEMS] ON [INNOVA].[DBO].[PROC_ITEMS] ([ID],[CHECKSTATUS],[LOT],[SHIFT],[ORIGIN],[EMPLOYEE],[PLOT],[RMAREA],[EXTNUM]) INCLUDE ([SITE],[NUMBER],[BASEITEM],[PARENTITEM],[INDIVUAL],[EXTCODE],[EXTBATCHCODE],[PRODUCTNUM],[PROCESSNUM],[POLINE],[CDAY],[PRDAY],[EXDAY],[EXDAY2],[PACKER],[INVKEEPMIN],[INVKEEPMAX],[EXPIRE1],[EXPIRE2],[EXPIRE3],[ORDER],[ORDERLINE],[PORDER],[PORDERLINE],[INVENTORY],[INVLOCATION],[INVSTATUS],[CONTAINER],[SHIPMENT],[RECORDINGMATERIAL],[PACKAGING],[YIELDGROUP],[CLASSIFICATION],[LAYOUT],[NOMINALL],[NOMINALU],[GROSS],[TARE],[TARETYPE],[VGIVEAWAY],[FGIVEAWAY],[FAT],[VALUE],[CURRENCY],[PRICE],[BASISPRICE],[DPRICE],[BASISDPRICE],[PIECES],[PIECESL],[TALLYPOINTS],[PACK],[NREGS],[REGTIME],[ALIBI],[QAMARK],[RSTAT],[RECORDEDBY],[OWEIGHT],[SECTIONTYPE],[PRUNIT],[SLDAY],[TAREDEVICE],[TAREALIBI]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_BASE_FEATURES_NAME] ON [INNOVA].[DBO].[BASE_FEATURES] ([NAME],[ID]) INCLUDE ([MAXINSTANCES],[SIGNATURE],[MAXINSTANCESUSED]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
