
USE [MFMB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230822 ON [MFMB].[dbo].[DppCondemnTrans];
		PRINT N'INDEX IX_AIDBA_1_20230822 ON [MFMB].[dbo].[DppCondemnTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230822 ON [MFMB].[dbo].[DppCondemnTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimHatchTrans];
		PRINT N'INDEX IX_AIDBA_2_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimHatchTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimHatchTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggHatcherReceiving];
		PRINT N'INDEX IX_AIDBA_3_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggHatcherReceiving] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggHatcherReceiving] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHRecv];
		PRINT N'INDEX IX_AIDBA_4_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHRecv] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHRecv] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomUsage];
		PRINT N'INDEX IX_AIDBA_5_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomUsage] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomUsage] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_6_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_6_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggTransfers];
		PRINT N'INDEX IX_AIDBA_6_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggTransfers] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_6_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_6_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggTransfers] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_7_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_7_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[FmimFeedTrans];
		PRINT N'INDEX IX_AIDBA_7_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[FmimFeedTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_7_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_7_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[FmimFeedTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_8_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_8_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimHenDaysInv];
		PRINT N'INDEX IX_AIDBA_8_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimHenDaysInv] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_8_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_8_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimHenDaysInv] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_9_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_9_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHUsage];
		PRINT N'INDEX IX_AIDBA_9_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHUsage] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_9_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_9_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHUsage] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_10_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_10_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimEntityInventory];
		PRINT N'INDEX IX_AIDBA_10_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimEntityInventory] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_10_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_10_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimEntityInventory] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_11_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_11_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggSetReceiving];
		PRINT N'INDEX IX_AIDBA_11_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggSetReceiving] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_11_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_11_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggSetReceiving] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_12_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_12_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ReportLayoutUsages];
		PRINT N'INDEX IX_AIDBA_12_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ReportLayoutUsages] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_12_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_12_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ReportLayoutUsages] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_13_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_13_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomReceiving];
		PRINT N'INDEX IX_AIDBA_13_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomReceiving] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_13_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_13_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomReceiving] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_14_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_14_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersInvoice];
		PRINT N'INDEX IX_AIDBA_14_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersInvoice] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_14_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_14_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersInvoice] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_15_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_15_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimChickTrans];
		PRINT N'INDEX IX_AIDBA_15_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimChickTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_15_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_15_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimChickTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_16_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_16_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersShipment];
		PRINT N'INDEX IX_AIDBA_16_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersShipment] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_16_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_16_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersShipment] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_17_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_17_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinJournalTrans];
		PRINT N'INDEX IX_AIDBA_17_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinJournalTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_17_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_17_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinJournalTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_18_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_18_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomInventory];
		PRINT N'INDEX IX_AIDBA_18_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomInventory] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_18_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_18_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggRoomInventory] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_19_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_19_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimChickInventoryRecv];
		PRINT N'INDEX IX_AIDBA_19_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimChickInventoryRecv] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_19_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_19_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimChickInventoryRecv] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_20_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_20_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[zBrimAdjustments];
		PRINT N'INDEX IX_AIDBA_20_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[zBrimAdjustments] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_20_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_20_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[zBrimAdjustments] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_21_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_21_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrders];
		PRINT N'INDEX IX_AIDBA_21_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrders] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_21_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_21_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrders] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_22_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_22_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinWHTransfer];
		PRINT N'INDEX IX_AIDBA_22_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinWHTransfer] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_22_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_22_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinWHTransfer] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_23_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_23_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersShipmentLineItems];
		PRINT N'INDEX IX_AIDBA_23_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersShipmentLineItems] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_23_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_23_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersShipmentLineItems] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_24_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_24_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggSetUsage];
		PRINT N'INDEX IX_AIDBA_24_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggSetUsage] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_24_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_24_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggSetUsage] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_25_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_25_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[PmtsProcRecvTrans];
		PRINT N'INDEX IX_AIDBA_25_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[PmtsProcRecvTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_25_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_25_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[PmtsProcRecvTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_26_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_26_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOInvoices];
		PRINT N'INDEX IX_AIDBA_26_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOInvoices] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_26_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_26_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOInvoices] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_27_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_27_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[xBpaDailyDetailProjections];
		PRINT N'INDEX IX_AIDBA_27_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[xBpaDailyDetailProjections] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_27_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_27_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[xBpaDailyDetailProjections] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_28_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_28_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[PmtsTransferSources];
		PRINT N'INDEX IX_AIDBA_28_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[PmtsTransferSources] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_28_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_28_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[PmtsTransferSources] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_29_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_29_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersLineItems];
		PRINT N'INDEX IX_AIDBA_29_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersLineItems] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_29_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_29_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersLineItems] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_30_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_30_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHPurchases];
		PRINT N'INDEX IX_AIDBA_30_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHPurchases] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_30_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_30_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductWHPurchases] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_31_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_31_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMPriceMasterDates];
		PRINT N'INDEX IX_AIDBA_31_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMPriceMasterDates] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_31_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_31_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMPriceMasterDates] CANNOT BE DROPPED.';
END CATCH;

USE [MFMB];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_32_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_32_20230822 ON [MFMB].[dbo].[EskerIDB];
		PRINT N'INDEX IX_AIDBA_32_20230822 ON [MFMB].[dbo].[EskerIDB] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_32_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_32_20230822 ON [MFMB].[dbo].[EskerIDB] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_33_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_33_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersInvoiceLineItems];
		PRINT N'INDEX IX_AIDBA_33_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersInvoiceLineItems] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_33_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_33_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMOrdersInvoiceLineItems] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_34_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_34_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrimFieldTrans];
		PRINT N'INDEX IX_AIDBA_34_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrimFieldTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_34_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_34_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrimFieldTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_V7_Intermediate_PROD];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_35_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_35_20230822 ON [MTECH_V7_Intermediate_PROD].[mtech].[xProteinInterfaceData];
		PRINT N'INDEX IX_AIDBA_35_20230822 ON [MTECH_V7_Intermediate_PROD].[mtech].[xProteinInterfaceData] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_35_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_35_20230822 ON [MTECH_V7_Intermediate_PROD].[mtech].[xProteinInterfaceData] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_36_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_36_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggTransfersDetails];
		PRINT N'INDEX IX_AIDBA_36_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggTransfersDetails] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_36_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_36_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[HimEggTransfersDetails] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_37_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_37_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOLineItems];
		PRINT N'INDEX IX_AIDBA_37_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOLineItems] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_37_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_37_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOLineItems] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_38_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_38_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinEntities];
		PRINT N'INDEX IX_AIDBA_38_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinEntities] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_38_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_38_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinEntities] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_39_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_39_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaProjectedFarms];
		PRINT N'INDEX IX_AIDBA_39_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaProjectedFarms] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_39_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_39_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaProjectedFarms] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_40_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_40_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsRequisitionTrans];
		PRINT N'INDEX IX_AIDBA_40_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsRequisitionTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_40_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_40_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsRequisitionTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_41_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_41_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaProjectedSchedules];
		PRINT N'INDEX IX_AIDBA_41_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaProjectedSchedules] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_41_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_41_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaProjectedSchedules] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_42_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_42_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPO];
		PRINT N'INDEX IX_AIDBA_42_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPO] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_42_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_42_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPO] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_43_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_43_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimFieldTrans];
		PRINT N'INDEX IX_AIDBA_43_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimFieldTrans] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_43_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_43_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BimFieldTrans] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_44_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_44_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinAdminPurchases];
		PRINT N'INDEX IX_AIDBA_44_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinAdminPurchases] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_44_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_44_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinAdminPurchases] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_45_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_45_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaTargets];
		PRINT N'INDEX IX_AIDBA_45_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaTargets] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_45_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_45_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaTargets] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_46_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_46_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMCustomers];
		PRINT N'INDEX IX_AIDBA_46_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMCustomers] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_46_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_46_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[OMCustomers] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_47_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_47_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsVendors];
		PRINT N'INDEX IX_AIDBA_47_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsVendors] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_47_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_47_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsVendors] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_48_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_48_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinFarms];
		PRINT N'INDEX IX_AIDBA_48_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinFarms] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_48_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_48_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinFarms] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_49_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_49_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsField];
		PRINT N'INDEX IX_AIDBA_49_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsField] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_49_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_49_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProductsField] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_50_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_50_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaPlacementSchedules];
		PRINT N'INDEX IX_AIDBA_50_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaPlacementSchedules] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_50_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_50_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[BrpaPlacementSchedules] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_51_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_51_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProducts];
		PRINT N'INDEX IX_AIDBA_51_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProducts] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_51_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_51_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinProducts] CANNOT BE DROPPED.';
END CATCH;

USE [MTECH_v7_PRODUCTION];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_52_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_52_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOLineItemsAddOns];
		PRINT N'INDEX IX_AIDBA_52_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOLineItemsAddOns] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_52_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_52_20230822 ON [MTECH_v7_PRODUCTION].[mtech].[ProteinPOLineItemsAddOns] CANNOT BE DROPPED.';
END CATCH;
