
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 7/24/2023 9:18:59 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230724091903 ON [SPRITZERTAIPINGDWH].[DBO].[DWH_ORDERSBY_STATUS] ([TIMESTAMP],[ORDER_COUNT]) INCLUDE ([ORDER_STATUS],[ORDER_TYPE]) ;
 END TRY BEGIN CATCH END CATCH;
