
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/9/2023 12:55:59 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809125601 ON [CLUBON].[DBO].[INVITEM] ([ID],[BARCODE]) INCLUDE ([REMARKS],[DESCRIPTION],[LASTQTY]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_3_20220926] ON [FAS].[DBO].[GLJOURNALHEADER] ([BRANCHCODE],[COMPANYCODE],[DEBTORCODE],[DOCUMENTTYPE],[ISCANCEL],[MODULETYPE],[REFNO],[REMARK]) INCLUDE ([DOCUMENTNO],[TXNDATE],[RECEIPTNO],[LOCALAMOUNT],[CHEQUENO]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
