

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230809125601 ON [CLUBON].[DBO].[INVITEM]; 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    DROP INDEX [IX_AIDBA_3_20220926] ON [FAS].[DBO].[GLJOURNALHEADER]; 
END TRY 
BEGIN CATCH 
END CATCH;


