

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230820094814 ON [CHUANSINCACTUS].[DBO].[REPORTFILES]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230820094816 ON [CHUANSINCACTUS].[DBO].[JOURNALS]; 
END TRY 
BEGIN CATCH 
END CATCH;










BEGIN TRY 
    CREATE UNIQUE INDEX [PK_GLACCOUNTS] ON [CHUANSINCACTUS].[DBO].[GLACCOUNTS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_STOCKS] ON [CHUANSINCACTUS].[DBO].[STOCKS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_STOCKCATEGORIES] ON [CHUANSINCACTUS].[DBO].[STOCKCATEGORIES] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [ISTOCKID_UOMS] ON [CHUANSINCACTUS].[DBO].[UOMS] ([STOCKID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_STOCKACCOUNTPRESETS] ON [CHUANSINCACTUS].[DBO].[STOCKACCOUNTPRESETS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_SPECIALACCOUNTS] ON [CHUANSINCACTUS].[DBO].[SPECIALACCOUNTS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_STOCKLOCATIONS] ON [CHUANSINCACTUS].[DBO].[STOCKLOCATIONS] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [ISALESCNID_SALESCNDETAILS] ON [CHUANSINCACTUS].[DBO].[SALESCNDETAILS] ([SALESCNID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IGLTRANSACTIONID_BANKRECONCILIATION] ON [CHUANSINCACTUS].[DBO].[BANKRECONCILIATION] ([GLTRANSACTIONID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDOCUMENTID_DOCUMENTINFO] ON [CHUANSINCACTUS].[DBO].[DOCUMENTINFO] ([DOCUMENTID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;