
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/19/2023 12:23:13 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230519002316 ON [SPRITZERTAIPINGDB].[DBO].[EVENTLOG] ([EVENT_KEY],[CLASS_TYPE],[ORIGIN_CATEGORY],[SEVERITY]) INCLUDE ([MESSAGE],[OCCURRENCE_COUNT],[OCCURRENCE_DATE],[TRANSLATED_MESSAGE]) ;
 END TRY BEGIN CATCH END CATCH;
