
ALTER DATABASE [tempdb] ADD FILE (NAME=N'temp3', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_3.ndf' ,SIZE=8MB TO FILEGROUP [PRIMARY]
			
ALTER DATABASE [tempdb] ADD FILE (NAME=N'temp4', FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_4.ndf' ,SIZE=8MB TO FILEGROUP [PRIMARY]
			