
ALTER DATABASE [tempdb] MODIFY FILE (NAME=N'tempdev',SIZE=474112KB , FILEGROWTH=524288KB)

ALTER DATABASE [tempdb] MODIFY FILE (NAME=N'temp2',SIZE=474112KB , FILEGROWTH=524288KB)

DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC FREESESSIONCACHE;
DBCC FREESYSTEMCACHE ( 'ALL');
USE [tempdb];
DBCC SHRINKFILE (N'temp3', EMPTYFILE);
ALTER DATABASE [tempdb] REMOVE FILE [temp3];

DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC FREESESSIONCACHE;
DBCC FREESYSTEMCACHE ( 'ALL');
USE [tempdb];
DBCC SHRINKFILE (N'temp4', EMPTYFILE);
ALTER DATABASE [tempdb] REMOVE FILE [temp4];

			ALTER DATABASE tempdb MODIFY FILE (NAME=N'templog', SIZE=1048576KB , FILEGROWTH=1048576KB)
			