

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230523010949 ON [E101TEST].[ICE].[NOTIFICATION]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [FARD_IX_1030] ON [SWISSLOG].[DBO].[FSW_TBLSWISSREQUEST] ([TYPENAME]) INCLUDE ([COMPANY],[EXCEPTIONERR],[KEYVALUE],[REQUESTDATE],[REQUESTID],[RESCODE],[RESDATE],[RESDESC],[RESTRANSCODE],[SERVICETYPE],[SUBTYPE],[TYPEOFACTION],[XMLREQUEST],[XMLRESPONSE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230523011006 ON [E101TEST].[ERP].[SHIPHEAD]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PART_SYSINDEX] ON [E101TEST].[ERP].[PART] ([SYSROWID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;