
BEGIN TRY
ALTER DATABASE [ITEH] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[ITEH] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [ITEH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[ITEH] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [ITEH] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[ITEH] PARAMETERIZATION is SIMPLE.';
USE [ITEH];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[ITEH] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [ITEH];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[ITEH] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ITEH] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;