
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [ITEH] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[ITEH] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [ITEH] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[ITEH] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [ITEH] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[ITEH] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: ON
USE [ITEH];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[ITEH] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [ITEH];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[ITEH] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ITEH] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;