

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230620023354 ON [SPRITZERTAIPINGDB].[DBO].[POWER_CONSUMPTION]; 
END TRY 
BEGIN CATCH 
END CATCH;

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230620023356 ON [SPRITZERTAIPINGDB].[DBO].[ASN_LINE]; 
END TRY 
BEGIN CATCH 
END CATCH;





