
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/19/2023 12:31:24 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230519003126 ON [OCS].[DBO].[CCZA_LOADINGAPPOINTMENTTIME_LINKAGE_AGT] ([LAT_ROWID],[T1_TABLENAME]) INCLUDE ([T1_ROWID]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230519003129 ON [VEEAMONE].[MONITOR].[BPEXTERNALPLATFORM] ([ID],[UID],[BP_SERVER_ID],[DELETE_TIME],[PLATFORM_ID],[PLATFORM_TASK],[DISPLAY_NAME]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDX_OBJECTPROPERTY_RELATIONS] ON [VEEAMONE].[REPORTER].[OBJECTPROPERTY] ([ISDELETED],[OBJECTID],[PARENTID],[PROPERTYID],[MODIFICATIONID]) INCLUDE ([PROPKEY],[VALUE],[INTVALUE],[DATETIMEVALUE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_LATESTOBJECTPROPERTY_PROPERTYID] ON [VEEAMONE].[REPORTER].[LATESTOBJECTPROPERTY] ([PROPERTYID],[OBJECTTYPEID]) INCLUDE ([VALUE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_ENTITYID] ON [VEEAMONE].[REPORTING].[OBJECTENTITYRELATIONS] ([ENDDATE],[ENTITYID],[ENTITYPARENTID],[STARTDATE]) INCLUDE ([ENTITYPARENTTYPEID],[ENTITYPROPERTYTYPEID],[ENTITYTYPEID],[ISDELETED]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_BPJOBSESSION] ON [VEEAMONE].[MONITOR].[BPJOBSESSION] ([BP_SERVER_ID],[UID]) INCLUDE ([DURATION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_SESSIONLOG] ON [VEEAMONE].[REPORTER].[SESSIONLOG] ([SESSIONID]) INCLUDE ([DETAILS],[LOGDATETIME]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_SLIST_UNIQUE] ON [COLOS].[DBO].[SLIST] ([INTVALUE],[STRLISTNAME]) INCLUDE ([STRDESCRIPTION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
