

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230604124403 ON [SPRITZERTAIPINGDB].[DBO].[TARGET_BUFFER_RESERVATION]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230604124407 ON [SPRITZERTAIPINGDB].[DBO].[CONFIGURATION_VALUE]; 
END TRY 
BEGIN CATCH 
END CATCH;






