
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/24/2023 5:38:14 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230824053912 ON [CHUANSINCACTUS].[DBO].[BANKACCOUNTSETTINGS] ([ID],[GLACCOUNTID]) INCLUDE ([OPTIMISTICLOCKFIELD],[OVERDRAFTLIMIT],[BANKCHARGESACCOUNTID],[USEOWNOR],[USEOWNPV],[USECHEQUEAUTONO],[ISCHEQUEALLOWEDIT],[FORMATORID],[FORMATPVID],[CHEQUEFORMATID],[FORMATOR],[NEXTNUMBEROR],[ISRESETMONTHLYRUNNINGOR],[ISRESETPERPROJECTRUNNINGOR],[FORMATPV],[NEXTNUMBERPV],[ISRESETMONTHLYRUNNINGPV],[ISRESETPERPROJECTRUNNINGPV],[CHEQUEPREFIX],[CHEQUENEXTNO],[BANKCHARGES]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_RECEIPTS] ON [CHUANSINCACTUS].[DBO].[RECEIPTS] ([ID],[ROWINDEX],[COMPANYCODE],[ISGROUPCOMPANY],[GLACCOUNTID]) INCLUDE ([SALESPERSON],[TERM],[COMPANYNAME2],[CONTROLACCOUNT],[REGISTRATIONNO],[ADDRESS1],[ADDRESS2],[ADDRESS3],[ADDRESS4],[CONTACTPERSON],[PHONENO1],[PHONENO2],[FAXNO1],[FAXNO2],[BUSINESSNATURE],[CATEGORY],[AREA],[CURRENCY],[STATEMENTCYCLE],[GROUPCOMPANY],[BRANCHCODE],[BUSINESSSTYLE],[EMAIL],[HOMEPAGE],[BILLINGCYCLE],[BILLINGCONTACTPERSON],[BILLINGCONTACTPHONE],[BILLINGCONTACTEMAIL],[ACCOUNTCONTACTPERSON],[ACCOUNTCONTACTPHONE],[ACCOUNTCONTACTEMAIL],[MANAGEMENTCONTACTPERSON],[MANAGEMENTCONTACTPHONE],[MANAGEMENTCONTACTEMAIL],[GUARANTORNAME],[GUARANTORNO],[GUARANTORGENDER],[GUARANTORRACE],[GUARANTORCITIZENSHIP],[CURRENTBALANCE],[SALESTAXEXEMPTIONNO],[PRICEGROUP],[STARTDATE],[SOURCEOFLEAD],[MEMBERNAME],[MEMBEROCCUPATION],[MEMBERSINCE],[MEMBERNO],[MEMBERBIRTHDAY],[MEMBEREMAIL],[MEMBERMOBILENO],[MEMBERRACE],[MEMBERRELIGION],[MEMBERVALTHRU],[GSTREGNO],[DEFAULTTAXCODE],[NOTES],[OPTIMISTICLOCKFIELD],[BIRCLASSIFICATION],[GSTREGTAG],[DEFAULTWTAXCODE],[STATE],[POSTINGACCOUNTGROUP],[USELOCALCREDITCONTROL],[EXCLUDESOCREDITCONTROL],[EXCLUDEDOCREDITCONTROL],[SALESTAXREGNO],[SERVICETAXREGNO],[SALESTAXEXEMPTIONEXPDATE],[ISDEFERREDVAT],[ZIPCODE],[GROUP],[DEFAULTWVATCODE],[POINTCATEGORY],[POINTSTATUS],[POINTEXPIRYDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_RECEIPTS] ON [CHUANSINCACTUS].[DBO].[RECEIPTS] ([ROWINDEX],[ISCANCELLED],[FROMDOCID],[DEBTORID],[OBJECTTYPE],[DNDATE]) INCLUDE ([TERMID],[DUEDATE],[SALESPERSONID],[NETTOTALAMOUNTLOCAL],[ROUNDINGADJUSTMENT],[ROUNDINGADJUSTMENTLOCAL],[WTAXTOTALAMOUNT],[WTAXTOTALAMOUNTLOCAL],[PROJECTID],[REFERENCENO],[DESCRIPTION],[CURRENCYRATE],[COSTCENTREID],[CURRENCYID],[NOTES],[ISDETAILFORGLPOSTING],[TOTALAMOUNTLOCAL],[DEPARTMENTID],[FROMDOCTYPE],[TAXTOTALAMOUNT],[TAXTOTALAMOUNTLOCAL],[SUBTOTALAMOUNT],[SUBTOTALAMOUNTLOCAL],[EXPORTCOUNTRY],[ISTAXINCLUSIVE],[TAXDATE],[TAXEXCLUSIVETOTALAMOUNT],[TAXEXCLUSIVETOTALAMOUNTLOCAL],[ROUNDINGADJUSTMENTACCOUNT],[ISROUNDING],[OPTIMISTICLOCKFIELD],[SGSTTOTALAMOUNT],[SGSTTOTALAMOUNTLOCAL],[CGSTTOTALAMOUNT],[CGSTTOTALAMOUNTLOCAL],[IGSTTOTALAMOUNT],[IGSTTOTALAMOUNTLOCAL],[ISDEFERREDVAT],[DOCTAXCODEID],[DOCTAXRATE],[REVERSERATE],[ISNONTAXINVOICE],[ISSSTBADDEBT],[FORECASTDUEDATE],[TOTALSERVICEAMOUNT],[TOTALSERVICEAMOUNTLOCAL],[ISSELFBEARWTAX],[ISESALES],[ISDETAILPOSTING],[DNCODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230824053917 ON [CHUANSINCACTUS].[DBO].[ROLEROLES_ROLEMODELDIFFERENCEOBJECTROLEMODELDIFFERENCEOBJECTS] ([OID],[ROLES]) INCLUDE ([OPTIMISTICLOCKFIELD]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_ARCN] ON [CHUANSINCACTUS].[DBO].[ARCN] ([ROWINDEX]) INCLUDE ([PROJECTID],[REFERENCENO],[DESCRIPTION],[COSTCENTREID],[JOURNALID],[NETDEBITLOCAL],[NETCREDIT],[NETCREDITLOCAL],[GLACCOUNTID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_IX_JOURNALS] ON [CHUANSINCACTUS].[DBO].[JOURNALS] ([ROWINDEX],[ISCANCELLED],[JOURNALDATE]) INCLUDE ([JOURNALCODE],[CURRENCYID],[CURRENCYRATE],[DESCRIPTION],[NOTES]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_GLACCOUNTS] ON [CHUANSINCACTUS].[DBO].[GLACCOUNTS] ([ID],[ROWINDEX]) INCLUDE ([GLACCOUNTCODE],[ACCOUNT],[SPECIALACCOUNT],[CURRENCY],[DESCRIPTION],[NOTES],[BANKACCOUNTNO],[GSTMSICCODE],[SAC],[TARIFFCODE],[DESCRIPTION2],[PARENT],[DRCR],[ISCREDITCARD],[ISACTIVE],[ISREVALUATION],[ISSUBACCOUNT],[OPTIMISTICLOCKFIELD],[HASCHILDINCOA],[INCLUDEINCASHFLOWFORECASTADVISOR],[SSTTARIFFCODE],[ATCCODE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_PURCHASERETURNDETAILS] ON [CHUANSINCACTUS].[DBO].[PURCHASERETURNDETAILS] ([ID],[ISBUNDLED],[LOCALONECENTSDIFF]) INCLUDE ([STOCK],[DESCRIPTION]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IGLACCOUNTID_CREDITCONTROL] ON [CHUANSINCACTUS].[DBO].[CREDITCONTROL] ([GLACCOUNTID]) INCLUDE ([CREDITLIMIT],[OVERDUELIMIT],[ISPDCHEQUEINCLUDED],[OVERDUEDAYS],[OVERDUEMONTHS],[ADDITIONALCREDITLIMIT],[ADDITIONALCREDITLIMITEXPIRYDATE],[OPTIMISTICLOCKFIELD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_UQ__ARCN__DOCDATE] ON [CHUANSINCACTUS].[DBO].[ARCN] ([CNDATE],[ROWINDEX]) INCLUDE ([RECEIPTID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IMODELDIFFERENCEOBJECT_ASPECTOBJECT] ON [CHUANSINCACTUS].[DBO].[ASPECTOBJECT] ([MODELDIFFERENCEOBJECT],[OID]) INCLUDE ([NAME],[XML]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_SPECIALACCOUNTS] ON [CHUANSINCACTUS].[DBO].[SPECIALACCOUNTS] ([ID],[ROWINDEX]) INCLUDE ([ACCOUNT],[SPECIALACCOUNTCODE],[DESCRIPTION],[ACCOUNTCODE],[OPTIMISTICLOCKFIELD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IDOCUMENTID_DOCUMENTINFO] ON [CHUANSINCACTUS].[DBO].[DOCUMENTINFO] ([DOCUMENTID]) INCLUDE ([DOCTYPE],[FIRSTCREATEDDATE],[FIRSTCREATEDUSERID],[LASTMODIFIEDDATE],[LASTMODIFIEDUSERID],[PRINTCOUNT],[OPTIMISTICLOCKFIELD]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
