
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/21/2023 10:06:38 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230821100641 ON [CMS].[DBO].[INVGOODSINDETAIL] ([COUNTER],[ITEMID],[ORDERID]) INCLUDE ([PROPERTYID],[DOCUMENTID],[ITEMPRICE],[ITEMGROSSAMOUNT],[ITEMDISCOUNT],[ITEMAMOUNT],[UOMID],[BALQTY],[ITEMQTY],[TAX1AMOUNT],[TAX2AMOUNT],[TAX3AMOUNT],[TAX4AMOUNT],[ITEMREMARK]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_INVGOODSSOLDHEADER] ON [CMS].[DBO].[INVGOODSSOLDHEADER] ([DOCUMENTID],[PROPERTYID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
