
BEGIN TRY
--CURRENT VALUE: ON
USE [LineView4];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[LineView4] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [LineView4];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[LineView4] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [LineView4] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [OCS] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[OCS] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [OCS] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[OCS] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [OCS] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[OCS] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [OCS] SET TARGET_RECOVERY_TIME = 62 SECONDS;
PRINT '[OCS] TARGET_RECOVERY_TIME is set 62.';
--CURRENT VALUE: ON
USE [OCS];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[OCS] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [OCS];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[OCS] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [OCS] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [CommonDB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[CommonDB] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [CommonDB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[CommonDB] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [CommonDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [VeeamOne] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[VeeamOne] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [VeeamOne] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[VeeamOne] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [VeeamOne] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[VeeamOne] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [VeeamOne] SET TARGET_RECOVERY_TIME = 64 SECONDS;
PRINT '[VeeamOne] TARGET_RECOVERY_TIME is set 64.';
END TRY 
BEGIN CATCH
	PRINT 'Database [VeeamOne] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [LineViewXL];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[LineViewXL] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [LineViewXL];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[LineViewXL] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [LineViewXL] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [Runtime];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[Runtime] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [Runtime];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Runtime] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Runtime] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [Colos];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[Colos] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [Colos];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Colos] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Colos] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [LineView4Reports];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[LineView4Reports] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [LineView4Reports];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[LineView4Reports] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [LineView4Reports] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [Lineview];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[Lineview] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [Lineview];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Lineview] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Lineview] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;