
BEGIN TRY
USE [LineView4];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[LineView4] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [LineView4];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[LineView4] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [LineView4] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [OCS] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[OCS] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [OCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[OCS] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [OCS] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[OCS] PARAMETERIZATION is SIMPLE.';
ALTER DATABASE [OCS] SET TARGET_RECOVERY_TIME = 0 SECONDS;
PRINT '[OCS] PARAMETERIZATION is set 0.';
USE [OCS];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[OCS] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [OCS];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[OCS] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [OCS] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
USE [CommonDB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[CommonDB] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [CommonDB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[CommonDB] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [CommonDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [VeeamOne] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[VeeamOne] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [VeeamOne] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[VeeamOne] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [VeeamOne] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[VeeamOne] PARAMETERIZATION is SIMPLE.';
ALTER DATABASE [VeeamOne] SET TARGET_RECOVERY_TIME = 0 SECONDS;
PRINT '[VeeamOne] PARAMETERIZATION is set 0.';
END TRY 
BEGIN CATCH
	PRINT 'Database [VeeamOne] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
USE [LineViewXL];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[LineViewXL] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [LineViewXL];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[LineViewXL] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [LineViewXL] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
USE [Runtime];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[Runtime] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [Runtime];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Runtime] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Runtime] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
USE [Colos];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[Colos] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [Colos];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Colos] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Colos] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
USE [LineView4Reports];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[LineView4Reports] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [LineView4Reports];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[LineView4Reports] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [LineView4Reports] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
USE [Lineview];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[Lineview] DISABLE_INTERLEAVED_EXECUTION_TVF  is ON.';
USE [Lineview];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Lineview] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Lineview] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;