
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/9/2023 1:14:05 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809131408 ON [SPRITZERTAIPINGDB].[DBO].[HOST_MESSAGE] ([CLASS_TYPE],[MESSAGE],[CREATE_DATE],[MESSAGE_TYPE]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[HOST_MESSAGE_KEY],[DIRECTION],[ERROR_CODE],[ERROR_TEXT],[ERROR_TYPE],[LAST_SENT_DATE],[MESSAGE_CLASS_NAME],[MESSAGE_ID],[MESSAGE_STATUS],[RECEIVER],[RESPONSE],[SEND_ATTEMPT_COUNT],[SENDER],[TRANS_CODE]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230809131409 ON [SPRITZERTAIPINGDB].[DBO].[WORK_ZONE] ([CLASS_TYPE],[WORK_ZONE_KEY],[ORGANIZATION_NODE_KEY],[STATUS],[WORK_ZONE_ID]) INCLUDE ([CREATE_DATE],[CREATED_BY],[STATUS_DATE],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY]) ;
 END TRY BEGIN CATCH END CATCH;
