
BEGIN TRY
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_PEDIVEND_001]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_PEDIVEND_001]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N10101]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N10101] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10101] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_37967_37966]
	ON [MIMS].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N10101]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N10101] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10101] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_37967_37966]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N001006]
	ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N001006]
	ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_ITEMPEDIVEND_001]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_ITEMPEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_ITEMPEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_N00663]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_N00663] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00663] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE ENABLED.';
END CATCH;

BEGIN TRY
	ALTER INDEX [IDX_DETAITEMPEDIVEND_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] REBUILD WITH (SORT_IN_TEMPDB = ON);
	PRINT 'INDEX [IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS ENABLED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE ENABLED.';
END CATCH;
