
BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_3697_3696')
	BEGIN
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_32312_32311')
	BEGIN
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_32312_32311')
	BEGIN
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_3697_3696')
	BEGIN
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_PEDIVEND_001')
	BEGIN
	ALTER INDEX [IDX_PEDIVEND_001]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_PEDIVEND_001')
	BEGIN
	ALTER INDEX [IDX_PEDIVEND_001]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_PEDIVEND_001] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N10101')
	BEGIN
	ALTER INDEX [IDX_N10101]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_N10101] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10101] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_37967_37966')
	BEGIN
	ALTER INDEX [Hitachi_37967_37966]
	ON [MIMS].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N10101')
	BEGIN
	ALTER INDEX [IDX_N10101]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [IDX_N10101] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N10101] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_37967_37966')
	BEGIN
	ALTER INDEX [Hitachi_37967_37966]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] DISABLE;
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_37967_37966] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_3697_3696')
	BEGIN
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_32312_32311')
	BEGIN
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS_TEST].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_32312_32311')
	BEGIN
	ALTER INDEX [Hitachi_32312_32311]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_32312_32311] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'Hitachi_3697_3696')
	BEGIN
	ALTER INDEX [Hitachi_3697_3696]
	ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] DISABLE;
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [Hitachi_3697_3696] ON [MIMS].[dbo].[SISTEMA_REPLICACAO_EXCLUSAO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N001006')
	BEGIN
	ALTER INDEX [IDX_N001006]
	ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] DISABLE;
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N001006')
	BEGIN
	ALTER INDEX [IDX_N001006]
	ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] DISABLE;
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N001006] ON [MIMS_TEST].[dbo].[TRANSPORTADOR_VEICULO] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_ITEMPEDIVEND_001')
	BEGIN
	ALTER INDEX [IDX_ITEMPEDIVEND_001]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [IDX_ITEMPEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_ITEMPEDIVEND_001] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'PEDIDO_VENDA_ITEM')
	BEGIN
	ALTER INDEX [PEDIDO_VENDA_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [PEDIDO_VENDA_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_N00663')
	BEGIN
	ALTER INDEX [IDX_N00663]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] DISABLE;
	PRINT 'INDEX [IDX_N00663] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_N00663] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IDX_DETAITEMPEDIVEND_ITEM')
	BEGIN
	ALTER INDEX [IDX_DETAITEMPEDIVEND_ITEM]
	ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] DISABLE;
	PRINT 'INDEX [IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS_TEST].[dbo].[PEDIDO_VENDA_ITEM_DETALHE] CANNOT BE DISABLED.';
END CATCH;
