BEGIN TRY ALTER INDEX [Hitachi_60452_60451] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REORGANIZE;PRINT 'Index Hitachi_60452_60451 on MIMS.dbo.PRODUCAO_REGISTRO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index Hitachi_60452_60451 does not exist on MIMS.dbo.PRODUCAO_REGISTRO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IX_AIDBA_1_20220401] ON [MIMS].[dbo].[PRODUCAO_REGISTRO] REORGANIZE;PRINT 'Index IX_AIDBA_1_20220401 on MIMS.dbo.PRODUCAO_REGISTRO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IX_AIDBA_1_20220401 does not exist on MIMS.dbo.PRODUCAO_REGISTRO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [Hitachi_9640_9639] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE] REORGANIZE;PRINT 'Index Hitachi_9640_9639 on MIMS.dbo.PRODUCAO_REGISTRO_ESTOQUE has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index Hitachi_9640_9639 does not exist on MIMS.dbo.PRODUCAO_REGISTRO_ESTOQUE, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IDX_LANCESTOREGIPROD] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] REORGANIZE;PRINT 'Index IDX_LANCESTOREGIPROD on MIMS.dbo.PRODUCAO_REGISTRO_ESTOQUE_LANC has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IDX_LANCESTOREGIPROD does not exist on MIMS.dbo.PRODUCAO_REGISTRO_ESTOQUE_LANC, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IDX_FK_USUASIST_PRODREGIMOVI_ID_USUASIST] ON [MIMS].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REORGANIZE;PRINT 'Index IDX_FK_USUASIST_PRODREGIMOVI_ID_USUASIST on MIMS.dbo.PRODUCAO_REGISTRO_MOVIMENTACAO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IDX_FK_USUASIST_PRODREGIMOVI_ID_USUASIST does not exist on MIMS.dbo.PRODUCAO_REGISTRO_MOVIMENTACAO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [FX_LOOSE_PKT] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REORGANIZE;PRINT 'Index FX_LOOSE_PKT on MIMS_TEST.dbo.PRODUCAO_REGISTRO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index FX_LOOSE_PKT does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [Hitachi_60452_60451] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REORGANIZE;PRINT 'Index Hitachi_60452_60451 on MIMS_TEST.dbo.PRODUCAO_REGISTRO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index Hitachi_60452_60451 does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IDX_REGIPROD_TRANSF] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REORGANIZE;PRINT 'Index IDX_REGIPROD_TRANSF on MIMS_TEST.dbo.PRODUCAO_REGISTRO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IDX_REGIPROD_TRANSF does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IX_AIDBA_1_20220401] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO] REORGANIZE;PRINT 'Index IX_AIDBA_1_20220401 on MIMS_TEST.dbo.PRODUCAO_REGISTRO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IX_AIDBA_1_20220401 does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [Hitachi_9640_9639] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO_ESTOQUE] REORGANIZE;PRINT 'Index Hitachi_9640_9639 on MIMS_TEST.dbo.PRODUCAO_REGISTRO_ESTOQUE has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index Hitachi_9640_9639 does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO_ESTOQUE, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IDX_LANCESTOREGIPROD] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO_ESTOQUE_LANC] REORGANIZE;PRINT 'Index IDX_LANCESTOREGIPROD on MIMS_TEST.dbo.PRODUCAO_REGISTRO_ESTOQUE_LANC has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IDX_LANCESTOREGIPROD does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO_ESTOQUE_LANC, or operation encountered an error.'
				END CATCH;
				BEGIN TRY ALTER INDEX [IDX_FK_USUASIST_PRODREGIMOVI_ID_USUASIST] ON [MIMS_TEST].[dbo].[PRODUCAO_REGISTRO_MOVIMENTACAO] REORGANIZE;PRINT 'Index IDX_FK_USUASIST_PRODREGIMOVI_ID_USUASIST on MIMS_TEST.dbo.PRODUCAO_REGISTRO_MOVIMENTACAO has been reorganized'
				END TRY
				BEGIN CATCH
				PRINT 'Index IDX_FK_USUASIST_PRODREGIMOVI_ID_USUASIST does not exist on MIMS_TEST.dbo.PRODUCAO_REGISTRO_MOVIMENTACAO, or operation encountered an error.'
				END CATCH;
				