
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/14/2023 8:34:34 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230814083436 ON [SPRITZERTAIPINGDB].[DBO].[TU_TYPE] ([CLASS_TYPE],[CREATE_DATE],[TU_TYPE_ID],[CATEGORY],[HEIGHT],[WEIGHT],[DESCRIPTION],[SIS_TU_TYPE_NUMBER]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[LENGTH],[VOLUME],[WIDTH],[AVAILABLE_LOCATION_THRESHOLD],[DETRAYABLE],[KEEP_TRACKING_WHEN_EMPTY],[SCANNABLE_LABEL],[SUBDIVISION_X],[SUBDIVISION_Y],[SUBDIVISION_Z],[WEIGHT_TRACKING]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230814083451 ON [SPRITZERTAIPINGDB].[DBO].[AUDIT_TRAIL_PARAM_PROP] ([CLASS_TYPE],[AUDIT_PARAM_PROP_KEY]) INCLUDE ([PROP_LABEL],[PROP_TYPE],[PROP_VALUE],[CREATE_DATE],[CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY]) ;
 END TRY BEGIN CATCH END CATCH;
