
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 5/22/2023 6:57:58 PM UTC
*/
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK__FSW_TBLD__3214EC079F6F972D] ON [SWISSLOG].[DBO].[FSW_TBLDELORDERMASTER] ([ID]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_FARD_IX_1030] ON [SWISSLOG].[DBO].[FSW_TBLSWISSREQUEST] ([TYPENAME]) INCLUDE ([COMPANY],[EXCEPTIONERR],[KEYVALUE],[REQUESTDATE],[REQUESTID],[RESCODE],[RESDATE],[RESDESC],[RESTRANSCODE],[SERVICETYPE],[SUBTYPE],[TYPEOFACTION],[XMLREQUEST],[XMLRESPONSE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
