
/* 
This Query has been Tuned by Ai-DBA Query Optimizer (v1.4.0.0).
Copyright (C) 2019-2023 Fard Technology Corp., all rights reserved.
Date: 8/21/2023 10:28:10 AM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_230821102813 ON [SPRITZERTAIPINGDB].[DBO].[REJECT_REASON] ([CLASS_TYPE],[TRANSPORT_ORDER_KEY],[CREATE_DATE],[TU_KEY],[DESCRIPTION]) INCLUDE ([CREATED_BY],[TRANSACTION_COUNT],[UPDATE_DATE],[UPDATED_BY],[REJECT_REASON_KEY],[ARGUMENTS],[REJECT_REASON_CATEGORY],[REJECT_REASON_ID]) ;
 END TRY BEGIN CATCH END CATCH;
