


BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230518061435 ON [MIMS].[DBO].[PEDIDO_VENDA]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IX_PEDIDO_VENDA_ITEM_DETALHE_ID_ITEMPEDIVEND] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_EXCEGRUPPROD] ON [MIMS].[DBO].[PRODUCAO_GRUPO_EXCECAO] ([ID_EXCEGRUPPROD]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_MATEEMBA_06] ON [MIMS].[DBO].[MATERIAL_EMBALAGEM_FILIAL] ([ID_DEFIMATEEMBA]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;




BEGIN TRY 
    DROP INDEX [IX_AIDBA_1_20220131] ON [MIMS].[DBO].[PEDIDO_DEVO_VEND_ITEM_DETA]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;
