



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_NOTIFICATIONS] ON [REPORTSERVER].[DBO].[NOTIFICATIONS] ([NOTIFICATIONID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_CATALOG] ON [REPORTSERVER].[DBO].[CATALOG] ([ITEMID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;







BEGIN TRY 
    CREATE  INDEX [IDX_TABECUSTITEM_001] ON [MIMS].[DBO].[TABELA_CUSTO_ITEM] ([DT_VIGEFINAITEMTABECUST],[DT_VIGEINICITEMTABECUST],[ID_MATEEMBA],[ID_TABECUST]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE  INDEX [PEDIDO_VENDA_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM] ([ID_MATEEMBA],[ID_PEDIVEND],[QN_EMBAITEMPEDIVEND],[QN_PESOITEMPEDIVEND],[VL_UNITITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [IDX_DETAITEMPEDIVEND_ITEM] ON [MIMS].[DBO].[PEDIDO_VENDA_ITEM_DETALHE] ([ID_ITEMPEDIVEND]) INCLUDE ([ID_DETAITEMPEDIVEND]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_EVENT] ON [REPORTSERVER].[DBO].[EVENT] ([EVENTID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;