

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230518061221 ON [JDE_PRODUCTION].[PRODDTA].[F4140]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230518061227 ON [JDE_PRODUCTION].[PRODDTA].[F4111]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [F9001_3] ON [JDE_PRODUCTION].[PRODCTL].[F9001] ([TRFRMREL],[TRPARNTTSK],[TRPRSSEQ],[TRRLTYPE],[TRTHRREL]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F9000_2] ON [JDE_PRODUCTION].[PRODCTL].[F9000] ([TMTASKNM]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F4101_2] ON [JDE_PRODUCTION].[PRODDTA].[F4101] ([IMLITM]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F0911_PK] ON [JDE_PRODUCTION].[PRODDTA].[F0911] ([GLDCT],[GLDGJ],[GLDOC],[GLEXTL],[GLJELN],[GLKCO],[GLLT]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F952410_PK] ON [JDE_PD920].[PD920].[F952410] ([CPWOBNM],[CPWOUSER]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F00950W_2] ON [JDE920].[SY920].[F00950W] ([WSFMNM],[WSOBNM],[WSSY],[WSSYR],[WSVER],[WSWOBNM],[WSWOCAT],[WSWOSETY],[WSWOUSER]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE  INDEX [HITACHI_11354_11353_F42119] ON [JDE_PRODUCTION].[PRODDTA].[F42119] ([SDDCTO],[SDLTTR],[SDMCU],[SDSO15],[SDTORG]) INCLUDE ([SDADDJ],[SDADTM],[SDAEXP],[SDAITM],[SDALLOC],[SDAN8],[SDASN],[SDCARS],[SDCNDJ],[SDCORD],[SDCRCD],[SDCRR],[SDDCT],[SDDELN],[SDDGL],[SDDMCT],[SDDOC],[SDDOCO],[SDDRQJ],[SDDRQT],[SDDSC1],[SDDSC2],[SDDVAN],[SDEMCU],[SDFEA],[SDFRTH],[SDFUC],[SDFUP],[SDITM],[SDIVD],[SDKCO],[SDKCOO],[SDKITID],[SDLITM],[SDLNID],[SDLNTY],[SDLOCN],[SDLOTN],[SDMOT],[SDNXTR],[SDOCTO],[SDOKCO],[SDOORN],[SDOPDJ],[SDOPTT],[SDPA8],[SDPDDJ],[SDPDTT],[SDPEFJ],[SDPMPN],[SDPMTN],[SDPSIG],[SDPSN],[SDRCTO],[SDRFRV],[SDRKCO],[SDRKIT],[SDRLIT],[SDRLLN],[SDRORN],[SDRSDJ],[SDRSDT],[SDSFXO],[SDSHAN],[SDSHPN],[SDSO16],[SDSOBK],[SDSOCN],[SDSONE],[SDSOQS],[SDSQOR],[SDSRP1],[SDSRP2],[SDSRP3],[SDSRP4],[SDSRP5],[SDSWMS],[SDTRDJ],[SDUNCS],[SDUOM],[SDUOM2],[SDUOM4],[SDUORG],[SDUPRC],[SDVR01],[SDZON]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [F95921_PK] ON [JDE920].[SY920].[F95921] ([RLEFFDATE],[RLFRROLE],[RLTOROLE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;




BEGIN TRY 
    CREATE  INDEX [F0005_3] ON [JDE_PRODUCTION].[PRODCTL].[F0005] ([DRDL01],[DRRT],[DRSY]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;









BEGIN TRY 
    CREATE  INDEX [HITACHI_14422_14421_F55JDEMT] ON [JDE_PRODUCTION].[PRODDTA].[F55JDEMT] ([ELTORG],[ELYFLR]) INCLUDE ([ELCO],[ELDCTO],[ELDOCO],[ELUPMJ],[ELUPMT]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;