
BEGIN TRY
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [E101PilotRpt] SET TARGET_RECOVERY_TIME = 63 SECONDS;
PRINT '[E101PilotRpt] TARGET_RECOVERY_TIME is set 63.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101PilotRpt] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [EpicorDataDiscovery];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[EpicorDataDiscovery] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [EpicorDataDiscovery];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[EpicorDataDiscovery] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [EpicorDataDiscovery] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: 80 SECONDS
ALTER DATABASE [E101Pilot] SET TARGET_RECOVERY_TIME = 67 SECONDS;
PRINT '[E101Pilot] TARGET_RECOVERY_TIME is set 67.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101Pilot] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: 61 SECONDS
ALTER DATABASE [TSQL_AX] SET TARGET_RECOVERY_TIME = 63 SECONDS;
PRINT '[TSQL_AX] TARGET_RECOVERY_TIME is set 63.';
END TRY 
BEGIN CATCH
	PRINT 'Database [TSQL_AX] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [ExternalE101Test] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[ExternalE101Test] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [ExternalE101Test] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[ExternalE101Test] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [ExternalE101Test] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[ExternalE101Test] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 60 SECONDS
ALTER DATABASE [ExternalE101Test] SET TARGET_RECOVERY_TIME = 61 SECONDS;
PRINT '[ExternalE101Test] TARGET_RECOVERY_TIME is set 61.';
--CURRENT VALUE: ON
USE [ExternalE101Test];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[ExternalE101Test] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [ExternalE101Test];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[ExternalE101Test] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ExternalE101Test] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [TestCMS];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[TestCMS] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [TestCMS];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[TestCMS] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [TestCMS] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [ESCDB] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[ESCDB] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [ESCDB] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[ESCDB] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [ESCDB] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[ESCDB] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 60 SECONDS
ALTER DATABASE [ESCDB] SET TARGET_RECOVERY_TIME = 61 SECONDS;
PRINT '[ESCDB] TARGET_RECOVERY_TIME is set 61.';
--CURRENT VALUE: ON
USE [ESCDB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[ESCDB] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [ESCDB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[ESCDB] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ESCDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [SwissLog] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[SwissLog] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [SwissLog] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[SwissLog] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [SwissLog] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[SwissLog] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [SwissLog] SET TARGET_RECOVERY_TIME = 61 SECONDS;
PRINT '[SwissLog] TARGET_RECOVERY_TIME is set 61.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SwissLog] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: 61 SECONDS
ALTER DATABASE [SwissTest] SET TARGET_RECOVERY_TIME = 62 SECONDS;
PRINT '[SwissTest] TARGET_RECOVERY_TIME is set 62.';
--CURRENT VALUE: ON
USE [SwissTest];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[SwissTest] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [SwissTest];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[SwissTest] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SwissTest] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [E101TrainRpt] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[E101TrainRpt] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [E101TrainRpt] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[E101TrainRpt] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [E101TrainRpt] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[E101TrainRpt] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [E101TrainRpt] SET TARGET_RECOVERY_TIME = 67 SECONDS;
PRINT '[E101TrainRpt] TARGET_RECOVERY_TIME is set 67.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101TrainRpt] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: ON
USE [E101Stating_Fard];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[E101Stating_Fard] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [E101Stating_Fard];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[E101Stating_Fard] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101Stating_Fard] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: 61 SECONDS
ALTER DATABASE [E101TestRpt] SET TARGET_RECOVERY_TIME = 63 SECONDS;
PRINT '[E101TestRpt] TARGET_RECOVERY_TIME is set 63.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101TestRpt] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: 61 SECONDS
ALTER DATABASE [REPORT_DB] SET TARGET_RECOVERY_TIME = 62 SECONDS;
PRINT '[REPORT_DB] TARGET_RECOVERY_TIME is set 62.';
--CURRENT VALUE: ON
USE [REPORT_DB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[REPORT_DB] DISABLE_INTERLEAVED_EXECUTION_TVF  is OFF.';
--CURRENT VALUE: ON
USE [REPORT_DB];
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[REPORT_DB] DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [REPORT_DB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: 69 SECONDS
ALTER DATABASE [E101Train] SET TARGET_RECOVERY_TIME = 70 SECONDS;
PRINT '[E101Train] TARGET_RECOVERY_TIME is set 70.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101Train] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: SIMPLE
ALTER DATABASE [E101Test] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[E101Test] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 74 SECONDS
ALTER DATABASE [E101Test] SET TARGET_RECOVERY_TIME = 68 SECONDS;
PRINT '[E101Test] TARGET_RECOVERY_TIME is set 68.';
END TRY 
BEGIN CATCH
	PRINT 'Database [E101Test] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;