
BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_ABTWork_SysIndex')
	BEGIN
	ALTER INDEX [IX_ABTWork_SysIndex]
	ON [E101Test].[Erp].[ABTWork] DISABLE;
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Test].[Erp].[ABTWork] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Test].[Erp].[ABTWork] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_ABTWork_SysIndex')
	BEGIN
	ALTER INDEX [IX_ABTWork_SysIndex]
	ON [E101Pilot].[Erp].[ABTWork] DISABLE;
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Pilot].[Erp].[ABTWork] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Pilot].[Erp].[ABTWork] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_ABTWork_SysIndex')
	BEGIN
	ALTER INDEX [IX_ABTWork_SysIndex]
	ON [E101Train].[Erp].[ABTWork] DISABLE;
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Train].[Erp].[ABTWork] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_ABTWork_SysIndex] ON [E101Train].[Erp].[ABTWork] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Train].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Train].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Train].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_64087')
	BEGIN
	ALTER INDEX [FARD_IX_64087]
	ON [E101Train].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_64087] ON [E101Train].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_64087] ON [E101Train].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Pilot].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Pilot].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Pilot].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_64087')
	BEGIN
	ALTER INDEX [FARD_IX_64087]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_64087] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_64087] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_64087')
	BEGIN
	ALTER INDEX [FARD_IX_64087]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_64087] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_64087] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_64087')
	BEGIN
	ALTER INDEX [FARD_IX_64087]
	ON [E101Train].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_64087] ON [E101Train].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_64087] ON [E101Train].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Train].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Train].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Train].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_AgentTask')
	BEGIN
	ALTER INDEX [IX_SysTask_AgentTask]
	ON [E101Pilot].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Pilot].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_AgentTask] ON [E101Pilot].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_StartedOn')
	BEGIN
	ALTER INDEX [IX_SysTask_StartedOn]
	ON [E101Train].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Train].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Train].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_144')
	BEGIN
	ALTER INDEX [FARD_IX_144]
	ON [E101Train].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_144] ON [E101Train].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_144] ON [E101Train].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_StartedOn')
	BEGIN
	ALTER INDEX [IX_SysTask_StartedOn]
	ON [E101Pilot].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Pilot].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Pilot].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_144')
	BEGIN
	ALTER INDEX [FARD_IX_144]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_144] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_144] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_StartedOn')
	BEGIN
	ALTER INDEX [IX_SysTask_StartedOn]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'IX_SysTask_StartedOn')
	BEGIN
	ALTER INDEX [IX_SysTask_StartedOn]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_SysTask_StartedOn] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;

BEGIN TRY
	IF EXISTS(  SELECT 1 FROM SYS.INDEXES I WHERE I.[IS_PRIMARY_KEY] = 1 AND I.[NAME] = 'FARD_IX_144')
	BEGIN
	ALTER INDEX [FARD_IX_144]
	ON [E101Test].[Ice].[SysTask] DISABLE;
	PRINT 'INDEX [FARD_IX_144] ON [E101Test].[Ice].[SysTask] IS DISABLED.';
	END
END TRY
BEGIN CATCH
	PRINT 'INDEX [FARD_IX_144] ON [E101Test].[Ice].[SysTask] CANNOT BE DISABLED.';
END CATCH;
