
USE [FusionOperational];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230502 ON [FusionOperational].[dbo].[Cycle];
		PRINT N'INDEX IX_AIDBA_1_20230502 ON [FusionOperational].[dbo].[Cycle] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230502 ON [FusionOperational].[dbo].[Cycle] CANNOT BE DROPPED.';
END CATCH;

USE [FusionDW];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230502 ON [FusionDW].[dbo].[FactDowntime];
		PRINT N'INDEX IX_AIDBA_2_20230502 ON [FusionDW].[dbo].[FactDowntime] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230502 ON [FusionDW].[dbo].[FactDowntime] CANNOT BE DROPPED.';
END CATCH;

USE [FusionDW];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230502 ON [FusionDW].[dbo].[ETLWatermark];
		PRINT N'INDEX IX_AIDBA_3_20230502 ON [FusionDW].[dbo].[ETLWatermark] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230502 ON [FusionDW].[dbo].[ETLWatermark] CANNOT BE DROPPED.';
END CATCH;

USE [FusionOperational];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230502 ON [FusionOperational].[dbo].[Downtime];
		PRINT N'INDEX IX_AIDBA_4_20230502 ON [FusionOperational].[dbo].[Downtime] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230502 ON [FusionOperational].[dbo].[Downtime] CANNOT BE DROPPED.';
END CATCH;

USE [FusionDW];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230502')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230502 ON [FusionDW].[dbo].[FactProduction];
		PRINT N'INDEX IX_AIDBA_5_20230502 ON [FusionDW].[dbo].[FactProduction] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230502 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230502 ON [FusionDW].[dbo].[FactProduction] CANNOT BE DROPPED.';
END CATCH;
