
USE [IDB_MTECH_MAREL_SL];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230822 ON [IDB_MTECH_MAREL_SL].[dbo].[ITF_PRODUCTION];
		PRINT N'INDEX IX_AIDBA_1_20230822 ON [IDB_MTECH_MAREL_SL].[dbo].[ITF_PRODUCTION] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230822 ON [IDB_MTECH_MAREL_SL].[dbo].[ITF_PRODUCTION] CANNOT BE DROPPED.';
END CATCH;

USE [IDB_MTECH_MAREL_SL];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230822 ON [IDB_MTECH_MAREL_SL].[dbo].[cust_itgr_FlockStatus_Export_History];
		PRINT N'INDEX IX_AIDBA_2_20230822 ON [IDB_MTECH_MAREL_SL].[dbo].[cust_itgr_FlockStatus_Export_History] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230822 ON [IDB_MTECH_MAREL_SL].[dbo].[cust_itgr_FlockStatus_Export_History] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230822 ON [innova].[dbo].[base_guinodes];
		PRINT N'INDEX IX_AIDBA_3_20230822 ON [innova].[dbo].[base_guinodes] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230822 ON [innova].[dbo].[base_guinodes] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230822 ON [innova].[dbo].[grd_pieceregs];
		PRINT N'INDEX IX_AIDBA_4_20230822 ON [innova].[dbo].[grd_pieceregs] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230822 ON [innova].[dbo].[grd_pieceregs] CANNOT BE DROPPED.';
END CATCH;

USE [PDSNT];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230822 ON [PDSNT].[dbo].[PDA_QTD_ARCHIVE];
		PRINT N'INDEX IX_AIDBA_5_20230822 ON [PDSNT].[dbo].[PDA_QTD_ARCHIVE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230822 ON [PDSNT].[dbo].[PDA_QTD_ARCHIVE] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_6_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_6_20230822 ON [innova].[dbo].[proc_packs];
		PRINT N'INDEX IX_AIDBA_6_20230822 ON [innova].[dbo].[proc_packs] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_6_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_6_20230822 ON [innova].[dbo].[proc_packs] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_7_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_7_20230822 ON [innova].[dbo].[proc_prcontexthistory];
		PRINT N'INDEX IX_AIDBA_7_20230822 ON [innova].[dbo].[proc_prcontexthistory] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_7_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_7_20230822 ON [innova].[dbo].[proc_prcontexthistory] CANNOT BE DROPPED.';
END CATCH;

USE [PDSNT];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_8_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_8_20230822 ON [PDSNT].[dbo].[PDA_RTD_ARCHIVE];
		PRINT N'INDEX IX_AIDBA_8_20230822 ON [PDSNT].[dbo].[PDA_RTD_ARCHIVE] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_8_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_8_20230822 ON [PDSNT].[dbo].[PDA_RTD_ARCHIVE] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_9_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_9_20230822 ON [innova].[dbo].[proc_orders];
		PRINT N'INDEX IX_AIDBA_9_20230822 ON [innova].[dbo].[proc_orders] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_9_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_9_20230822 ON [innova].[dbo].[proc_orders] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_10_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_10_20230822 ON [innova].[dbo].[proc_lots];
		PRINT N'INDEX IX_AIDBA_10_20230822 ON [innova].[dbo].[proc_lots] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_10_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_10_20230822 ON [innova].[dbo].[proc_lots] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_11_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_11_20230822 ON [innova].[dbo].[proc_prperiods];
		PRINT N'INDEX IX_AIDBA_11_20230822 ON [innova].[dbo].[proc_prperiods] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_11_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_11_20230822 ON [innova].[dbo].[proc_prperiods] CANNOT BE DROPPED.';
END CATCH;

USE [innova];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_12_20230822')
	BEGIN
		DROP INDEX IX_AIDBA_12_20230822 ON [innova].[dbo].[base_recordhistory];
		PRINT N'INDEX IX_AIDBA_12_20230822 ON [innova].[dbo].[base_recordhistory] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_12_20230822 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_12_20230822 ON [innova].[dbo].[base_recordhistory] CANNOT BE DROPPED.';
END CATCH;
