

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_230822104337 ON [PDSNT].[DBO].[AQS_TRAJECT_DEFINITION]; 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROC_ORDERL] ON [INNOVA].[DBO].[PROC_ORDERL] ([ID]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [PK_PROC_LOTS] ON [INNOVA].[DBO].[PROC_LOTS] ([LOT]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;


BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROC_ORDERSERVICEPROCESSES_ORDERPROCESS_ORDERPROCESSTYPE] ON [INNOVA].[DBO].[PROC_ORDERSERVICEPROCESSES] ([ORDERPROCESS],[ORDERPROCESSTYPE]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    CREATE UNIQUE INDEX [IX_PROC_RECIPEBATCHES_LOT] ON [INNOVA].[DBO].[PROC_RECIPEBATCHES] ([LOT]) WITH (DROP_EXISTING=ON ); 
END TRY 
BEGIN CATCH 
END CATCH;