
USE [ClubOn];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_1_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_1_20230506 ON [ClubOn].[dbo].[RetTransactionMaster];
		PRINT N'INDEX IX_AIDBA_1_20230506 ON [ClubOn].[dbo].[RetTransactionMaster] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_1_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_1_20230506 ON [ClubOn].[dbo].[RetTransactionMaster] CANNOT BE DROPPED.';
END CATCH;

USE [CMS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_2_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_2_20230506 ON [CMS].[dbo].[invDepartmentItemMovement];
		PRINT N'INDEX IX_AIDBA_2_20230506 ON [CMS].[dbo].[invDepartmentItemMovement] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_2_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_2_20230506 ON [CMS].[dbo].[invDepartmentItemMovement] CANNOT BE DROPPED.';
END CATCH;

USE [FAS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_3_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_3_20230506 ON [FAS].[dbo].[GlJournalHeader];
		PRINT N'INDEX IX_AIDBA_3_20230506 ON [FAS].[dbo].[GlJournalHeader] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_3_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_3_20230506 ON [FAS].[dbo].[GlJournalHeader] CANNOT BE DROPPED.';
END CATCH;

USE [ClubOn];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_4_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_4_20230506 ON [ClubOn].[dbo].[mrmPaymentMaster];
		PRINT N'INDEX IX_AIDBA_4_20230506 ON [ClubOn].[dbo].[mrmPaymentMaster] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_4_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_4_20230506 ON [ClubOn].[dbo].[mrmPaymentMaster] CANNOT BE DROPPED.';
END CATCH;

USE [FAS];
BEGIN TRY
BEGIN TRAN
	IF EXISTS ( SELECT * FROM sys.indexes WHERE name = N'IX_AIDBA_5_20230506')
	BEGIN
		DROP INDEX IX_AIDBA_5_20230506 ON [FAS].[dbo].[GlTransaction];
		PRINT N'INDEX IX_AIDBA_5_20230506 ON [FAS].[dbo].[GlTransaction] IS DROPPED.';
	END
	ELSE
	BEGIN
		PRINT N'There is no index named IX_AIDBA_5_20230506 in the database.';
	END

COMMIT TRAN
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
ROLLBACK TRAN
	PRINT N'INDEX IX_AIDBA_5_20230506 ON [FAS].[dbo].[GlTransaction] CANNOT BE DROPPED.';
END CATCH;
