
BEGIN TRY
--CURRENT VALUE: OFF
ALTER DATABASE [SPRITZERTAIPINGDWH] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [SPRITZERTAIPINGDWH] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [SPRITZERTAIPINGDWH] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] PARAMETERIZATION is FORCED.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDWH] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
--CURRENT VALUE: SIMPLE
ALTER DATABASE [SPRITZERTAIPINGDB] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDB] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: 0 SECONDS
ALTER DATABASE [SPRITZERTAIPINGDB] SET TARGET_RECOVERY_TIME = 61 SECONDS;
PRINT '[SPRITZERTAIPINGDB] TARGET_RECOVERY_TIME is set 61.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;