
BEGIN TRY
ALTER DATABASE [SPRITZERTAIPINGDWH] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [SPRITZERTAIPINGDWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [SPRITZERTAIPINGDWH] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDWH] PARAMETERIZATION is SIMPLE.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDWH] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY
ALTER DATABASE [SPRITZERTAIPINGDB] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[SPRITZERTAIPINGDB] PARAMETERIZATION is SIMPLE.';
ALTER DATABASE [SPRITZERTAIPINGDB] SET TARGET_RECOVERY_TIME = 0 SECONDS;
PRINT '[SPRITZERTAIPINGDB] PARAMETERIZATION is set 0.';
END TRY 
BEGIN CATCH
	PRINT 'Database [SPRITZERTAIPINGDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;